from pathlib import Path
import datetime as dt, html, json

DATE='2026-07-23'; STAMP=dt.datetime.now(dt.timezone.utc).isoformat()
OUT=Path('/root/Projects/artifact-library/artifacts/daily-ingest'); OUT.mkdir(parents=True,exist_ok=True)
lanes=[
{'slug':'agent-sandbox-tool-controls','title':'Agent Sandbox + Tool Controls','rationale':'This is a fresh control-surface lane, selected after several days centered on evaluation and adoption: new releases make credential injection, harness substitution, and MCP exposure explicit configuration choices rather than hidden framework behavior.','readout':'The useful pattern is not “give an agent more tools.” Put tool exposure, credentials, and execution harnesses behind independent, replaceable boundaries. That makes a client pilot easier to audit and easier to stop.','sources':[
{'title':'Agents SDK reduces MCP schema conversion and adds exposure controls','url':'https://developers.cloudflare.com/changelog/post/2026-07-22-mcp-codemode-updates/','source_type':'release','published_or_updated':'2026-07-22','what':'Cloudflare added a switch to opt out of Think’s automatic MCP tool exposure and direct host APIs for its Code Mode runtime.','why':'Automatic tool discovery is convenient but expands an agent’s effective authority. An explicit opt-in creates a review point.','usecase':'Use a per-workflow allowlist: start with read-only tools, add an action tool only with an owner and test case, then log every call.','caveat':'A framework flag is not a security boundary by itself; enforce authorization and data scope at each tool endpoint.','action':'Prototype one MCP workflow with `includeMcpTools = false`; add only the two tools required for its acceptance test.'},
{'title':'Safely inject credentials in HTTP headers with Vercel Sandbox','url':'https://vercel.com/changelog/safely-inject-credentials-in-http-headers-with-vercel-sandbox','source_type':'release','published_or_updated':'unknown','what':'Vercel Sandbox can inject outbound HTTP headers at the network-policy layer, so sandboxed code calls an approved service without receiving the raw secret.','why':'It separates agent runtime access from credential possession and supports a setup phase followed by deny-all execution.','usecase':'For repository analysis or agent testing, allow credentials only for a short clone/bootstrap phase; remove egress and secrets before untrusted commands run.','caveat':'Header injection still grants capability to the sandbox for allowed destinations; constrain hostnames, paths where possible, and timeouts.','action':'Turn an existing sandbox policy into a two-phase policy: authenticated setup, then deny-all execution.'},
{'title':'Program Claude Code, Codex, Pi and other agent harnesses with AI SDK','url':'https://vercel.com/changelog/program-agent-harnesses-with-ai-sdk','source_type':'release','published_or_updated':'unknown','what':'AI SDK 7’s experimental HarnessAgent presents one session API around Claude Code, Codex, and Pi adapters.','why':'Treating the harness as a replaceable implementation lets a workflow retain its policy, tools, skills, and acceptance checks while evaluation compares runners.','usecase':'Build a small harness bake-off around a real bounded task: same repo snapshot, tools, budget, sandbox, and test command; compare completed work, cost, and cleanup.','caveat':'The adapters are experimental and may break; avoid making the abstraction itself a production dependency without pinning and a fallback.','action':'Pick one repetitive repair task and run it through two harnesses under identical limits.'},
{'title':'Gemini Enterprise supports unauthenticated Custom MCP Server data stores (Preview)','url':'https://docs.cloud.google.com/release-notes','source_type':'release notes','published_or_updated':'2026-07-22','what':'Google Cloud’s release notes announce preview support for unauthenticated Custom MCP Server data stores in Gemini Enterprise.','why':'This is a sharp reminder that “easy connector setup” can turn an unauthenticated endpoint into part of a business answer path.','usecase':'Before connecting any client knowledge endpoint, classify it public/internal/restricted and require an authenticated retrieval path for internal material.','caveat':'The search result describes a preview feature only; confirm exact product behavior and tenancy controls in the current documentation before use.','action':'Add “connector authentication and audience” to the agent integration review checklist.'}]},
{'slug':'web-runtime-patch-and-access','title':'Web Runtime Patch + Access Hygiene','rationale':'This lane rotates away from repeated model news toward immediate web-stack maintenance. The sources are primary notices with concrete versions, dates, and least-privilege changes that can become a short client operations checklist.','readout':'Patch the exposed framework first, then reduce the authority of the data and support paths around it. The practical win is a small, owned maintenance queue—not a generic security posture statement.','sources':[
{'title':'Next.js July 2026 Security Release','url':'https://nextjs.org/blog/july-2026-security-release','source_type':'security release','published_or_updated':'2026-07-20','what':'Next.js published fixes in 16.2.11 and 15.5.21 for Image Optimization CPU exhaustion, Edge Server Action memory use, and response-body cache confusion.','why':'The release turns a broad framework risk into concrete upgrade targets, including issues relevant to App Router, Server Actions, and server-side fetch.','usecase':'Inventory client Next.js versions, identify exposed image optimization and Edge paths, update a staging property, and execute route-level smoke tests before production rollout.','caveat':'Impact depends on configuration and route usage; do not claim exposure without checking each deployed application.','action':'Open a patch ticket today with owner, deployed version, target version, test route, and rollout window.'},
{'title':'Upcoming GHES change impacting uploading support bundles','url':'https://github.blog/changelog/2026-07-22-upcoming-ghes-change-impacting-uploading-support-bundles/','source_type':'notice','published_or_updated':'2026-07-22','what':'From August 18, GitHub will reject command-line support-bundle uploads from GHES appliances below specified patched releases.','why':'Supportability is an operational dependency: an appliance that cannot upload diagnostic bundles is harder to recover precisely when an incident needs vendor help.','usecase':'For any self-hosted GitHub client, record the appliance version, required patch line, owner, maintenance window, and a post-upgrade support-bundle test.','caveat':'This applies to GitHub Enterprise Server appliances, not GitHub.com organizations.','action':'Check GHES inventory and schedule required patching before the August 18 enforcement date.'},
{'title':'R2 Data Catalog now supports read-only API tokens','url':'https://developers.cloudflare.com/changelog/post/2026-07-09-r2-data-catalog-read-only-tokens/','source_type':'release','published_or_updated':'2026-07-09','what':'Cloudflare R2 Data Catalog now accepts tokens scoped to catalog and storage read operations, while writes retain read-write requirements.','why':'Analytics and retrieval clients no longer need a write-capable credential merely to list tables or query data.','usecase':'Split ingestion and query identities for client reporting or RAG pipelines; issue read-only credentials to DuckDB, PyIceberg, or R2 SQL consumers.','caveat':'Vended credentials inherit R2 storage permissions, so catalog scope alone does not make a token read-only.','action':'Audit catalog consumers and replace every query-only credential with storage-and-catalog read-only scope.'},
{'title':'View total SQLite storage for Durable Object namespaces','url':'https://developers.cloudflare.com/changelog/post/2026-07-20-durable-objects-total-storage-metrics/','source_type':'release','published_or_updated':'2026-07-20','what':'Cloudflare added an hourly Total storage chart for SQLite-backed Durable Object namespaces.','why':'Stateful agent and collaboration workflows can fail quietly through retention and growth; an aggregate time series makes cleanup assumptions testable.','usecase':'Add storage growth to the operational review for Durable Object–backed sessions, queues, or client workspaces; define retention and an alert threshold.','caveat':'The chart is aggregate-only and unavailable for legacy key-value storage namespaces.','action':'Review the largest stateful namespace, document retention behavior, and set a weekly growth check.'}]},
{'slug':'agent-adoption-measurement','title':'Agent Adoption Measurement','rationale':'Recent dossiers covered agent evaluation and cost concepts, but not the new organizational surface for measuring developer adoption. This lane earns inclusion because a fresh GitHub dashboard provides a concrete starting point for separating activity from delivered impact.','readout':'Measure agent adoption as a sequence: enabled → used → accepted → shipped → maintained. A usage chart alone is not proof of client value, but it can identify where to ask better questions.','sources':[
{'title':'New Copilot usage metrics impact dashboard','url':'https://github.blog/changelog/2026-07-22-new-copilot-usage-metrics-impact-dashboard/','source_type':'release','published_or_updated':'2026-07-22','what':'GitHub released a Copilot metrics impact dashboard for enterprise administrators and organization owners.','why':'It provides a native administrative surface for adoption conversations instead of relying on anecdotal prompts or license counts.','usecase':'Pair dashboard signals with repository delivery measures: PR cycle time, review rework, incident escape, and developer-reported friction for one pilot cohort.','caveat':'Metrics dashboards can show correlation, not causation; avoid tying individual performance management to tool telemetry.','action':'Define a four-week pilot baseline before enabling a new agent capability for a selected team.'},
{'title':'Access and share AI Gateway leaderboard data','url':'https://vercel.com/changelog/open-data-and-shareable-charts-for-ai-gateway-leaderboards','source_type':'release','published_or_updated':'2026-07-21','what':'Vercel made AI Gateway leaderboard data downloadable and shareable under CC BY 4.0.','why':'External production-routing data can seed model-shortlisting hypotheses, but it should not replace a workload-specific evaluation.','usecase':'Use the dataset to select three candidate models, then run a Buildn/client task suite for quality, latency, cost, refusal behavior, and tool reliability.','caveat':'Aggregate gateway traffic reflects Vercel’s observed population, not a client’s policy, region, inputs, or quality bar.','action':'Write a one-page model scorecard before changing a production default.'},
{'title':'Vercel AI Gateway Production Index — July 2026','url':'https://vercel.com/blog/ai-gateway-production-index-july-2026','source_type':'blog','published_or_updated':'2026-07-21','what':'Vercel’s July index reports production routing and spend patterns, including a gap between open-weight token volume and spend share.','why':'The split is a useful warning against treating token volume, capability, and operating economics as the same metric.','usecase':'For a mixed model stack, track task outcome and total cost per completed workflow alongside tokens, latency, and fallback rate.','caveat':'This is vendor-observed aggregate data; do not infer that an open-weight model is right for a sensitive client workload.','action':'Add outcome-per-dollar and fallback rate to the next agent workflow review.'},
{'title':'OpenAI: A scorecard for the AI age','url':'https://openai.com/index/a-scorecard-for-the-ai-age/','source_type':'blog','published_or_updated':'2026-07-20','what':'OpenAI proposes measuring useful intelligence per dollar through completed work, full cost, dependability, and scaling value.','why':'It reinforces a customer-facing measurement frame: value comes from finished, dependable work rather than model theater.','usecase':'Translate an agent pilot into baseline minutes per completed job, acceptance rate, exception rate, human-review minutes, and fully loaded cost.','caveat':'It is a vendor framework, not a substitute for a client’s actual revenue, risk, and quality constraints.','action':'Make “completed work with evidence” the primary success criterion for the next client pilot.'}]}
]

def e(x): return html.escape(str(x),quote=True)
def logo(): return '<svg viewBox="0 0 32 32" width="23" aria-hidden="true"><path fill="#01dc82" d="M5 3h20l4 5-3 19-5 3H3l2-18z"/><path fill="#033330" d="M12 8h11l-1 7h-8l-1 9H7l1-7h4z"/></svg>'
css='''<style>:root{--brand:#01dc82;--deep:#033330;--lime:#cfe66a;--ink:#0f172a;--muted:#475569;--line:#e2e8f0;--bg:#fafaf9;--card:#fff;--serif:"Newsreader",Georgia,serif;--sans:"Plus Jakarta Sans",system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.55 var(--sans)}main{max-width:64rem;margin:auto;padding:3rem 1.4rem 4rem}h1,h2,h3{font-family:var(--serif);color:var(--deep);line-height:1.13}h1{font-size:2.25rem;margin:.5rem 0}h2{font-size:1.32rem;margin:.5rem 0}a{color:#087f51}.wordmark{display:flex;align-items:center;gap:.55rem;font-weight:700;color:var(--deep)}.date,.kicker{font:12px ui-monospace,monospace;color:var(--muted);letter-spacing:.04em}.kicker{color:#087f51;font-weight:700}.lead{font-size:1.04rem;max-width:56rem}.card,.item{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:1.3rem;margin:1.25rem 0}.diagram{border:1px solid var(--line);border-radius:9px;padding:.8rem;margin:1rem 0;background:#fff}.diagram svg{display:block;width:100%;height:auto}.label{font:700 10px var(--sans);fill:#475569;letter-spacing:.08em}.small{font:12px var(--sans);fill:#475569}.badges{display:flex;gap:.45rem;flex-wrap:wrap}.badge{font-size:10px;letter-spacing:.06em;text-transform:uppercase;font-weight:700;background:#f1f5f9;color:#475569;padding:.2rem .45rem;border-radius:5px}.good{background:#dcfce7;color:#166534}dl{margin:1rem 0}dt{font-size:11px;font-weight:700;color:#087f51;text-transform:uppercase;letter-spacing:.06em}dd{margin:0 0 .65rem}.action{border-left:3px solid var(--brand);background:#effdf6;padding:.6rem .8rem;margin:0}.matrix{width:100%;border-collapse:collapse;font-size:.85rem}.matrix th,.matrix td{border-bottom:1px solid var(--line);padding:.55rem;text-align:left}.matrix td{text-align:center;color:#087f51}.trail{padding-left:1.2rem}.callout{background:#fffbeb;border-left:3px solid #9a6700;padding:.7rem .9rem;color:#713f12}</style>'''
def map_svg(title): return f'''<div class="diagram"><svg viewBox="0 0 720 150" role="img" aria-label="Signal map for {e(title)}"><defs><marker id="a" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L7 4 0 8Z" fill="#94a3b8"/></marker></defs><text x="15" y="22" class="label">SIGNAL MAP · {e(title).upper()}</text><rect x="15" y="50" width="185" height="64" rx="9" fill="#fff" stroke="#cbd5e1"/><text x="107" y="78" text-anchor="middle" class="label">RELEASE / NOTICE</text><text x="107" y="98" text-anchor="middle" class="small">specific new change</text><line x1="201" y1="82" x2="278" y2="82" stroke="#94a3b8" stroke-width="2" marker-end="url(#a)"/><rect x="280" y="50" width="185" height="64" rx="9" fill="#effdf6" stroke="#01dc82"/><text x="372" y="78" text-anchor="middle" class="label">OPERATING RULE</text><text x="372" y="98" text-anchor="middle" class="small">scope · verify · own</text><line x1="466" y1="82" x2="543" y2="82" stroke="#94a3b8" stroke-width="2" marker-end="url(#a)"/><rect x="545" y="50" width="160" height="64" rx="9" fill="#fff" stroke="#cbd5e1"/><text x="625" y="78" text-anchor="middle" class="label">NEXT ACTION</text><text x="625" y="98" text-anchor="middle" class="small">small + reversible</text><path d="M108 132H625" stroke="#cfe66a" stroke-width="5" stroke-linecap="round"/></svg></div>'''
def report(l):
 cards=''.join(f'''<article class="item"><div class="badges"><span class="badge good">{e(s['source_type'])}</span><span class="badge">{e(s['published_or_updated'])}</span></div><h2><a href="{e(s['url'])}">{e(s['title'])}</a></h2><dl><dt>What it is</dt><dd>{e(s['what'])}</dd><dt>Why it matters</dt><dd>{e(s['why'])}</dd><dt>Buildn / client use</dt><dd>{e(s['usecase'])}</dd><dt>Caveat</dt><dd>{e(s['caveat'])}</dd></dl><p class="action"><b>Follow-up action:</b> {e(s['action'])}</p></article>''' for s in l['sources'])
 rows=''.join(f'<tr><th>{e(s["title"][:42])}</th><td>●</td><td>●</td><td>●</td><td>○</td></tr>' for s in l['sources'])
 trail=''.join(f'<li><a href="{e(s["url"])}">{e(s["title"])}</a></li>' for s in l['sources'])
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily Ingest Dossier — {e(l['title'])} — {DATE}</title><meta name="lib:group" content="report"><meta name="lib:date" content="{DATE}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">{css}</head><body><main><header><div class="wordmark">{logo()}<span>Buildn</span></div><p class="kicker">DAILY INGEST DOSSIER · {DATE}</p><h1>{e(l['title'])}</h1><p class="lead">{e(l['readout'])}</p></header><section class="card"><h2>Signal map</h2>{map_svg(l['title'])}<p class="callout">Selection: {e(l['rationale'])}</p></section><section><h2>Dossier cards</h2>{cards}</section><section class="card"><h2>Use-case matrix</h2><table class="matrix"><tr><th>Signal</th><th>Buildn OS</th><th>Client work</th><th>Agent workflows</th><th>Personal</th></tr>{rows}</table></section><section class="card"><h2>Top actions</h2><ol>{''.join(f'<li>{e(s["action"])}</li>' for s in l['sources'][:3])}</ol></section><section class="card"><h2>Source trail</h2><ul class="trail">{trail}</ul></section></main></body></html>'''
ledger={'date':DATE,'generated_at':STAMP,'editorial_thesis':'Today’s practical signal is operational control: make agent authority explicit, patch exposed runtimes, and measure adoption by completed work rather than activity.','topic_groups':[{'slug':l['slug'],'title':l['title'],'selection_rationale':l['rationale'],'sources':[{k:s[k] for k in ('title','url','source_type','published_or_updated')}|{'why_selected':s['why'],'usefulness':s['action']} for s in l['sources']]} for l in lanes]}
for l in lanes: (OUT/f'daily-ingest-{l["slug"]}-20260723.html').write_text(report(l),encoding='utf8')
(OUT/'daily-ingest-20260723.json').write_text(json.dumps(ledger,indent=2)+'\n')
links=''.join(f'<article class="item"><h2><a href="{e(l["slug"])}.html">{e(l["title"])}</a></h2><p>{e(l["rationale"])}</p></article>' for l in lanes)
overview=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily Ingest Dossier — {DATE}</title><meta name="lib:group" content="report"><meta name="lib:date" content="{DATE}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">{css}</head><body><main><div class="wordmark">{logo()}<span>Buildn</span></div><p class="kicker">DAILY INGEST DOSSIER · {DATE}</p><h1>Control the seams</h1><p class="lead">Today’s practical signal is operational control: make agent authority explicit, patch exposed runtimes, and measure adoption by completed work rather than activity.</p><section class="card"><h2>Selected lanes</h2>{links}</section><section class="card"><h2>All-lanes top three</h2><ol><li>Build a two-phase sandbox policy: authenticated setup, then deny-all execution.</li><li>Patch exposed Next.js deployments to the applicable July security release.</li><li>Baseline a four-week agent pilot against completed work, review cost, and fallback rate.</li></ol></section></main></body></html>'''
(OUT/'daily-ingest-overview-20260723.html').write_text(overview,encoding='utf8')
coverage_path=Path('/root/Projects/daily-ingest-pages/topic-coverage.json'); coverage=json.loads(coverage_path.read_text()); hist=coverage.get('item_history',[])
for l in lanes:
 for s in reversed(l['sources']): hist.insert(0,{'date':DATE,'lane':l['slug'],'title':s['title'],'url':s['url'],'source_type':s['source_type'],'selection_rationale':s['why']})
summary=coverage.setdefault('rolling_theme_summary',{})
for l in lanes:
 old=summary.get(l['slug'],{});summary[l['slug']]={'title':l['title'],'times_covered':old.get('times_covered',0)+1,'last_covered':DATE}
coverage['item_history']=hist[:300];coverage['updated_at']=STAMP
coverage_path.write_text(json.dumps(coverage,indent=2)+'\n')
print('generated',len(lanes),'lanes')
