from pathlib import Path
import json, html, datetime
R=Path('/root/Projects/daily-ingest-pages'); O=R/'2026-09-30'; O.mkdir(exist_ok=True)
css='''<style>:root{--g:#01dc82;--d:#033330;--i:#0f172a;--m:#475569;--l:#e2e8f0;--b:#fafaf9}*{box-sizing:border-box}body{margin:0;background:var(--b);color:var(--i);font:15px/1.55 Arial,sans-serif}main{max-width:980px;margin:auto;padding:38px 22px}h1,h2{font-family:Georgia,serif;color:var(--d)}h1{font-size:34px}h2{font-size:23px}.word{color:var(--d);font-weight:bold}.mark{display:inline-block;width:18px;height:22px;background:var(--g);vertical-align:middle;margin-right:8px;clip-path:polygon(20% 0,100% 0,85% 58%,65% 58%,60% 100%,0 100%,10% 37%,18% 34%)}.read{font-size:17px;max-width:780px}.card{background:#fff;border:1px solid var(--l);border-radius:10px;padding:20px;margin:17px 0}.tag{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:var(--m)}.badges span{background:#eef2f7;padding:3px 8px;border-radius:4px;font-size:11px;margin-right:5px}.good{background:#dcfce7!important;color:#166534}.facts{color:var(--m);font:12px monospace}.facts a,.sources a,a{color:#087f52}.diagram{border:1px solid var(--l);padding:12px;border-radius:7px}.diagram svg{width:100%;height:auto}.call{border-left:3px solid #9a6700;background:#fffbeb;color:#713f12;padding:9px 12px}.wins{padding-left:20px}.matrix{width:100%;border-collapse:collapse;font-size:13px}.matrix th,.matrix td{padding:8px;border-bottom:1px solid var(--l);text-align:left;vertical-align:top}.matrix th{background:#f8fafc;color:var(--d)}.top{border-left:4px solid var(--g)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}.node{border:1px solid var(--l);padding:12px;border-radius:7px}footer{font-size:12px;color:var(--m);margin-top:28px}</style>'''
def svg(names):
 s='<svg viewBox="0 0 700 105" role="img" aria-label="Signal map">'; xs=[10,185,360,535]
 for n,x in zip(names,xs): s+=f'<rect x="{x}" y="23" width="145" height="55" rx="7" fill="#dcfce7" stroke="#cbd5e1"/><text x="{x+72}" y="55" text-anchor="middle" font-family="Arial" font-size="13" fill="#475569">{html.escape(n)}</text>'
 for x in xs[:-1]: s+=f'<line x1="{x+145}" y1="50" x2="{x+173}" y2="50" stroke="#94a3b8" stroke-width="2"/>'
 return s+'</svg>'
def item(title,typ,date,url,what,why,use,now,caveat,action): return locals()
lanes={
'agent-platforms':('Persistent agents move from prompt to operating layer','Persistent work, cheaper long-horizon inference, and agent access inside existing developer surfaces are converging. Treat this as an operations and cost-design problem, not a chat UX upgrade.',['Persistent','Model economics','Remote execution','Embedded surfaces'],[
item('Dots: an always-on project steward','product','2026-09-29','https://openai.com/index/introducing-dots/','OpenAI describes persistent agents with their own cloud computer, browser, connected apps, parallel workstreams, and activity inspection.','The unit of automation becomes an owned workstream with memory and review.','Prototype a bounded project steward that maintains a decision log and returns reviewable artifacts.','Always-on agents force explicit scope, escalation, and evidence policies.','Access tiers may shift. Start with synthetic or low-risk data.','Run a 7-day steward experiment with approval checkpoints.'),
item('GPT-6.1 Sol: lower-cost long-horizon work','model','2026-09-29','https://openai.com/index/introducing-gpt-6-1-sol/','OpenAI positions GPT-6.1 Sol near Astra performance for coding, computer use, and professional workflows at roughly one-fifth the standard price.','Cheap context reuse changes the economics of agents that revisit project state.','Benchmark Buildn tasks by quality, retries, latency, and cost.','Model routing can now be governed by task difficulty and context reuse.','Benchmarks are vendor-reported. Reproduce them on your own acceptance set.','Run a 10-task before/after benchmark.'),
item('DevDay: cloud agents, code review, private intelligence','platform','2026-09-29','https://openai.com/index/devday-2026-recap/','OpenAI bundles cloud Codex, multi-agent CLI controls, automatic code review, and private-intelligence directions.','The toolchain is converging around remote execution plus review surfaces.','Map Buildn artifacts to isolated workspaces, human review, and immutable links.','Remote execution is becoming the default place to scale throughput.','Validate each capability in the actual plan and region.','Convert one existing cron flow first.'),
item('GPT-6.1 Sol arrives inside GitHub Copilot','release','2026-09-29','https://github.blog/changelog/2026-09-29-gpt-6-1-sol-in-github-copilot','GitHub reports GPT-6.1 Sol rolling out across Copilot clients, coding agent, CLI, and IDEs, with admin model policy controls.','Model choice is now close to the repository and workflow where adoption happens.','Pilot it without rebuilding orchestration.','Client teams can compare a new model with low integration friction.','Usage-based billing and rollout timing matter.','Enable a cohort and pin a rollback model.')]),
'security-governance':('Agent security is becoming an operating plane','Security guidance and productized defenses now converge on inventory, identity, tool boundaries, runtime monitoring, and approved containment. Turn these into reusable controls.',['Inventory','Gateway','Runtime','Response'],[
item('Google Cloud’s partner security-agent layer','ecosystem','2026-09-29','https://cloud.google.com/blog/products/identity-security/google-cloud-partners-deliver-new-security-agents-and-ai-defenses-with-gemini-enterprise','Google Cloud brings partner security agents into Gemini Enterprise across identity, data, runtime, SOC, supply chain, and agent-gateway controls.','Security work is packaged as orchestrable action across existing systems.','Build discover → assess → propose → approve → contain → record-evidence adapters.','The value is shared context and control, not the chat entry point.','Availability and integration depth vary.','Start with read-only posture aggregation.'),
item('ISACA’s 11-category agent security baseline','white paper','2026-09-15','https://www.isaca.org/resources/white-papers/2026/cybersecurity-recommendations-for-securing-ai-agents','ISACA covers governance, prompt injection, tool misuse, excessive agency, memory leakage, unsafe ingestion, supply chain, drift, and assurance.','It gives clients a common vocabulary for threat-modeling the full workflow.','Turn categories into Buildn intake and release gates.','A concise baseline helps replace generic AI-safety talk with owned controls.','Guidance is not implementation. Map each item to a test or invariant.','Create five release gates and a regression suite.'),
item('Agent Gateway + Registry as the control seam','architecture','2026-09-29','https://cloud.google.com/blog/products/identity-security/google-cloud-partners-deliver-new-security-agents-and-ai-defenses-with-gemini-enterprise','Google highlights gateway and registry patterns for discovering workloads, monitoring posture, and applying defenses.','A central seam can enforce identity, routing, policy, and telemetry.','Represent integrations as registered capabilities with scopes, owners, health, and evidence contracts.','Central seams reduce per-agent drift as portfolios grow.','Do not let a gateway replace local sandboxing.','Prototype a read-only registry view.'),
item('Security posture becomes an integration surface','market signal','2026-09-29','https://cloud.google.com/blog/products/identity-security/google-cloud-partners-deliver-new-security-agents-and-ai-defenses-with-gemini-enterprise','The partner set spans deception, identity termination, DLP, SAST triage, runtime defense, and SOC orchestration.','Clients will expect agent security to connect to existing controls.','Package a readiness sprint around inventory, permissions, tests, and reversible response.','The market is moving from generic safety to controls with owners and SLAs.','Vendor claims need proof-of-value evidence.','Require logs, approval events, and failure-mode tests.')]),
'knowledge-and-edge':('The overlooked leverage is durable context and migration hygiene','The practical thread beneath frontier agents is portable context, deprecation discipline, knowledge foundations, and safer physical interfaces. Optimize for reversible migrations.',['Context','Contracts','Simulation','Consent'],[
item('Gemini API change windows make migration visible','docs','2026-09-23','https://ai.google.dev/gemini-api/docs/changelog','Google’s notes show model and agent changes, including a preview replacement and an October 5 shutdown date for the older preview.','Agent systems need ordinary dependency hygiene: pins, contract tests, and deprecation calendars.','Add provider-change monitoring to every integration.','Migration is operational, not merely model selection.','Verify against the current deprecations page.','Add a deprecation record and contract test.'),
item('Knowledge management is an AI readiness constraint','research','2026-01-07','https://www.apqc.org/resource-library/resource-listing/2026-knowledge-management-priorities-and-trends-survey-report','APQC reports AI as the top KM priority while 59% of organizations remain in the two earliest maturity stages.','Agent quality is bounded by freshness, ownership, and reuse of knowledge.','Sell a knowledge map and maintenance loop before promising an enterprise agent.','This counters “just connect the docs” projects.','Survey data is self-reported; measure retrieval on real tasks.','Map one client domain’s owners and freshness.'),
item('Physical AI needs digital-twin-first workflows','physical ai','2026-09-03','https://www.fanucamerica.com/press-releases/fanuc-america-brings-robotics-automation-physical-ai-and-cnc-innovation-to-imts-2026','FANUC showcases natural-language robot programming, sensor-linked reasoning, digital twins, and virtual commissioning.','Simulation reduces the cost of experimenting with real-world agents.','Use plan → simulate → verify → deploy for high-cost automation.','Digital twins offer a safer test surface for embodied workflows.','This is a demonstration, not proof of general autonomy.','Keep operator approval and hard interlocks.'),
item('Voice becomes an API primitive','release','2026-09-22','https://ai.google.dev/gemini-api/docs/changelog','Google’s notes describe GA TTS models and a Voices endpoint with voice design and consent verification.','Voice can remove friction from field intake when identity and audit are explicit.','Prototype voice intake that creates a structured task and asks for confirmation.','Use voice where typing is the bottleneck, not as novelty.','Voice replication and high-impact actions need consent policy.','Pilot with opt-in recordings.')])}
def page(slug,title,read,chain,items):
 cards=''.join(f'<article class="card"><h2>{html.escape(i["title"])}</h2><div class="badges"><span class="good">fresh signal</span> <span>{html.escape(i["typ"])}</span></div><ul class="facts"><li>{i["date"]}</li><li><a href="{i["url"]}">{html.escape(i["url"])}</a></li></ul><p><b>What:</b> {html.escape(i["what"])}</p><p><b>Why it matters:</b> {html.escape(i["why"])}</p><p><b>Buildn/client use:</b> {html.escape(i["use"])}</p><p><b>Why now:</b> {html.escape(i["now"])}</p><ul class="wins"><li>Scope the smallest useful loop</li><li>Keep outputs reviewable</li><li>Measure cost and failure</li></ul><div class="call"><b>Caveat / next move:</b> {html.escape(i["caveat"])} {html.escape(i["action"])}</div></article>' for i in items)
 src=''.join(f'<li><a href="{i["url"]}">{html.escape(i["title"])}</a></li>' for i in items)
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily Ingest — {html.escape(title)}</title>{css}</head><body><main><header><div class="word"><span class="mark"></span>Buildn</div><div class="tag">Daily Ingest Dossier · 2026-09-30</div><h1>{html.escape(title)}</h1><p class="read">{html.escape(read)}</p></header><section class="card"><h2>Signal map</h2><div class="diagram">{svg(chain)}</div></section><section><h2>Dossier</h2>{cards}</section><section class="card"><h2>Use-case matrix</h2><table class="matrix"><tr><th>Theme</th><th>Buildn OS</th><th>Client work</th><th>Agent workflows</th><th>Personal leverage</th></tr><tr><td>Foundation</td><td>Register capabilities</td><td>Readiness sprint</td><td>Context packets</td><td>Maintain source of truth</td></tr><tr><td>Control</td><td>Audit and rollback</td><td>Approval gates</td><td>Tool scopes</td><td>Review before act</td></tr><tr><td>Experiment</td><td>Telemetry</td><td>Small pilot</td><td>Contract tests</td><td>Compare outcomes</td></tr></table></section><section class="card top"><h2>Top actions</h2><ol><li>Run one bounded pilot, not a platform rewrite.</li><li>Record cost, retries, approvals, and evidence.</li><li>Pin versions and keep a reversible fallback.</li></ol></section><section class="card"><h2>Source trail</h2><ol class="sources">{src}</ol></section><footer>Static HTML · zero scripts</footer></main></body></html>'''
for slug,(title,read,chain,items) in lanes.items(): (O/(slug+'.html')).write_text(page(slug,title,read,chain,items),encoding='utf-8')
ledger={'date':'2026-09-30','generated_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'editorial_thesis':'Persistent agents are moving into operating workflows, while security controls and context portability decide whether they can be trusted.','topic_groups':[{'slug':s,'title':v[0],'selection_rationale':'Fresh practical signal and a coverage gap; avoids yesterday’s runtime-control, privacy, and architecture lanes.','sources':[{'title':i['title'],'url':i['url'],'source_type':i['typ'],'published_or_updated':i['date'],'why_selected':i['why'],'usefulness':i['use']} for i in v[3]]} for s,v in lanes.items()]}
(O/'ledger.json').write_text(json.dumps(ledger,indent=2),encoding='utf-8')
index=f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily Ingest — 2026-09-30</title>{css}</head><body><main><header><div class="word"><span class="mark"></span>Buildn</div><div class="tag">Adaptive Daily Ingest · 2026-09-30</div><h1>From always-on agents to governed context</h1><p class="read">Agent capability is arriving as an operating layer, but durable leverage depends on three seams: cost-aware execution, security control planes, and portable knowledge/context.</p></header><section class="card"><h2>Selected lanes</h2><div class="grid">{''.join(f'<div class="node"><b>{html.escape(v[0])}</b><p>{html.escape(v[1][:160])}…</p><a href="{s}.html">Open lane →</a></div>' for s,v in lanes.items())}</div></section><section class="card top"><h2>Top three today</h2><ol><li>Benchmark GPT-6.1 Sol on real long-horizon tasks.</li><li>Build an agent inventory and convert the security baseline into release gates.</li><li>Add deprecation monitoring and contract tests before expanding interfaces.</li></ol></section><section class="card"><h2>Editorial note</h2><p>Coverage rotates away from yesterday’s runtime-control, privacy-by-construction, and agent-architecture lanes toward adoption surfaces and the operational seams needed to make them safe and portable.</p></section><footer><a href="ledger.json">Source ledger</a> · Static HTML · zero scripts</footer></main></body></html>'''
(O/'index.html').write_text(index,encoding='utf-8')
# durable ledgers
cov=json.loads((R/'topic-coverage.json').read_text()); cov['updated_at']=datetime.datetime.now(datetime.timezone.utc).isoformat(); cov.setdefault('runs',[]).append({'date':'2026-09-30','selected_lanes':list(lanes),'items':[{'title':i['title'],'url':i['url'],'source_type':i['typ']} for v in lanes.values() for i in v[3]],'selection_rationale':'Followed fresh product/security signals and rotated toward migration, knowledge, and physical-interface gaps.'})
for s,v in lanes.items(): z=cov.setdefault('rolling_theme_summary',{}).setdefault(s,{'title':v[0],'times_covered':0}); z.update(title=v[0],times_covered=z.get('times_covered',0)+1,last_covered='2026-09-30')
(R/'topic-coverage.json').write_text(json.dumps(cov,indent=2),encoding='utf-8')
seen=json.loads((R/'seen-sources.json').read_text()); seen['updated_at']=datetime.datetime.now(datetime.timezone.utc).isoformat()
for v in lanes.values():
 for i in v[3]: seen.setdefault('sources',{})[i['url']]={'first_seen':'2026-09-30','last_seen':'2026-09-30','title':i['title']}
(R/'seen-sources.json').write_text(json.dumps(seen,indent=2),encoding='utf-8')
print(O)
