import json, os, re
from datetime import datetime, timezone
ROOT='/root/Projects/daily-ingest-pages'; DATE='2026-09-29'; TS='2026-09-29T08:00:30Z'
OUT=os.path.join(ROOT,DATE); os.makedirs(OUT,exist_ok=True)
logo='<svg viewBox="0 0 164 195" width="22" aria-hidden="true"><path d="M117 194.5H0L12 73C17 67 21 65 29 64L35 0H152c7 4 9 7 12 13l-11 106c-4 8-8 10-17 11l-5 55c-3 5-6 8-14 9Z" fill="#01dc82"/><path d="m64 33-3 32h33l-3 32h32l5-51c-2-9-6-11-15-13H64Z" fill="#033330"/><path d="m37 148 5-50h33l-3 32 32 1-4 31H50c-8-3-10-7-13-14Z" fill="#033330"/></svg>'
CSS='''<style>:root{--brand:#01dc82;--deep:#033330;--lime:#cfe66a;--red:#b3261e;--amber:#9a6700;--ink:#0f172a;--muted:#475569;--line:#e2e8f0;--bg:#fafaf9;--card:#fff;--serif:Newsreader,Georgia,serif;--sans:"Plus Jakarta Sans",system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.55 var(--sans)}main{max-width:68rem;margin:auto;padding:3rem 1.5rem}header{display:flex;flex-direction:column;gap:1rem;margin-bottom:2.3rem}.wordmark{display:flex;align-items:center;gap:.6rem;font-weight:700;color:var(--deep)}h1,h2{font-family:var(--serif);color:var(--deep);font-weight:600}h1{font-size:2.2rem;margin:0}h2{font-size:1.35rem;margin:0 0 .5rem}h3{font-size:1rem;color:var(--deep);margin:1rem 0 .35rem}a{color:#087b52;text-decoration-thickness:1px}.lede{max-width:54rem;font-size:1.05rem;color:var(--muted)}.date{color:var(--muted);font-size:.8rem;letter-spacing:.06em;text-transform:uppercase}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:1.25rem}.card{background:var(--card);border:1px solid var(--line);border-radius:.75rem;padding:1.35rem}.badges{display:flex;flex-wrap:wrap;gap:.45rem;margin:.35rem 0 .8rem}.badge{font-size:.68rem;text-transform:uppercase;letter-spacing:.06em;font-weight:700;padding:.15rem .5rem;border-radius:.35rem;background:#f1f5f9;color:var(--muted)}.good{background:#dcfce7;color:#166534}.warn{background:#fef3c7;color:var(--amber)}.spec{background:#e2e8f0;color:#334155}.facts{font: .78rem ui-monospace,monospace;color:var(--muted);margin:.5rem 0;padding:0;list-style:none}.facts li{padding:.1rem 0}.diagram{border:1px solid var(--line);border-radius:.5rem;background:#fff;padding:.8rem;margin:1rem 0}.diagram svg{width:100%;height:auto;display:block}.label{font:600 10px system-ui;letter-spacing:.06em;fill:var(--muted)}.small{font-size:.87rem;color:var(--muted)}.wins{margin:.4rem 0;padding-left:1.1rem}.wins li{margin:.15rem 0}.callout{border-left:3px solid var(--amber);background:#fffbeb;color:#713f12;padding:.55rem .8rem;border-radius:.25rem;font-size:.87rem;margin-top:.8rem}.matrix{width:100%;border-collapse:collapse;font-size:.83rem}.matrix th,.matrix td{border-bottom:1px solid var(--line);padding:.55rem;text-align:left;vertical-align:top}.matrix th{color:var(--deep);font-weight:700}.top{border-top:4px solid var(--brand)}.source-list{columns:2;column-gap:2rem}.source-list li{break-inside:avoid;margin:.35rem 0}.section{margin-top:2rem}.signal{display:grid;grid-template-columns:repeat(3,1fr);gap:.55rem}.signal div{border:1px solid var(--line);padding:.8rem;border-radius:.5rem;background:#fff}.signal strong{display:block;color:var(--deep)}@media(max-width:600px){main{padding:2rem 1rem}.source-list{columns:1}.signal{grid-template-columns:1fr}h1{font-size:1.8rem}}</style>'''
def svg(kind):
 if kind=='runtime': return '<svg viewBox="0 0 620 125" role="img" aria-label="Agent request flows through policy and sandbox layers"><defs><marker id="ar" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 6 3 0 6Z" fill="#94a3b8"/></marker></defs><rect x="10" y="42" width="125" height="40" rx="6" fill="#fff" stroke="#cbd5e1"/><text x="72" y="66" text-anchor="middle" class="label">AGENT REQUEST</text><line x1="135" y1="62" x2="215" y2="62" stroke="#94a3b8" marker-end="url(#ar)"/><rect x="215" y="30" width="145" height="64" rx="6" fill="#f0fdf4" stroke="#01dc82" stroke-width="2"/><text x="287" y="58" text-anchor="middle" class="label">POLICY GATE</text><text x="287" y="76" text-anchor="middle" class="label">allow / deny / log</text><line x1="360" y1="62" x2="440" y2="62" stroke="#94a3b8" marker-end="url(#ar)"/><rect x="440" y="30" width="160" height="64" rx="6" fill="#fff" stroke="#cbd5e1"/><text x="520" y="58" text-anchor="middle" class="label">EPHEMERAL</text><text x="520" y="76" text-anchor="middle" class="label">SANDBOX</text></svg>'
 if kind=='privacy': return '<svg viewBox="0 0 620 125" role="img" aria-label="Private data is taint tracked before tool disclosure"><defs><marker id="ap" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 6 3 0 6Z" fill="#94a3b8"/></marker></defs><rect x="10" y="35" width="135" height="55" rx="6" fill="#fff" stroke="#cbd5e1"/><text x="77" y="58" text-anchor="middle" class="label">PRIVATE DATA</text><text x="77" y="75" text-anchor="middle" class="label">+ PERMISSIONS</text><line x1="145" y1="62" x2="225" y2="62" stroke="#94a3b8" marker-end="url(#ap)"/><rect x="225" y="25" width="165" height="75" rx="6" fill="#f0fdf4" stroke="#01dc82" stroke-width="2"/><text x="307" y="57" text-anchor="middle" class="label">TAINT + PLAN</text><text x="307" y="75" text-anchor="middle" class="label">IFC CHECK</text><line x1="390" y1="62" x2="470" y2="62" stroke="#94a3b8" marker-end="url(#ap)"/><rect x="470" y="35" width="140" height="55" rx="6" fill="#fff" stroke="#b3261e"/><text x="540" y="58" text-anchor="middle" class="label">TOOL CALL</text><text x="540" y="75" text-anchor="middle" class="label">ALLOW / BLOCK</text></svg>'
 return '<svg viewBox="0 0 620 125" role="img" aria-label="Task shape determines agent architecture"><rect x="20" y="28" width="165" height="68" rx="6" fill="#fff" stroke="#cbd5e1"/><text x="102" y="56" text-anchor="middle" class="label">TASK SHAPE</text><text x="102" y="76" text-anchor="middle" class="label">parallel or sequential?</text><path d="M185 62h70" stroke="#94a3b8"/><path d="m250 62-8-5v10Z" fill="#94a3b8"/><rect x="270" y="15" width="150" height="42" rx="6" fill="#f0fdf4" stroke="#01dc82"/><text x="345" y="41" text-anchor="middle" class="label">PARALLEL → FAN OUT</text><rect x="270" y="68" width="150" height="42" rx="6" fill="#fff" stroke="#b3261e"/><text x="345" y="94" text-anchor="middle" class="label">SEQUENTIAL → ONE LOOP</text><path d="M420 36h70M420 89h70" stroke="#94a3b8"/><text x="555" y="41" text-anchor="middle" class="label">GAIN</text><text x="555" y="94" text-anchor="middle" class="label">DRIFT</text></svg>'
def card(item):
 b=item['badge']; return f'''<article class="card" id="{item['id']}"><h2>{item['title']}</h2><div class="badges"><span class="badge {b[0]}">{b[1]}</span><span class="badge spec">{item['tag']}</span></div><ul class="facts"><li>Source: <a href="{item['url']}">{item['source']}</a></li><li>Signal: {item['signal']}</li></ul><h3>What it is</h3><div>{item['what']}</div><h3>Why it matters</h3><div>{item['why']}</div><h3>Buildn / client use</h3><div>{item['use']}</div><ul class="wins">{''.join('<li>'+x+'</li>' for x in item['wins'])}</ul><div class="callout"><strong>Caveat / next move:</strong> {item['next']}</div></article>'''
def report(lane, thesis, kind, items, matrix, actions):
 sources=''.join(f'<li><a href="{x["url"]}">{x["title"]}</a> <span class="small">— {x.get("typ")}</span></li>' for x in items)
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily Ingest — {lane}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Newsreader:wght@400;500;600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">{CSS}</head><body><main><header><div class="wordmark">{logo}<span>Buildn</span></div><div class="date">Daily Ingest Dossier · {DATE}</div><h1>{lane}</h1><div class="lede">{thesis}</div></header><section class="card"><h2>Signal map</h2><div class="signal"><div><strong>Observe</strong><span class="small">{items[0]['map']}</span></div><div><strong>Connect</strong><span class="small">{items[1]['map']}</span></div><div><strong>Try</strong><span class="small">{items[2]['map']}</span></div></div><div class="diagram">{svg(kind)}</div></section><section class="section"><div class="grid">{''.join(card(x) for x in items)}</div></section><section class="section card"><h2>Use-case matrix</h2><table class="matrix"><tr><th>Theme</th><th>Buildn OS</th><th>Client work</th><th>Agent workflows</th><th>Personal leverage</th></tr>{''.join('<tr>'+''.join('<td>'+c+'</td>' for c in row)+'</tr>' for row in matrix)}</table></section><section class="section card top"><h2>Top actions</h2><ol class="wins">{''.join('<li>'+a+'</li>' for a in actions)}</ol></section><section class="section card"><h2>Source trail</h2><ol class="source-list">{sources}</ol></section></main></body></html>'''

def I(id,title,url,source,typ,signal,what,why,use,wins,next,map,badge=('good','fresh'),tag='practical'):
 return locals()
items_runtime=[
 I('openshell','NVIDIA OpenShell: policy outside the agent','https://developer.nvidia.com/blog/add-runtime-controls-to-ai-agents-with-nvidia-openshell/','NVIDIA OpenShell runtime controls','official technical blog','Published Sep 28; OpenShell 0.1.0','An open-source runtime wrapping Codex, Claude Code, Pi, or Hermes with kernel, network, credential, MCP, and audit controls.','It makes permissions enforceable even when the model generates shell commands, child processes, or delegated work.','Compare the supervisor/sandbox split with Hermes execution boundaries and build a policy-backed worker profile.',['Controls survive bad prompts','Credentials stay out of workloads','OCSF decisions become evidence'],'Treat 0.1.0 as an evaluation target, not a drop-in production control plane. Run one read-only sandbox test.','Runtime guardrails'),
I('dynamic-workers','Cloudflare Dynamic Worker Loader: millisecond sandboxes','https://blog.cloudflare.com/dynamic-workers/','Dynamic Worker Loader','official platform blog','Fresh runtime primitive for code-mode agents','A Worker can load generated JavaScript into a disposable V8 isolate with selected bindings and blocked or intercepted outbound traffic.','The execution economics make per-request code sandboxes plausible where containers are too slow or heavy.','Prototype a tiny code-mode verifier that exposes only typed RPC capabilities, never raw credentials.',['Few-millisecond startup','Capability injection is explicit','Disposable by default'],'Open beta and JavaScript-specific; validate isolation and observability before client promises.','Disposable code'),
I('hermes-release','Hermes Agent v0.21.5: deployment surface expands','https://github.com/NousResearch/hermes-agent/releases','Hermes Agent v0.21.5','GitHub release','Sep 24 patch roll-up; 460 merged PRs','The latest tagged Hermes release rolls up desktop plugin SDK work, connectors, profile lifecycle controls, JSONL/CLI improvements, and model catalog changes.','The practical signal is not one feature: downstream deployments get a more complete operator surface for profiles, plugins, and hosted images.','Use the release compare as a change-control input for this cron environment and test profile restart plus structured output.',['Versioned hosted image','Operator controls mature','JSONL supports automation'],'Large roll-up notes are incomplete; pin and smoke-test before upgrading.','Release hygiene'),
I('webmcp','WebMCP preview: websites expose agent-callable actions','https://blog.cloudflare.com/tag/agents-week/','Cloudflare Agents Week / WebMCP','official product index','Web surfaces are becoming callable, not merely readable','Cloudflare’s Agents Week work frames WebMCP and agent-ready web surfaces as a way for sites to expose actions to agents.','If websites become structured capability surfaces, client UX and authorization need to be designed together.','Add an agent-readiness checklist to client web builds: discoverability, action schemas, consent, rate limits, and receipts.',['Moves beyond scraping','Capability schema is product UX','Consent becomes visible'],'The index is a discovery page, not one stable API contract; follow the specific WebMCP preview before implementation.','Agentic web'),
I('control-plane','Cloudflare AI control-plane direction','https://blog.cloudflare.com/workers-ai-gateway-unification/','Workers AI + AI Gateway unification','official platform blog','One control surface for routing, billing, and observability','Cloudflare describes a unified AI control plane with routing across managed GPUs and external providers plus consolidated telemetry.','Operational visibility is becoming part of model choice; portability without spend and latency data is only theoretical.','Borrow the pattern for Buildn: one model gateway, per-task budgets, route logs, and provider fallback.',['Routing becomes inspectable','Billing joins traces','Provider choice stays replaceable'],'This announcement is from Agents Week; treat it as architecture signal and verify current product availability.','Model operations')
]
items_priv=[
 I('gaap','GAAP: deterministic privacy for tool-using agents','https://arxiv.org/html/2604.19657v3','GAAP paper','paper + code','v3 dated Sep 24; code is available','An execution environment combines structured plans, information-flow control, taint tracking, permissions, and persistent disclosure logs.','It moves confidentiality decisions outside the model and reports 100% blocking on tested disclosure attacks with about 10% utility loss.','Use the paper as a design benchmark for sensitive Buildn workflows: data item × recipient policies, tool interception, and durable disclosure receipts.',['Guards survive malicious models','Permissions persist across tasks','Testable confidentiality claim'],'It protects confidentiality, not correctness or metadata; inspect the implementation before copying the guarantee.','Privacy ledger',('good','research-backed'),'security'),
I('gaap-code','GAAP reference implementation','https://github.com/rssta/gaap','rssta/gaap','GitHub repository','Rare paper-to-code bridge','The accompanying repository provides a concrete starting point for the structured execution and policy machinery described in GAAP.','Executable artifacts make the privacy model inspectable rather than purely conceptual.','Run a narrow local experiment with synthetic secrets and MCP-like tools; compare policy friction against prompt-only approval.',['Synthetic test first','Policy semantics are inspectable','Good candidate for replay tests'],'Research code may be incomplete or brittle; isolate it and avoid real credentials.','Inspect code',('warn','try locally'),'implementation'),
I('trust-framework','Trustworthy Agentic AI lifecycle framework','https://arxiv.org/html/2609.22712v1','Trustworthy Agentic AI','research survey','Fresh September synthesis of failure modes and mitigations','A lifecycle view organizes agent failures across design, deployment, monitoring, and governance rather than treating safety as a prompt prefix.','It is useful as a client review checklist when the system spans model, tools, memory, identity, and human approval.','Turn the lifecycle headings into a one-page architecture review gate for client proposals.',['Covers whole lifecycle','Maps failure to control','Good review vocabulary'],'Survey-level guidance needs system-specific tests; use it to frame questions, not as evidence of efficacy.','Review checklist',('warn','framework'),'governance'),
I('eu-ai-act','EU AI Act: post-August applicability baseline','https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai','European Commission AI Act framework','official policy page','Current applicability baseline: Aug 2, 2026','The Commission notes that the AI Act is applicable from August 2, 2026 with exceptions, including prohibited practices and AI literacy obligations.','Clients shipping agentic workflows need a dated inventory of use cases, roles, controls, and evidence rather than a generic “AI policy.”','Add regulatory scope, operator training, logging, and human-oversight questions to discovery and delivery checklists.',['Date the compliance baseline','Separate risk classes','Operationalize literacy'],'Rules and guidance evolve; obtain client legal review for high-impact deployments.','Governance baseline',('good','current baseline'),'policy'),
I('privacy-design','Private context is a permissioned capability','https://arxiv.org/html/2602.05016v1','Exploring the design space of AI agents for human-as-the-unit','research paper','Human-centered privacy decisions remain a product surface','The paper studies privacy management tools that help people navigate complex decisions with AI and personal context.','Permission UX is where security, trust, and usefulness meet; an invisible policy engine will be hard to operate.','Design consent receipts and “why this data?” explanations into Buildn workflows that touch client material.',['Make policy legible','Separate read from disclose','Keep users in control'],'The research is exploratory; validate with real operators before expanding permission prompts.','Consent UX',('spec','design lead'),'product')
]
items_arch=[
 I('scaling-science','Agent count is a task-shape decision','https://research.google/blog/towards-a-science-of-scaling-agent-systems-when-and-why-agent-systems-work/','Google Research: Science of Scaling Agent Systems','research finding','Material synthesis: architecture beats “more agents”','A study of 180 configurations finds centralized systems help parallelizable work, while independent agents can amplify errors on sequential tasks.','It gives a falsifiable reason to avoid multi-agent theater: choose topology from decomposability and tool complexity.','Add task-shape classification before spawning workers in Buildn or client automations.',['Parallelize independent evidence','Keep sequential loops coherent','Measure error amplification'],'The source is not new today; it earns a revisit because it is the decision rule behind today’s runtime experiments.','Task shape',('good','revisit: applied'),'architecture'),
I('dynamic-workflows','Dynamic workflows as reusable infrastructure','https://claude.com/blog/a-harness-for-every-task-dynamic-workflows-in-claude-code','Claude Code dynamic workflow field notes','product guide','Reframed as a reusable harness pattern','Saved workflows can fan out, critique, filter, and verify work rather than relying on one long prompt.','The useful unit is a bounded workflow artifact with an entry condition, budget, and verifier.','Create three Buildn templates: research fan-out, implementation loop, and release verification.',['Workflows become shareable','Budgets become explicit','Verifiers close loops'],'Avoid copying vendor-specific commands; preserve the control pattern, not the syntax.','Harness library',('warn','pattern'),'workflow'),
I('agent-dojo','Agent privacy evaluation as a test harness','https://github.com/ethz-spylab/agentdojo','AgentDojo benchmark','open-source benchmark','Concrete adversarial tasks for tool-using agents','AgentDojo supplies environments and attacks for evaluating prompt injection and tool-use safety.','A repeatable attack suite is more useful than a one-time red-team demo when workflows and models change.','Adapt two synthetic tasks into a regression suite for tool permissions and prompt-injection resilience.',['Replayable attacks','Tool-aware evaluation','Useful CI gate'],'Benchmark assumptions may not match your tools; fork only the smallest task set and document adaptations.','Adversarial tests',('good','OSS benchmark'),'evaluation'),
I('mcp-v2','MCP v2 direction: stateless, deployable tool surfaces','https://blog.cloudflare.com/mcp-v2/','Cloudflare: The next generation of MCP','official technical blog','Protocol evolution matters at the integration boundary','Cloudflare describes a stateless MCP core designed for Workers, with protocol upgrades and an SDK migration path.','Statelessness and deployability reduce the friction of making tools portable across agent runtimes.','Review Buildn MCP tools for explicit auth, idempotency, and request-scoped state before adding more connectors.',['Less hidden session state','Portable deployment target','Clearer migration boundary'],'Protocol previews can shift; pin versions and test interoperability with two clients.','Tool boundary',('warn','protocol watch'),'infrastructure'),
I('chopin','Chopin: planning before delegated execution','https://githubnext.com/projects/chopin/','GitHub Next Chopin','research prototype','Planning surface remains under-covered','Chopin combines human presence, shared plans, chat, and MCP in a multiplayer agentic planning environment.','It reinforces a useful separation: decide and record the plan before workers mutate repositories or external systems.','Prototype a static Buildn plan card that captures intent, constraints, owners, and approval before execution.',['Plans become artifacts','Presence supports steering','Decisions stay reviewable'],'Prototype, not production software; borrow the interaction model only.','Planning surface',('spec','prototype'),'collaboration')
]
common_matrix=[['Bounded execution','Policy profiles + audit trail','Safer client automations','Capability-scoped workers','Safer personal experiments'],['Evidence','Receipts + replayable traces','Explainable delivery','Regression gates','Less guesswork']]
for slug,lane,thesis,kind,items,matrix,actions in [
 ('agent-runtime-controls','Agent Runtime Controls + Callable Surfaces','The fresh signal is moving below the prompt: enforceable runtime policy, disposable code sandboxes, and agent-callable web surfaces are becoming infrastructure primitives.', 'runtime',items_runtime,common_matrix,['Read OpenShell architecture and compare it with Hermes profiles.','Run a synthetic Dynamic Worker or local sandbox experiment with no network.','Add a model-control-plane sketch to the next Buildn architecture review.']),
 ('privacy-by-construction','Privacy-by-Construction for Personal Agents','The strongest practical privacy signal is architectural: track data, permissions, and disclosure at the tool boundary instead of asking a model to behave itself.', 'privacy',items_priv,common_matrix,['Clone the GAAP reference and reproduce one synthetic disclosure block.','Draft a data-item × recipient permission table for one sensitive workflow.','Add consent receipts and disclosure logs to the client discovery checklist.']),
 ('agent-architecture','Agent Architecture: Shape, Harness, Evaluate','Today’s useful architecture lesson is selective orchestration: classify the task, choose the smallest topology, then evaluate the boundary with repeatable tests.', 'arch',items_arch,common_matrix,['Classify one current workflow as parallel or sequential.','Build one bounded fan-out template with a verifier and budget.','Turn two AgentDojo-style attacks into a regression test.'])]:
 html=report(lane,thesis,kind,items,matrix,actions); open(os.path.join(OUT,slug+'.html'),'w').write(html)
# overview
reports=[('agent-runtime-controls','Agent Runtime Controls + Callable Surfaces'),('privacy-by-construction','Privacy-by-Construction for Personal Agents'),('agent-architecture','Agent Architecture: Shape, Harness, Evaluate')]
links=''.join(f'<article class="card"><h2><a href="{slug}.html">{title}</a></h2><p>{desc}</p><div class="badges"><span class="badge good">selected</span><span class="badge spec">{reason}</span></div></article>' for (slug,title),(desc,reason) in zip(reports,[('Policy is moving outside the model into runtime gates, sandboxes, and callable web capability surfaces.','fresh infrastructure signal'),('Privacy guarantees are being implemented with taint, policy, and disclosure logs.','coverage gap: privacy-by-construction'),('Task shape should decide orchestration; reusable harnesses and attack tests make that choice operational.','applied architecture revisit')]))
over=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily Ingest Dossier — {DATE}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Newsreader:wght@400;500;600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">{CSS}</head><body><main><header><div class="wordmark">{logo}<span>Buildn</span></div><div class="date">Adaptive Daily Ingest · {DATE}</div><h1>Daily Ingest Dossier</h1><div class="lede">Today’s thesis: the practical advantage is shifting from clever prompting to controlled execution. Fresh runtime primitives, privacy-by-construction research, and task-shaped orchestration make agents more deployable—and more reviewable.</div></header><section class="card"><h2>Editorial readout</h2><p>Selection favors primary or directly inspectable sources that can be tried, integrated, or turned into client leverage. Yesterday’s cyber-defense, physical-AI, and dynamic-workflow lanes are not repeated; today’s workflow material is used only where it supplies a new architecture decision or testable implementation boundary.</p><div class="diagram">{svg('runtime')}</div></section><section class="section"><div class="grid">{links}</div></section><section class="section card top"><h2>Top 3 today</h2><ol class="wins"><li><strong>OpenShell:</strong> compare external runtime policy with current Hermes worker boundaries.</li><li><strong>GAAP:</strong> test data-item permissions and disclosure receipts on synthetic secrets.</li><li><strong>Task-shape rule:</strong> classify one workflow before adding more agents.</li></ol></section><section class="section card"><h2>Source trail</h2><p class="small">Full direct source trails live in each lane dossier.</p><ul class="source-list">{''.join(f'<li><a href="{x["url"]}">{x["title"]}</a></li>' for xs in [items_runtime,items_priv,items_arch] for x in xs)}</ul></section></main></body></html>'''
open(os.path.join(OUT,'index.html'),'w').write(over)
# ledger
ledger={'date':DATE,'generated_at':TS,'editorial_thesis':'The practical advantage is shifting from clever prompting to controlled execution: runtime policy, privacy-by-construction, and task-shaped orchestration make agents more deployable and reviewable.','topic_groups':[]}
for slug,title,thesis,kind,items,_,_ in [('agent-runtime-controls','Agent Runtime Controls + Callable Surfaces','', '',items_runtime,None,None),('privacy-by-construction','Privacy-by-Construction for Personal Agents','', '',items_priv,None,None),('agent-architecture','Agent Architecture: Shape, Harness, Evaluate','', '',items_arch,None,None)]:
 ledger['topic_groups'].append({'slug':slug,'title':title,'selection_rationale':thesis or 'Selected for freshness, practical relevance, and coverage gap.', 'sources':[{'title':x['title'],'url':x['url'],'source_type':x.get("typ"),'published_or_updated':'2026-09','why_selected':x['signal'],'usefulness':x['use']} for x in items]})
open(os.path.join(OUT,'ledger.json'),'w').write(json.dumps(ledger,indent=2))
# update coverage and sources
cp=os.path.join(ROOT,'topic-coverage.json'); cov=json.load(open(cp)); cov['updated_at']=TS; cov['last_run']={'date':DATE,'selected_lanes':[x[0] for x in reports]}; cov['last_successful_run']=DATE; cov['last_editorial_thesis']=ledger['editorial_thesis']
for slug,title in reports:
 s=cov.setdefault('rolling_theme_summary',{}).setdefault(slug,{'title':title,'times_covered':0,'last_covered':None}); s['times_covered']+=1; s['last_covered']=DATE
for x in items_runtime+items_priv+items_arch:
 rec={'date':DATE,'topic':x['id'],'title':x['title'],'url':x['url'],'source_type':x.get("typ"),'rationale':x['why']}
 cov.setdefault('item_history',[]).append(rec)
 cov.setdefault('sources',{})[x['url']]={'first_seen':DATE,'last_seen':DATE,'title':x['title']}
cov['item_history']=cov['item_history'][-450:]
open(cp,'w').write(json.dumps(cov,indent=2))
# seen sources
sp=os.path.join(ROOT,'seen-sources.json'); seen=json.load(open(sp)); seen['updated_at']=TS
for x in items_runtime+items_priv+items_arch: seen.setdefault('sources',{})[x['url']]={'first_seen':DATE,'last_seen':DATE,'title':x['title']}
open(sp,'w').write(json.dumps(seen,indent=2))
print('generated', OUT)
