from pathlib import Path
from datetime import datetime, timezone
import json, html, shutil

ROOT = Path('/root/Projects/daily-ingest-pages')
ART = Path('/root/Projects/artifact-library/artifacts/daily-ingest')
DATE = '2026-10-01'
STAMP = datetime.now(timezone.utc).isoformat()

lanes = [
 {
  'slug':'frontier-models', 'title':'Frontier models become long-horizon work engines',
  'rationale':'A material model update earns inclusion because it changes the practical envelope for coding, document work, and cyber workflows; it is distinct from yesterday’s lower-cost model economics.',
  'readout':'Gemini 4 Argon is positioned less as a chat upgrade than as a durable execution substrate: one-million-token context, multimodal professional work, and explicit cyber-defense use. The useful question is not whether the benchmark is high; it is which bounded workflows become economical enough to instrument and review.',
  'sources':[
   ('Gemini 4 Argon','https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-4-argon/','blog','2026-09-30','One-million-token context and long-horizon coding/document/cyber positioning.','Benchmark a long-lived Buildn task with cached context, review gates, and cost telemetry.'),
   ('Gemini 3.8 Flash and Flash Cyber','https://blog.google/innovation-and-ai/models-and-research/gemini-models/3-8-flash-and-3-8-flash-cyber/','release','unknown','A lighter model family signals a portfolio approach for agentic workflows and cyber work.','Use a cheap routing tier for extraction, triage, and evidence preparation.'),
   ('Gemini Computer Use model','https://blog.google/innovation-and-ai/models-and-research/google-deepmind/gemini-computer-use-model/','product','2025-03-25','Browser and mobile interaction remains a separate risk surface from reasoning.','Keep computer-use actions behind presence checks, screenshots, and reversible steps.'),
  ],
  'items':[
   ('Gemini 4 Argon','frontier / model','New long-context frontier model for software engineering, enterprise knowledge work, multimodal analysis, and cyber defense.','Long trajectories can keep requirements, evidence, and intermediate decisions in one working set.','Buildn: run a migration or dossier benchmark. Client: compare document-heavy workflows. Agents: route only high-value tasks. Personal: test a long research notebook.','Google-reported benchmarks and internal outcomes are vendor claims; access is staged.','Create a 3-task eval: repo change, source-backed report, incident triage.'),
   ('Gemini 3.8 Flash Cyber','portfolio / routing','A faster, cheaper model option aimed at agentic and defensive workflows.','Portfolio routing matters more than a single best model when tasks vary by latency and risk.','Buildn: classify tasks into fast/deep lanes. Client: price predictable automations. Agents: use Flash for evidence normalization. Personal: automate low-risk inbox or notes.','Verify API availability, limits, and safety behavior before promising savings.','Add quality/cost/latency columns to the next model trial.'),
   ('Computer Use API','interaction / browser','A model interface for operating browsers and mobile surfaces.','The action layer introduces confirmation, identity, and rollback requirements that pure text agents avoid.','Buildn: bounded browser chores. Client: test back-office flows in a sandbox. Agents: require proof of presence for impact. Personal: automate repetitive navigation.','UI drift, credentials, and unintended side effects remain the main failure modes.','Prototype one read-only flow before any write action.'),
  ],
 },
 {
  'slug':'public-sector-ai', 'title':'Public-sector AI enters an adoption window',
  'rationale':'October 1 is a concrete start date for a broad government offer, creating an unusually actionable procurement and enablement signal rather than another abstract policy story.',
  'readout':'OpenAI and GSA’s agreement turns public-sector AI from a pilot conversation into a multi-year adoption window: zero license fee, discounted usage, cyber-defense access, and enablement. The operational opportunity is implementation discipline—spend controls, data boundaries, training, and evidence—not indiscriminate rollout.',
  'sources':[
   ('OpenAI + GSA public-sector agreement','https://openai.com/index/expanding-ai-access-us-government/','product / policy','2026-09-10','The 27-month offer begins October 1 and includes broader eligibility, discounted usage, and Daybreak Blue.','Use the structure as a checklist for governed rollout: eligibility, spend, training, and data policy.'),
   ('Daybreak for Frontline Defenders','https://openai.com/index/daybreak-for-frontline-defenders/','program','unknown','The offer is part of a larger cyber-defense support program.','Separate subsidized defensive use from general-purpose deployment in client proposals.'),
   ('OpenAI cyber access','https://openai.com/index/responding-next-frontier-critical-cyber-capabilities/','security','2026-08-07','Shows the surrounding trust and access model for advanced defensive capability.','Map verification and abuse controls before adopting high-impact cyber workflows.'),
  ],
  'items':[
   ('OneGov starts today','adoption / procurement','Federal, state, local, and tribal governments can access the new commercial terms from October 1, 2026.','A dated adoption window creates a real trigger for readiness work.','Buildn: package a public-sector readiness sprint. Client: inventory use cases and data. Agents: keep procurement facts separate from execution. Personal: learn how public-service workflows differ.','Eligibility, contracting, and local policy still need verification.','Turn the announcement into a one-page intake and control checklist.'),
   ('Daybreak Blue','cyber / enablement','Discounted defensive access with training and enablement for verified government entities.','Security AI value depends on operator skill, workflows, and evidence—not model access alone.','Buildn: design a defend-and-document workflow. Client: connect to existing SOC controls. Agents: require analyst approval before containment. Personal: study defensive use cases, not offensive shortcuts.','Cyber claims and pricing are provider-specific; do not generalize to all sectors.','Model a safe vulnerability-triage flow with synthetic data.'),
   ('Spend and FinOps guidance','operations / governance','The offer explicitly includes usage estimates, spend controls, onboarding, and FinOps guidance.','Cost control is part of product design when access expands to millions of users.','Buildn: expose budgets and quotas. Client: define unit economics per workflow. Agents: stop on budget thresholds. Personal: track tool cost against time saved.','Discounts can hide demand spikes and support burden.','Add budget, owner, and escalation fields to every agent brief.'),
  ],
 },
 {
  'slug':'ai-services-market', 'title':'AI services are being productized around proof',
  'rationale':'The partner signal is older than today but materially useful as a market structure: production deployments, certified practitioners, and public references become visible proof points for services firms.',
  'readout':'Anthropic’s services track makes a familiar consultancy claim measurable. The differentiator is no longer “we can run a pilot”; it is a verified bench, deployed customers, and references. For a small studio, the implication is to build a narrow evidence ladder instead of chasing broad partner branding.',
  'sources':[
   ('Claude Partner Network Services Track','https://www.anthropic.com/news/services-track-partner-hub','announcement','2026-06-03','Anthropic publishes tier requirements around certified practitioners, production customers, and references.','Use the metrics as a design brief for a small, credible implementation practice.'),
   ('Claude partner program','https://claude.com/partners','directory','unknown','The partner surface connects customers to firms with stated implementation capability.','Study how proof is presented and what evidence a Buildn offer should expose.'),
   ('Claude certification','https://anthropic.skilljar.com/claude-certified-architect-foundations-access-request','training','unknown','Individual certification is part of the services-track measurement system.','Treat learning as an operating capability with recency and deployment evidence.'),
  ],
  'items':[
   ('Production proof ladder','services / trust','The program measures certified people, production customers, and public customer stories.','It gives buyers a legible proxy for delivery maturity.','Buildn: publish a compact case-study ladder. Client: request evidence, not logos. Agents: attach deployment artifacts. Personal: maintain a build journal.','Vendor-defined metrics may reward volume over fit or outcome quality.','Define three proof artifacts for one repeatable offer.'),
   ('Small-firm path','positioning / leverage','The same requirements apply to small and large firms; smaller firms climb by growing a certified bench and production record.','A narrow offer can compete on repeatability rather than headcount.','Buildn: choose one workflow class. Client: sell a bounded implementation. Agents: standardize intake and handoff. Personal: avoid broad tool sprawl.','Certification alone does not establish independent delivery quality.','Pick one vertical workflow and document its acceptance test.'),
   ('Public partner data','distribution / transparency','A daily-refreshed hub exposes tier, certified practitioners, deployments, and references.','Visible evidence changes how buyers compare providers.','Buildn: make capability pages evidence-first. Client: use partner directories as leads, not proof. Agents: query capability metadata before delegation. Personal: keep source links with claims.','Directory data can be incomplete or marketing-shaped.','Create a public “what we have shipped” page with dates and links.'),
  ],
 },
 {
  'slug':'developer-community', 'title':'Hands-on agent building gets a global distribution channel',
  'rationale':'DevFest opens today with 800+ local events, offering a practical learning and client-signal channel that has been under-covered in recent dossiers.',
  'readout':'DevFest 2026 is a distribution mechanism for practical agent literacy: codelabs, agent-athons, and local communities across 115 countries. The useful move is to treat events as field research—collect recurring implementation questions, then turn them into reusable Buildn patterns and client education.',
  'sources':[
   ('DevFest 2026','https://blog.google/innovation-and-ai/technology/developers-tools/devfest2026/','community','2026-09-14','The season runs October 1–December 31 with 800+ events in 115 countries.','Use the event directory to identify practical local signal and workshop topics.'),
   ('DevFest event directory','https://developers.google.com/community/devfest','directory','unknown','The directory is the actionable index for local events.','Find one event with a relevant agent, security, or Firebase track.'),
   ('Google Antigravity','https://developers.googleblog.com/build-with-google-antigravity-our-new-agentic-development-platform/','platform','unknown','DevFest names Antigravity among the hands-on technologies for the agentic era.','Compare its workflow assumptions with Hermes and Buildn patterns.'),
  ],
  'items':[
   ('Agent-athons','learning / build','Hands-on events focus on building agentic applications rather than passive talks.','Short build cycles reveal where tooling, safety, and deployment still hurt.','Buildn: mine workshop prompts for product ideas. Client: use a constrained workshop format. Agents: test one workflow end-to-end. Personal: ship a small artifact.','Event demos can optimize for novelty and omit operations.','Attend or follow one event; capture five repeated questions.'),
   ('Local developer groups','community / signal','More than 800 local events create a distributed view of what builders need.','Local context can reveal client language and overlooked workflows.','Buildn: create a feedback loop. Client: partner with a community. Agents: turn FAQs into retrieval sources. Personal: meet builders outside the usual feed.','Availability and agenda vary by location.','Search the directory for one nearby or virtual event.'),
   ('Build, secure, scale','operating model','The 2026 theme links making, security, and production infrastructure.','It is a useful curriculum spine for client enablement and internal docs.','Buildn: make three modules. Client: sell a staged rollout. Agents: pair every demo with a control. Personal: learn by building and reviewing.','Google’s ecosystem emphasis is not vendor-neutral.','Draft a 90-minute workshop with one build and one failure review.'),
  ],
 }
]

CSS='''<style>:root{--brand:#01dc82;--deep:#033330;--lime:#cfe66a;--red:#b3261e;--amber:#9a6700;--ink:#0f172a;--muted:#475569;--line:#e2e8f0;--bg:#fafaf9;--card:#fff;--serif:Newsreader,Georgia,serif;--sans:Plus Jakarta Sans,ui-sans-serif,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:var(--sans);line-height:1.5}main{max-width:68rem;margin:auto;padding:2.7rem 1.4rem}h1,h2{font-family:var(--serif);color:var(--deep);font-weight:600}h1{font-size:2.2rem;margin:.25rem 0 .5rem}h2{font-size:1.35rem;margin:0 0 .45rem}h3{font-size:1rem;color:var(--deep);margin:.5rem 0}.word{font-weight:700;color:var(--deep);display:flex;gap:.55rem;align-items:center}.mark{width:20px;height:24px;background:var(--brand);display:inline-block;clip-path:polygon(20% 0,100% 0,85% 58%,65% 58%,60% 100%,0 100%,10% 37%,18% 34%)}.eyebrow,.tag{font-size:.7rem;text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}header{margin-bottom:2rem}.read{font-size:1.03rem;max-width:880px}.card{background:var(--card);border:1px solid var(--line);border-radius:.75rem;padding:1.35rem;margin:1.25rem 0}.badges{display:flex;gap:.45rem;flex-wrap:wrap;margin:.35rem 0 .8rem}.badge{font-size:.68rem;text-transform:uppercase;letter-spacing:.06em;font-weight:600;padding:.18rem .5rem;border-radius:.35rem;background:#f1f5f9;color:var(--muted)}.good{background:#dcfce7;color:#166534}.warn{background:#fef3c7;color:var(--amber)}.facts{font:12px ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--muted);padding-left:1.1rem}.facts li{margin:.12rem 0}.facts a,a{color:#087f52}.diagram{border:1px solid var(--line);border-radius:.5rem;background:#fff;padding:.8rem;margin:1rem 0}.diagram svg{width:100%;height:auto;display:block}.label{font:12px ui-monospace,monospace;fill:var(--muted)}.wins{padding-left:1.15rem}.wins li{margin:.15rem 0}.callout{border-left:3px solid var(--amber);background:#fffbeb;color:#713f12;padding:.55rem .8rem;border-radius:.25rem;font-size:.88rem}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:.8rem}.node{border:1px solid var(--line);border-radius:.45rem;padding:.8rem}.matrix{border-collapse:collapse;width:100%;font-size:.83rem}.matrix th,.matrix td{text-align:left;vertical-align:top;border-bottom:1px solid var(--line);padding:.55rem}.matrix th{color:var(--deep);background:#f8fafc}.source{font-size:.82rem;margin:.35rem 0}footer{margin-top:2rem;font-size:.75rem;color:var(--muted)}@media(max-width:600px){main{padding:1.5rem .85rem}h1{font-size:1.8rem}}</style>'''

def mark(): return '<span class="mark" aria-hidden="true"></span>'
def diagram(title, count, lane):
    return f'''<div class="diagram"><svg viewBox="0 0 760 118" role="img" aria-label="Signal map for {html.escape(title)}"><defs><marker id="arr{count}" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#94a3b8"/></marker></defs><text x="10" y="18" class="label">SIGNAL MAP</text><rect x="10" y="38" width="160" height="45" rx="7" fill="#033330"/><text x="90" y="65" text-anchor="middle" fill="#fff" font-size="13">fresh trigger</text><line x1="170" y1="60" x2="285" y2="60" stroke="#94a3b8" marker-end="url(#arr{count})"/><rect x="285" y="38" width="190" height="45" rx="7" fill="#dcfce7" stroke="#01dc82"/><text x="380" y="65" text-anchor="middle" class="label">{count} sourced signals</text><line x1="475" y1="60" x2="590" y2="60" stroke="#b3261e" stroke-dasharray="4 4" marker-end="url(#arr{count})"/><rect x="590" y="38" width="160" height="45" rx="7" fill="#fff" stroke="#b3261e"/><text x="670" y="65" text-anchor="middle" class="label">try + verify</text></svg></div>'''

def page(title, lane=None):
    if lane:
      items=lane['items']; sources=lane['sources'];
      cards=''.join(f'''<article class="card" id="item-{i}"><h2>{html.escape(name)}</h2><div class="badges"><span class="badge good">{html.escape(tag)}</span><span class="badge">fresh signal</span></div><p><b>What:</b> {html.escape(what)}</p><p><b>Why it matters:</b> {html.escape(why)}</p><p><b>Buildn / client use:</b> {html.escape(use)}</p><div class="callout"><b>Caveat:</b> {html.escape(caveat)}</div><p><b>Follow-up:</b> {html.escape(action)}</p></article>''' for i,(name,tag,what,why,use,caveat,action) in enumerate(items,1))
      matrix=''.join(f'<tr><td>{html.escape(name)}</td><td>{html.escape("Bounded benchmark or offer design")}</td><td>{html.escape("Evidence, controls, and repeatability")}</td><td>{html.escape("Route, review, and log")}</td><td>{html.escape("One small experiment")}</td></tr>' for name,*_ in items)
      src=''.join(f'<li class="source"><a href="{url}">{html.escape(t)}</a> · {html.escape(st)} · {html.escape(dt)}<br>{html.escape(w)} <b>Use:</b> {html.escape(u)}</li>' for t,url,st,dt,w,u in sources)
      return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily Ingest — {html.escape(lane['title'])} — {DATE}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">{CSS}</head><body><main><header><div class="word">{mark()} Buildn</div><div class="eyebrow">Daily Ingest Dossier · {DATE}</div><h1>{html.escape(lane['title'])}</h1><p class="read">{html.escape(lane['readout'])}</p></header><section class="card"><h2>Signal map</h2>{diagram(lane['title'],len(sources),len(lane['slug']))}<div class="callout">Selection rationale: {html.escape(lane['rationale'])}</div></section><section><h2>Dossier</h2>{cards}</section><section class="card"><h2>Use-case matrix</h2><table class="matrix"><thead><tr><th>Signal</th><th>Buildn OS</th><th>Client work</th><th>Agent workflow</th><th>Personal leverage</th></tr></thead><tbody>{matrix}</tbody></table></section><section class="card"><h2>Top actions</h2><ol class="wins"><li>Open the primary source and extract its actual constraints.</li><li>Run one bounded experiment with a visible acceptance test.</li><li>Record quality, cost, latency, and failure evidence.</li></ol></section><section class="card"><h2>Source trail</h2><ul class="facts">{src}</ul></section><footer>Generated {STAMP}. Research is selective; vendor claims are labeled as such.</footer></main></body></html>'''
    links=''.join(f'<article class="card"><div class="eyebrow">Lane {i}</div><h2><a href="{s}/">{html.escape(t)}</a></h2><p>{html.escape(r)}</p><div class="badges"><span class="badge good">{len(src)} sources</span><span class="badge">{len(items)} dossier items</span></div></article>' for i,(s,t,r,src,items) in enumerate([(l['slug'],l['title'],l['rationale'],l['sources'],l['items']) for l in lanes],1))
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily Ingest — {DATE}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">{CSS}</head><body><main><header><div class="word">{mark()} Buildn</div><div class="eyebrow">Adaptive Daily Ingest · {DATE}</div><h1>From model capacity to practical adoption</h1><p class="read">Today’s strongest signal is operational: frontier models widen the work envelope, public-sector access creates a real adoption window, services firms are asked to prove production capability, and developer communities provide a hands-on distribution channel. The common thread is not novelty; it is turning access into bounded, reviewable practice.</p></header><section class="card"><h2>Editorial thesis</h2>{diagram('overview',4,1)}<p><span class="hl">Prototype the workflow, not the headline.</span> Prioritize one model benchmark, one governed rollout checklist, one proof artifact, and one hands-on learning loop.</p></section><section><h2>Selected lanes</h2>{links}</section><section class="card"><h2>All-lanes top three</h2><ol class="wins"><li><b>Benchmark Gemini 4 Argon-style long-horizon work</b> with cost, cache, review, and rollback telemetry.</li><li><b>Turn the October 1 public-sector window into a readiness checklist</b> covering eligibility, spend, training, and data.</li><li><b>Build a proof ladder for services work</b> using one repeatable workflow and dated production evidence.</li></ol></section><section class="card"><h2>Source trail</h2><ul class="facts">{''.join(f'<li><a href="{u}">{html.escape(t)}</a> · {html.escape(st)}</li>' for l in lanes for t,u,st,dt,w,us in l['sources'])}</ul></section><footer>Generated {STAMP}. All lane reports are self-contained and script-free.</footer></main></body></html>'''

out=ROOT/DATE
out.mkdir(exist_ok=True)
(out/'index.html').write_text(page('overview'),encoding='utf-8')
for l in lanes: (out/(l['slug']+'.html')).write_text(page(l['title'],l),encoding='utf-8')
ledger={'date':DATE,'generated_at':STAMP,'editorial_thesis':'Frontier capacity only matters when it becomes bounded, reviewable practice: benchmark the model, govern the rollout, prove delivery, and learn in public.','topic_groups':[]}
for l in lanes:
    ledger['topic_groups'].append({'slug':l['slug'],'title':l['title'],'selection_rationale':l['rationale'],'sources':[{'title':t,'url':u,'source_type':st,'published_or_updated':dt,'why_selected':w,'usefulness':us} for t,u,st,dt,w,us in l['sources']]})
(out/'ledger.json').write_text(json.dumps(ledger,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')

# Durable local artifacts; never overwrite a historic same-day artifact.
ART.mkdir(parents=True,exist_ok=True)
for p in [out/'index.html',*(out/(l['slug']+'.html') for l in lanes),out/'ledger.json']:
    target=ART/p.name
    if target.exists(): target=ART/(p.stem+'-'+datetime.now(timezone.utc).strftime('%H%M%S')+p.suffix)
    shutil.copy2(p,target)

# Update source memory and rolling coverage while preserving all prior history.
seen=json.loads((ROOT/'seen-sources.json').read_text())
seen['updated_at']=STAMP
for l in lanes:
    for t,u,st,dt,w,us in l['sources']:
        prev=seen.setdefault('sources',{}).get(u,{})
        seen['sources'][u]={'first_seen':prev.get('first_seen',DATE),'last_seen':DATE,'title':t}
(ROOT/'seen-sources.json').write_text(json.dumps(seen,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
coverage=json.loads((ROOT/'topic-coverage.json').read_text())
coverage.setdefault('daily_history',[]).append({'date':DATE,'selected_lanes':[l['slug'] for l in lanes],'items':[{'title':t,'url':u,'source_type':st} for l in lanes for t,u,st,dt,w,us in l['sources']],'selection_rationale':'Fresh October 1 signals with practical adoption value and deliberate rotation toward public-sector access, services proof, and developer community learning.'})
for l in lanes:
    key=l['slug']; rec=coverage.setdefault('rolling_theme_summary',{}).setdefault(key,{'title':l['title'],'times_covered':0,'last_covered':None}); rec['title']=l['title']; rec['times_covered']+=1; rec['last_covered']=DATE
# retain at least 45 days of item detail, but keep compact history entries
coverage['daily_history']=coverage['daily_history'][-90:]
coverage['last_successful_run']={'date':DATE,'generated_at':STAMP,'lanes':[l['slug'] for l in lanes]}
(ROOT/'topic-coverage.json').write_text(json.dumps(coverage,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
print(json.dumps({'date':DATE,'files':[str(p) for p in out.iterdir()],'lanes':[l['slug'] for l in lanes]}))
