from pathlib import Path
import json, datetime, html

DATE='2026-08-05'
STAMP='2026-08-05T08:05:00Z'
ROOT=Path('/root/Projects/artifact-library/artifacts/daily-ingest')
ROOT.mkdir(parents=True, exist_ok=True)

lanes=[
 {"slug":"agent-runtime-observability","title":"Agent Runtime + Observability","rationale":"Agent-operation coverage is a gap after recent governance and browser-control dossiers. Fresh Cloudflare releases make the execution substrate, local debug loop, and production trace boundary concrete.","sources":[
 {"title":"Preview: @cloudflare/computer agent runtime","url":"https://developers.cloudflare.com/changelog/post/2026-08-03-cloudflare-computer/","source_type":"release","published_or_updated":"2026-08-03","why_selected":"A new open-source runtime combines SQLite-backed workspaces with an explicit isolate/container split and audited operations.","usefulness":"Buildn: evaluate it for file-aware delivery agents. Client work: make execution backends and audit trails a design choice, not an implementation accident.","what":"Early-preview agent workspace runtime: per-agent filesystem, Git and shell capabilities, then isolate or Linux-container execution as the task requires.","why":"It turns ‘agent needs a computer’ into a bounded runtime architecture instead of a blanket container grant.","cases":"Prototype code/document tasks in isolates; reserve containers for native binaries and package installs.","caveat":"Preview software; test isolation, quotas, retention and destructive-command policy before production.","action":"Read the repository and model one low-risk workspace task."},
 {"title":"AI agents can debug Workers with local tracing","url":"https://developers.cloudflare.com/changelog/post/2026-08-04-local-tracing/","source_type":"release","published_or_updated":"2026-08-04","why_selected":"Local OpenTelemetry traces, correlated logs, and a read-only Explorer API give an agent evidence without deploying or attaching temporary logs.","usefulness":"Buildn: tighten the fix–rerun–verify loop. Client work: offer reproducible debugging sessions rather than opaque AI repair.","what":"wrangler dev and vite dev capture structured traces; detected agent sessions receive a Local Explorer API hint.","why":"The same trace answers ‘what failed?’ for both the developer and the coding agent.","cases":"Give a repair agent read-only local telemetry; require a rerun and trace delta in its handoff.","caveat":"Local observability does not prove production behavior; keep deployment verification separate.","action":"Add a failing local Worker case and require trace-backed repair evidence."},
 {"title":"Agent traces for Think, Flue, and AI SDK instrumented by Agents SDK","url":"https://developers.cloudflare.com/changelog/post/2026-08-04-agent-tracing/","source_type":"release","published_or_updated":"2026-08-04","why_selected":"Production traces now join turns, model calls, tools, approvals, tokens and runtime operations; payload storage remains off by default.","usefulness":"Buildn: create a client-safe incident trail. Client work: identify costly or looping tool paths without collecting sensitive payloads by default.","what":"Agents SDK tracing instruments Think/Flue automatically and wraps direct AI SDK calls; sessions can be inspected as waterfalls.","why":"It gives operational facts—tool sequence, approval point, token use—rather than an aggregate agent-success metric.","cases":"Tag runs with agent and conversation IDs; alert on repeat-tool loops and abnormal token growth.","caveat":"Only enable stored messages/tools after a data-classification decision.","action":"Turn on trace metadata first; leave payload recording disabled."}
 ]},
 {"slug":"platform-continuity-security","title":"Platform Continuity + Security Baselines","rationale":"The GitHub Models shutdown became an operational migration today: Spark lost creation access and has an August 31 export deadline. New CodeQL centralization and GitLab migration tooling make a practical continuity lane rather than a generic security roundup.","sources":[
 {"title":"Upcoming deprecation of GitHub Spark on github.com","url":"https://github.blog/changelog/2026-08-04-upcoming-deprecation-of-github-spark-on-github-com/","source_type":"release notice","published_or_updated":"2026-08-04","why_selected":"This materially updates the July 30 GitHub Models retirement: no new Spark apps, existing workbench export ends August 31, and llm() already fails.","usefulness":"Buildn: locate and export client prototypes now. Client work: convert the inventory, inference replacement, and redeploy plan into a bounded continuity engagement.","what":"Spark is being retired: export editable code by August 31. Deployed apps stay up, but GitHub Models-backed llm() calls stopped July 30.","why":"The immediate risk is not only downtime—it is loss of the only editing path for an unexported app.","cases":"Inventory Spark apps; export to repositories; search for llm(); replace inference, keys and billing deliberately.","caveat":"A deployed app surviving retirement does not mean its AI features survive.","action":"Run the Spark export and llm() inventory this week."},
 {"title":"Customize code scanning default setup at scale","url":"https://github.blog/changelog/2026-08-04-customize-code-scanning-default-setup-at-scale","source_type":"release","published_or_updated":"2026-08-04","why_selected":"The new github-codeql-config-file property centralizes configuration without per-repository Actions workflow maintenance.","usefulness":"Buildn: establish a small shared CodeQL baseline. Client work: offer a pilot that standardizes scans while retaining controlled exceptions.","what":"Default CodeQL setup can reference an organization-level configuration, including one stored in another private repository through Git Source access.","why":"It separates a maintained security baseline from repository-by-repository workflow copy/paste.","cases":"Store query packs, exclusions and threat models centrally; pilot one repository; decide override policy.","caveat":"Merged defaults can still change results; establish alert triage ownership before broad rollout.","action":"Create a baseline config repository and test it on one service."},
 {"title":"Migrate from GitLab to GitHub with GitHub Enterprise Importer","url":"https://github.blog/changelog/2026-08-03-migrate-from-gitlab-to-github-with-github-enterprise-importer/","source_type":"release","published_or_updated":"2026-08-03","why_selected":"GA self-service GitLab and GitLab Self-Managed import gives migrations a scriptable CLI path instead of a one-off manual process.","usefulness":"Buildn: assess source-control consolidation requests quickly. Client work: pair bulk migration with security-baseline rollout and agent-workflow portability.","what":"GEI now supports GitLab-to-GitHub Enterprise Cloud via gh gl2gh, including bulk scripting and GitHub-, S3-, or Azure-staged archives.","why":"A repeatable importer reduces coordination friction for portfolio migrations.","cases":"Use a pilot repository to validate metadata, CI, runner, secret and compliance cutover assumptions.","caveat":"GitHub Enterprise Server is not a supported destination.","action":"Write a migration acceptance checklist before moving any production repository."}
 ]},
 {"slug":"operational-knowledge-systems","title":"Operational Knowledge Systems","rationale":"Learning and reusable procedure design have been under-covered since mid-July. New role-specific plugins, distributable skill packs, and comment-triggered repository automations show a useful shift from prompt collections to installed, constrained workflows.","sources":[
 {"title":"New ways to learn and teach with ChatGPT Work and Codex","url":"https://openai.com/index/learn-teach-chatgpt-work-codex/","source_type":"product","published_or_updated":"2026-08-04","why_selected":"Role-specific plugins package skills, instructions, approved apps and workflows while keeping institutional tool and permission control.","usefulness":"Buildn: translate the pattern into client onboarding or internal capability playbooks. Personal leverage: turn a study/project context into active practice rather than a generic chat.","what":"OpenAI introduced K–12 educator, college educator and college student plugins for ChatGPT Edu and teacher deployments.","why":"The product pattern is the signal: capability becomes usable when roles receive context, tools and bounded workflows together.","cases":"Design a client discovery skill with approved documents, a checklist and required evidence outputs.","caveat":"Education availability is limited to specified deployments; the transferable asset is the workflow design, not product access.","action":"Package one repeated Buildn procedure as a skill plus acceptance checklist."},
 {"title":"Skill packs are now available on skills.sh","url":"https://vercel.com/changelog/skill-packs-are-now-available","source_type":"release","published_or_updated":"2026-08-04","why_selected":"A pack can distribute and update several skills with one install command, making workflows versionable operational assets.","usefulness":"Buildn: distribute project-specific discovery, QA and release skills as a tested bundle. Client work: hand off a maintainable operating kit rather than a slide deck.","what":"skills.sh now supports skill packs, installed with npx skills add and updated with npx skills update.","why":"The unit of reuse shifts from a copied prompt to a named, updatable collection of procedures.","cases":"Version a Buildn starter pack: research evidence rules, HTML reporting, deployment checks and client handoff.","caveat":"Review source provenance and changes before updating a pack into an active workflow.","action":"Create a small internal pack with one owner and release notes."},
 {"title":"Trigger Copilot automations with comments","url":"https://github.blog/changelog/2026-08-03-trigger-copilot-automations-with-comments/","source_type":"release","published_or_updated":"2026-08-03","why_selected":"A PR or issue comment can now be the explicit intent boundary for documentation, investigation and follow-up automation.","usefulness":"Buildn: make handoffs reviewable through narrow command phrases. Client work: use comments as audit-friendly approvals instead of invisible background automation.","what":"Copilot cloud agent automations can be triggered by configured issue or pull-request comment text.","why":"A visible comment creates a social and technical checkpoint: intention, scope and resulting artifact are co-located.","cases":"Use /investigate for stack traces or /docs for docs draft; require the automation to open a reviewable PR or issue.","caveat":"Requires eligible Copilot plans; organizations must enable cloud-agent policy.","action":"Pilot one non-destructive comment trigger with a required reviewer."}
 ]}
]

ledger={"date":DATE,"generated_at":STAMP,"editorial_thesis":"Today’s strongest practical signal is operational packaging: make agent execution observable, make platform dependencies exportable and secure, and make reusable knowledge installable as a bounded workflow.","topic_groups":[{k:v for k,v in lane.items() if k in ('slug','title','rationale','sources')} | {'selection_rationale':lane['rationale']} for lane in lanes]}
# retain only schema requested fields
for g in ledger['topic_groups']:
    g.pop('rationale',None)
(ROOT/'daily-ingest-20260805.json').write_text(json.dumps(ledger,indent=2)+"\n")

CSS='''<style>:root{--brand:#01dc82;--deep:#033330;--lime:#cfe66a;--red:#b3261e;--amber:#9a6700;--ink:#0f172a;--muted:#475569;--line:#e2e8f0;--bg:#fafaf9;--card:#fff;--serif:Newsreader,Georgia,serif;--sans:"Plus Jakarta Sans",ui-sans-serif,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:var(--sans);line-height:1.55}main{max-width:68rem;margin:auto;padding:3rem 1.5rem}header{margin-bottom:2.3rem}.wordmark{display:flex;align-items:center;gap:.55rem;font-weight:700;color:var(--deep)}.mark{width:20px;height:20px;background:var(--brand);border-radius:5px;display:inline-block}h1,h2,h3{font-family:var(--serif);color:var(--deep)}h1{font-size:2.2rem;line-height:1.08;margin:.6rem 0}h2{font-size:1.45rem;margin:0 0 .4rem}h3{font-size:1.15rem;margin:.1rem 0}.date,.facts{font:.78rem ui-monospace,SFMono-Regular,monospace;color:var(--muted)}.lead{max-width:52rem;margin:0}.card{background:var(--card);border:1px solid var(--line);border-radius:.8rem;padding:1.4rem;margin:1.3rem 0}.badges{display:flex;gap:.4rem;flex-wrap:wrap;margin:.35rem 0 .9rem}.badge{font-size:.68rem;text-transform:uppercase;letter-spacing:.07em;padding:.16rem .48rem;border-radius:.3rem;background:#eef2f7;color:var(--muted);font-weight:700}.good{background:#dcfce7;color:#166534}.warn{background:#fef3c7;color:#854d0e}.diagram{border:1px solid var(--line);border-radius:.55rem;padding:.75rem;margin:1rem 0;background:#fff}.diagram svg{display:block;max-width:100%;height:auto}.label{font:700 11px var(--sans);fill:#475569;letter-spacing:.06em}.item{border-top:1px solid var(--line);padding:1.1rem 0}.item:first-of-type{border-top:0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.8rem}.mini{background:#f8fafc;border:1px solid var(--line);border-radius:.55rem;padding:.7rem;font-size:.86rem}.callout{border-left:3px solid var(--amber);background:#fffbeb;color:#713f12;padding:.65rem .85rem;border-radius:.25rem;font-size:.9rem}.actions li{margin:.35rem 0}a{color:#087f51;font-weight:600}.matrix{width:100%;border-collapse:collapse;font-size:.86rem}.matrix th,.matrix td{border-bottom:1px solid var(--line);padding:.55rem;text-align:left}.matrix th{color:var(--deep)}@media(max-width:620px){.grid{grid-template-columns:1fr}main{padding:2rem 1rem}}</style>'''

def diagram(slug):
    labels={'agent-runtime-observability':['WORKSPACE','LOCAL TRACE','PROD TRACE','REVIEW'], 'platform-continuity-security':['INVENTORY','EXPORT / MOVE','BASELINE','ACCEPT'], 'operational-knowledge-systems':['ROLE','SKILL PACK','EXPLICIT TRIGGER','REVIEW']}[slug]
    boxes=''.join(f'<rect x="{10+i*150}" y="35" width="120" height="48" rx="7" fill="#fff" stroke="#cbd5e1"/><text x="{70+i*150}" y="64" text-anchor="middle" class="label">{x}</text>' for i,x in enumerate(labels))
    lines=''.join(f'<line x1="{130+i*150}" y1="59" x2="{155+i*150}" y2="59" stroke="#01dc82" stroke-width="2" marker-end="url(#arrow)"/>' for i in range(3))
    return f'<div class="diagram"><svg viewBox="0 0 600 118" role="img" aria-label="{html.escape(" to ".join(labels))} workflow"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#01dc82"/></marker></defs><text x="10" y="18" class="label">SIGNAL MAP</text>{boxes}{lines}</svg></div>'

def lane_html(l):
    items=''.join(f'''<article class="item"><h3><a href="{s['url']}">{html.escape(s['title'])}</a></h3><div class="badges"><span class="badge good">{s['source_type']}</span><span class="badge">{s['published_or_updated']}</span></div><div class="grid"><div class="mini"><strong>What</strong><br>{html.escape(s['what'])}</div><div class="mini"><strong>Why now</strong><br>{html.escape(s['why'])}</div><div class="mini"><strong>Buildn / client use</strong><br>{html.escape(s['cases'])}</div><div class="mini"><strong>Caveat</strong><br>{html.escape(s['caveat'])}</div></div><p class="date">FOLLOW-UP → {html.escape(s['action'])}</p></article>''' for s in l['sources'])
    rows=''.join(f'<tr><td>{html.escape(s["title"])}</td><td>Yes</td><td>Yes</td><td>Yes</td><td>Selective</td></tr>' for s in l['sources'])
    trail=''.join(f'<li><a href="{s["url"]}">{html.escape(s["title"])}</a></li>' for s in l['sources'])
    actions=''.join(f'<li><strong>{html.escape(s["action"])}</strong></li>' for s in l['sources'])
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily Ingest Dossier — {html.escape(l['title'])} — {DATE}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,600&family=Plus+Jakarta+Sans:wght@400;600;700&display=swap" rel="stylesheet">{CSS}</head><body><main><header><div class="wordmark"><span class="mark"></span>Buildn</div><p class="date">DAILY INGEST DOSSIER · {DATE}</p><h1>{html.escape(l['title'])}</h1><p class="lead">{html.escape(l['rationale'])} The useful move is to turn these releases into a small, reviewable operating experiment—not a platform-wide rollout.</p></header><section><article class="card"><h2>Signal map</h2>{diagram(l['slug'])}<p class="callout">Editorial read: choose explicit boundaries, preserve evidence, and keep a human acceptance step at the edge of consequential change.</p></article><article class="card"><h2>Selected dossiers</h2>{items}</article><article class="card"><h2>Use-case matrix</h2><table class="matrix"><thead><tr><th>Signal</th><th>Buildn OS</th><th>Client work</th><th>Agent workflows</th><th>Personal leverage</th></tr></thead><tbody>{rows}</tbody></table></article><article class="card"><h2>Top actions</h2><ol class="actions">{actions}</ol></article><article class="card"><h2>Source trail</h2><ul>{trail}</ul></article></section></main></body></html>'''

for lane in lanes:
    (ROOT/f'daily-ingest-{lane["slug"]}-20260805.html').write_text(lane_html(lane))

overview_cards=''.join(f'<article class="card"><div class="badges"><span class="badge good">SELECTED LANE</span></div><h2>{html.escape(l["title"])}</h2><p>{html.escape(l["rationale"])}</p><p><a href="daily-ingest-{l["slug"]}-20260805.html">Open dossier →</a></p></article>' for l in lanes)
overview=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily Ingest Overview — {DATE}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,600&family=Plus+Jakarta+Sans:wght@400;600;700&display=swap" rel="stylesheet">{CSS}</head><body><main><header><div class="wordmark"><span class="mark"></span>Buildn</div><p class="date">DAILY INGEST OVERVIEW · {DATE}</p><h1>Make operating knowledge executable.</h1><p class="lead">Today connects three practical changes: observable agent runtimes, exportable platform dependencies, and reusable skills that remain bounded by visible intent and review.</p></header><section>{overview_cards}<article class="card"><h2>All-lanes top three</h2><ol class="actions"><li><strong>Export every GitHub Spark app before August 31 and replace broken llm() paths.</strong></li><li><strong>Adopt trace metadata for one agent workflow; keep payload capture off.</strong></li><li><strong>Package one repeated delivery procedure as an owned skill pack.</strong></li></ol></article></section></main></body></html>'''
(ROOT/'daily-ingest-overview-20260805.html').write_text(overview)
print('generated', len(lanes), 'lanes')
