from pathlib import Path
from datetime import datetime, timezone
import html, json

DATE='2026-07-26'; STAMP='20260726'
OUT=Path('/root/Projects/artifact-library/artifacts/daily-ingest'); OUT.mkdir(parents=True,exist_ok=True)
lanes=[
 {'slug':'bounded-execution-and-artifact-access','title':'Bounded Execution + Artifact Access','rationale':'This is a deliberately narrow operational lane: recent coverage examined agent authority, while these releases expose the runtime, time, and stored-output boundaries an operator must now govern.',
  'readout':'Longer jobs and browser-accessible sandboxes increase practical delivery capacity. The useful move is to make runtime inspection and artifact protection part of the same operating checklist—not an afterthought after an agent finishes.',
  'items':[
   ('Workflow steps now support extended function durations','https://vercel.com/changelog/workflow-steps-now-support-extended-function-durations','release','2026-07-24','Vercel Pro and Enterprise workflow steps can run up to 30 minutes, up from 800 seconds, after enabling an environment flag; Hobby remains capped at five minutes.','Use it for one bounded, resumable client task such as a site audit or media transformation, with an explicit timeout and output contract.','The feature is beta, plan-gated, and requires Fluid compute plus a supported runtime.','Classify current jobs by five-minute, 13-minute, and 30-minute needs before enabling the flag.'),
   ('Connect to and manage Sandboxes from the dashboard','https://vercel.com/changelog/connect-to-and-manage-sandboxes-from-the-dashboard','release','2026-07-23','The dashboard can now open a terminal into a running Sandbox, browse files, transfer files, inspect ports, snapshot, stop, and resume persistent sandboxes.','Add an operator inspection step for agent runs that produce deployable files or need incident triage.','Browser terminal access widens the administrative surface; access reviews and secret hygiene still apply.','Document which roles may connect, export files, snapshot, or expose ports for each sandbox class.'),
   ('Vercel WAF for Blob is now in beta','https://vercel.com/changelog/vercel-waf-for-blob-is-now-in-beta','release','2026-07-24','Vercel can apply deny, challenge, rate-limit, redirect, and log rules at the edge for Blob stores without changing blob URLs or application code.','Protect client downloads, generated reports, and expensive media endpoints before transfer occurs.','One shared rule set covers every protected store; challenge rules block matching server-side blob requests.','Inventory public Blob paths, then pilot a rate limit and logging rule on one non-critical store.'),
  ]},
 {'slug':'delegated-work-intake','title':'Delegated Work Intake','rationale':'This fills a coverage gap between agent capability and portfolio coordination: the fresh signal is not another coding model, but a clearer handoff from a work item to a supervised draft PR.',
  'readout':'Issue trackers are becoming the control point for delegated implementation. Keep the human as accountable owner, make task context structured, and treat agent guidance as versioned operational policy.',
  'items':[
   ('Copilot cloud agent for Linear is now generally available','https://github.blog/changelog/2026-07-23-copilot-cloud-agent-for-linear-is-now-generally-available','release','2026-07-23','GitHub Copilot cloud agent can be assigned from Linear to work asynchronously in an ephemeral GitHub Actions environment, update the issue timeline, and open a draft pull request.','Pilot a low-risk maintenance issue where the acceptance criteria and repository are unambiguous.','Setup requires both organization-owner and Linear-workspace-admin permissions; a draft PR is still not an accepted change.','Create a Linear label for agent-eligible work and require a testable definition of done before delegation.'),
   ('AI Agents — Linear Docs','https://linear.app/docs/agents-in-linear','docs','2026-07-26','Linear keeps the human as primary assignee when work is delegated, supports team-scoped agent access, and records guidance with full history.','Use workspace guidance for universal delivery rules and team guidance for repository, review, and client conventions.','Each third-party agent has its own data handling and interpretation of guidance.','Write a short guidance baseline: allowed repos, required checks, PR naming, and escalation triggers.'),
   ('Multi-select fields for Projects and Issues in public preview','https://github.blog/changelog/2026-07-23-multi-select-fields-for-projects-and-issues-in-public-preview','release','2026-07-23','GitHub Projects and Issue fields can now hold multiple values, enabling one item to be tagged by several teams, modules, or work categories.','Model client impact, workstream, risk, and agent eligibility without forcing a single category.','It is a public preview; avoid making critical governance depend on an unreleased workflow feature.','Add a temporary multi-select taxonomy to one portfolio board and test the filters used in weekly review.'),
  ]},
 {'slug':'consented-personal-context','title':'Consented Personal Context','rationale':'A personal-leverage lane earns inclusion because a new consumer health connector makes selective, revocable context a concrete product pattern—not merely a privacy principle.',
  'readout':'The practical lesson is not to centralize sensitive context. It is to ask for the minimum relevant category at the moment it improves a decision, keep it revocable, and verify consequential outputs against the original record.',
  'items':[
   ('Launching Health in ChatGPT','https://openai.com/index/health-in-chatgpt/','product','2026-07-23','OpenAI is rolling out Health in ChatGPT to logged-in U.S. adults on web and iOS, with permissioned connections to Apple Health and supported medical records.','For personal use, turn a complex appointment or lab-result review into a question-preparation workflow while retaining the source record and clinician as authority.','Availability is U.S.-only, records can be incomplete or stale, and ChatGPT is not medical care.','If eligible, test one low-stakes prompt: ask for questions to bring to an appointment, then verify every claim against the record.'),
   ('View health records in Health on iPhone','https://support.apple.com/en-us/HT208680','docs','2026-07-26','Apple Health downloads records from participating providers to iPhone; sharing can be category-specific and limited to current records rather than future updates.','Use the current-versus-future sharing distinction as a design cue for client consent flows involving sensitive data.','Provider coverage varies, and a connected record is not guaranteed complete or current.','Review existing Health sharing permissions and remove any app that no longer needs access.'),
   ('Health and fitness apps — Apple Developer','https://developer.apple.com/health-fitness/','docs','2026-07-26','Apple describes HealthKit as a permissioned repository and asks apps to clearly explain intended use when requesting health, motion, or location data.','Apply the same request-by-request explanation to Buildn prototypes that handle identity, financial, or customer-sensitive context.','Platform permission controls do not replace a product-level retention, deletion, and human-review policy.','Add purpose, scope, retention, and revoke instructions to the next sensitive-data feature brief.'),
  ]}
]
thesis='The strongest current signal is operational: expanded agent capacity must be paired with visible runtime boundaries, accountable work intake, and narrowly consented context.'

def e(x): return html.escape(str(x),quote=True)
CSS='''<style>:root{--brand:#01dc82;--deep:#033330;--lime:#cfe66a;--red:#b3261e;--amber:#9a6700;--ink:#0f172a;--muted:#475569;--line:#e2e8f0;--bg:#fafaf9;--card:#fff;--serif:"Newsreader",Georgia,serif;--sans:"Plus Jakarta Sans",ui-sans-serif,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:var(--sans);line-height:1.55}main{max-width:68rem;margin:auto;padding:3rem 1.5rem 5rem}header{margin-bottom:2rem}.wordmark{display:flex;align-items:center;gap:.55rem;font-weight:700;color:var(--deep)}h1,h2{font-family:var(--serif);color:var(--deep)}h1{font-size:2.3rem;line-height:1.12;margin:.8rem 0 .4rem}h2{font-size:1.4rem;margin:0 0 .5rem}p{margin:.45rem 0 1rem}.date{font:.78rem ui-monospace,monospace;color:var(--muted)}.card{background:var(--card);border:1px solid var(--line);border-radius:.8rem;padding:1.35rem;margin:1.15rem 0}.badges{display:flex;gap:.45rem;flex-wrap:wrap;margin-bottom:.75rem}.badge{font-size:.68rem;text-transform:uppercase;letter-spacing:.07em;font-weight:700;padding:.16rem .48rem;border-radius:.35rem;background:#e2e8f0;color:#334155}.good{background:#dcfce7;color:#166534}.warn{background:#fef3c7;color:#854d0e}.diagram{margin:1rem 0;border:1px solid var(--line);border-radius:.55rem;padding:.8rem;background:#fff}.diagram svg{display:block;width:100%;height:auto}.label{font:600 11px var(--sans);letter-spacing:.08em;fill:#475569}.grid{display:grid;grid-template-columns:1fr 1fr;gap:.8rem}.fact{background:#f8fafc;border:1px solid var(--line);border-radius:.5rem;padding:.75rem;font-size:.9rem}.callout{border-left:3px solid var(--amber);background:#fffbeb;color:#713f12;padding:.65rem .85rem;border-radius:.25rem;font-size:.9rem}a{color:#087d54}table{border-collapse:collapse;width:100%;font-size:.85rem}th,td{border:1px solid var(--line);padding:.55rem;text-align:left}th{background:#f8fafc;color:var(--deep)}.top{border-color:#9ee8ca;background:#f4fff9}@media(max-width:620px){.grid{grid-template-columns:1fr}h1{font-size:1.9rem}}</style>'''
LOGO='''<div class="wordmark"><svg viewBox="0 0 40 40" width="23" aria-hidden="true"><path d="M2 38 6 10 12 2h25l-4 26-7 8Z" fill="#01dc82"/><path d="M15 9h15l-2 12H13Z" fill="#033330"/></svg><span>Buildn</span></div>'''
def head(title): return f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily Ingest Dossier — {e(title)} — {DATE}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">{CSS}</head><body><main><header>{LOGO}<h1>Daily Ingest Dossier — {e(title)}</h1><div class="date">{DATE} · Adaptive research brief</div>'
def report(lane):
 items=lane['items']; w=720; nodes=''.join(f'<g transform="translate({20+i*220},54)"><rect width="185" height="74" rx="8" fill="#f8fafc" stroke="#cbd5e1"/><text x="92" y="29" text-anchor="middle" class="label">{e(x[0][:24])}</text><text x="92" y="51" text-anchor="middle" class="label">{e(x[3])}</text></g>' for i,x in enumerate(items))
 svg=f'<div class="diagram"><svg viewBox="0 0 {w} 176" role="img" aria-label="Signal map"><path d="M28 28H{w-28}" stroke="#01dc82" stroke-width="3"/><text x="20" y="18" class="label">TODAY’S SIGNALS</text>{nodes}<path d="M28 147H{w-28}" stroke="#cbd5e1" stroke-dasharray="5 5"/><text x="20" y="168" class="label">EVIDENCE → BOUNDED PILOT → OPERATING RULE</text></svg></div>'
 out=head(lane['title'])+f'<p>{e(lane["readout"])}</p></header><section><article class="card"><h2>Signal map</h2><div class="badges"><span class="badge good">fresh signal</span><span class="badge">coverage gap</span></div>{svg}<div class="callout"><strong>Why this lane:</strong> {e(lane["rationale"])}</div></article>'
 for n,x in enumerate(items,1):
  title,url,typ,pub,what,use,caveat,action=x
  out+=f'<article class="card"><div class="badges"><span class="badge good">{e(typ)}</span><span class="badge">{e(pub)}</span></div><h2>{n}. <a href="{e(url)}">{e(title)}</a></h2><div class="grid"><div class="fact"><strong>What it is</strong><br>{e(what)}</div><div class="fact"><strong>Buildn / client use</strong><br>{e(use)}</div></div><p><strong>Why useful now:</strong> {e(lane["rationale"])}</p><div class="callout"><strong>Caveat:</strong> {e(caveat)}</div><p><strong>Follow-up action:</strong> {e(action)}</p></article>'
 out+='<article class="card"><h2>Use-case matrix</h2><table><thead><tr><th>Theme</th><th>Buildn OS</th><th>Client work</th><th>Agent workflows</th><th>Personal leverage</th></tr></thead><tbody><tr><td>Scope</td><td>Named access boundary</td><td>Reversible pilot</td><td>Explicit acceptance test</td><td>Minimum useful context</td></tr><tr><td>Review</td><td>Operator visibility</td><td>Human remains accountable</td><td>Log outputs and escalation</td><td>Verify source records</td></tr></tbody></table></article><article class="card top"><h2>Top actions</h2><ol>'+''.join(f'<li><a href="{e(x[1])}">{e(x[0])}</a> — {e(x[7])}</li>' for x in items[:3])+'</ol></article><article class="card"><h2>Source trail</h2><ul>'+''.join(f'<li><a href="{e(x[1])}">{e(x[0])}</a> <span class="date">({e(x[2])}, {e(x[3])})</span></li>' for x in items)+'</ul></article></section></main></body></html>'
 return out
ledger={'date':DATE,'generated_at':datetime.now(timezone.utc).isoformat(),'editorial_thesis':thesis,'topic_groups':[]}
for lane in lanes:
 ledger['topic_groups'].append({'slug':lane['slug'],'title':lane['title'],'selection_rationale':lane['rationale'],'sources':[{'title':x[0],'url':x[1],'source_type':x[2],'published_or_updated':x[3],'why_selected':x[4],'usefulness':x[5]} for x in lane['items']]})
 (OUT/f'daily-ingest-{lane["slug"]}-{STAMP}.html').write_text(report(lane))
(OUT/f'daily-ingest-{STAMP}.json').write_text(json.dumps(ledger,indent=2))
links=''.join(f'<li><a href="{e(l["slug"])}.html">{e(l["title"])}</a> — {e(l["rationale"])}</li>' for l in lanes)
overview=head('Overview')+f'<p>{e(thesis)}</p></header><section><article class="card top"><h2>Editorial thesis</h2><p>{e(thesis)}</p></article><article class="card"><h2>Selected lanes</h2><ul>{links}</ul></article><article class="card"><h2>All-lanes top three</h2><ol><li><a href="bounded-execution-and-artifact-access.html">Bounded execution + artifact access</a> — classify jobs before extending run duration.</li><li><a href="delegated-work-intake.html">Delegated work intake</a> — pilot one agent-eligible issue with a human-owned definition of done.</li><li><a href="consented-personal-context.html">Consented personal context</a> — use category-level, revocable permissions for sensitive context.</li></ol></article><article class="card"><h2>Reports</h2><div class="grid">'+''.join(f'<div class="fact"><a href="{e(l["slug"])}.html"><strong>{e(l["title"])}</strong></a><br>{e(l["readout"])}</div>' for l in lanes)+'</div></article></section></main></body></html>'
(OUT/f'daily-ingest-overview-{STAMP}.html').write_text(overview)
coverage_path=Path('/root/Projects/daily-ingest-pages/topic-coverage.json'); coverage=json.loads(coverage_path.read_text()) if coverage_path.exists() else {'schema_version':1,'rolling_theme_summary':{},'item_history':[],'runs':[]}; summary=coverage.setdefault('rolling_theme_summary',{})
for lane in lanes:
 s=summary.setdefault(lane['slug'],{'title':lane['title'],'times_covered':0,'last_covered':None}); s['title']=lane['title']; s['times_covered']=int(s.get('times_covered',0))+1; s['last_covered']=DATE
 for x in lane['items']: coverage.setdefault('item_history',[]).append({'date':DATE,'lane':lane['slug'],'title':x[0],'url':x[1],'source_type':x[2],'selection_rationale':x[4]})
coverage['item_history']=[i for i in coverage['item_history'] if i.get('date','')>='2026-06-11']
run={'date':DATE,'selected_lanes':[{'slug':l['slug'],'title':l['title'],'selection_rationale':l['rationale']} for l in lanes],'editorial_thesis':thesis}
coverage['runs']=[r for r in coverage.setdefault('runs',[]) if r.get('date')!=DATE]+[run]; coverage['last_run']=run; coverage['last_editorial_thesis']=thesis; coverage['updated_at']=ledger['generated_at']; coverage_path.write_text(json.dumps(coverage,indent=2))
