#!/usr/bin/env python3
from pathlib import Path
import datetime as dt, html, json

DATE='2026-07-31'; STAMP=dt.datetime.now(dt.timezone.utc).isoformat()
OUT=Path('/root/Projects/artifact-library/artifacts/daily-ingest'); OUT.mkdir(parents=True,exist_ok=True)
PAGES=Path('/root/Projects/daily-ingest-pages')
lanes=[
 {'slug':'agent-routing-economics','title':'Agent Routing Economics','rationale':'A same-day OpenAI price and latency update materially changes the economics of high-volume agent work; this is a concrete update to the model-choice lane covered July 29, not a repeat of its earlier policy framing.','readout':'Routing can now be a workflow decision: reserve Sol for uncertainty, move defined background work to Luna, and pay the Fast premium only when latency has a measurable business value. Re-baseline rather than assume the old mix remains rational.','signal':['uncertainty','Sol','Terra / Luna','measured route'],
 'sources':[{'title':'Advancing the price-performance frontier with GPT-5.6','url':'https://openai.com/index/advancing-the-price-performance-frontier-with-gpt-5-6/','source_type':'product','published_or_updated':'2026-07-30','why_selected':'OpenAI cut Luna API pricing by 80% and Terra by 20%, while introducing Sol Fast mode at a stated 2× price for up to 2.5× speed.','usefulness':'Makes a measured task-tier routing pilot cheaper to run and easier to justify.'},{'title':'GPT-5.6: Frontier intelligence that scales with your ambition','url':'https://openai.com/index/gpt-5-6/','source_type':'product','published_or_updated':'2026-07-30 update','why_selected':'The product page defines the family roles and the Responses API tool-calling context for the pricing change.','usefulness':'Supplies a practical division of labor for planning, execution, testing, and evaluation.'}],
 'cards':[('Re-price the background queue','Luna is now $0.20 input and $1.20 output per million tokens, according to OpenAI.','High-volume, tool-using and multi-step work has a new cost baseline.','Move deterministic extraction, test-writing, evaluation, and batch enrichment to a controlled Luna cohort.','Price is not quality evidence; compare completion, rework, and escalation rates.','Run 50 historical tasks through the current route and Luna; record outcome cost.'),('Keep uncertainty on the high tier','OpenAI positions Sol for consequential work and Luna for well-defined execution.','The price cut is useful only when routing follows task uncertainty rather than model fashion.','Use Sol for plan and exception resolution; give workers bounded implementation and verification jobs.','Model labels are vendor positioning, not an acceptance test.','Write a three-tier routing rubric with explicit human escalation.'),('Treat Fast mode as a service level','Sol Fast replaces Priority Processing and is stated to offer up to 2.5× speed at 2× the price.','Latency becomes an auditable per-workflow trade-off, not a blanket account setting.','Use it for live operator or client interaction; preserve Standard for queued work.','Actual latency and quality vary by prompt, tool calls, and capacity.','Measure p50/p95 latency, completed-work rate, and dollars per finished task.')]
 },
 {'slug':'reviewable-delegated-delivery','title':'Reviewable Delegated Delivery','rationale':'GitHub stacks and Linear’s new review/coding-session surfaces are fresh, complementary delivery controls. The lane deliberately shifts from last week’s agent governance toward the human review bottleneck created by parallel implementation.','readout':'Split large work into reviewable layers and keep delegation observable from the issue system. The useful pattern is not autonomous throughput; it is smaller diffs, signed outputs, and direct steering before merge.','signal':['issue','delegated session','small diff','protected merge'],
 'sources':[{'title':'Stacked pull requests are now in public preview','url':'https://github.blog/changelog/2026-07-30-stacked-pull-requests-are-now-in-public-preview/','source_type':'release','published_or_updated':'2026-07-30','why_selected':'GitHub now supports dependency-ordered PR layers that retain existing checks and branch protections.','usefulness':'Lets an agent or developer land a large feature as small independently reviewable units.'},{'title':'Coding sessions on mobile','url':'https://linear.app/changelog/2026-07-30-coding-sessions-on-mobile','source_type':'release','published_or_updated':'2026-07-30','why_selected':'Linear adds mobile session steering, GA Guided Reviews, GitHub-team review assignment, and signed commits for coding sessions.','usefulness':'Makes delegated implementation visible and steerable without turning mobile access into blind approval.'}],
 'cards':[('Stack the change, not the review burden','Each PR targets the layer below it; GitHub shows the layer diff and maintains upper branches after merges.','Reviewers can assess one logical boundary at a time while the complete feature still moves.','Use for schema → service → interface changes; keep each layer independently testable.','Preview rollout and merge-queue support are progressive.','Install gh-stack in one active repository; split the next cross-cutting feature into three layers.'),('Make Linear the steering surface','Mobile coding sessions expose diffs and allow a selected line to be sent back to the session.','A delegated task stays connected to its issue, status, and feedback rather than becoming a hidden terminal job.','Use comments to clarify acceptance criteria and inspect a diff before a PR becomes review-ready.','Mobile steering is not a substitute for protected merge review.','Choose one bounded issue; require a written acceptance check before the agent opens a draft PR.'),('Use guided reviews and signatures together','Guided Reviews are GA for Business and Enterprise; coding sessions can now produce signed commits.','Readable change sections and provenance address different review risks: comprehension and authorship.','Assign review to a GitHub team and require signing on client repositories with agent work.','Signed commits do not validate intent or behavior.','Enable signing for a pilot workspace and inspect the review trail end-to-end.')]
 },
 {'slug':'visual-design-to-code-feedback','title':'Visual Design-to-Code Feedback','rationale':'Figma Make’s July 30 properties panel and canvas annotations are a material delivery update after the July 27 design-production coverage: edits can now be staged visually and applied to underlying code with targeted context.','readout':'The design handoff can become a precise, reviewable code-change loop. Use direct manipulation for token-aligned visual changes and annotations for behavior, but retain code review as the shipping gate.','signal':['canvas target','staged edit','code version','PR review'],
 'sources':[{'title':'A Properties Panel and Annotations, Now in Figma Make','url':'https://www.figma.com/blog/properties-panel-and-annotations-now-in-figma-make/','source_type':'product','published_or_updated':'2026-07-30','why_selected':'Figma Make adds direct visual property editing and marked-canvas instructions that apply to underlying code.','usefulness':'Offers a lower-ambiguity way to turn client feedback into staged, inspectable implementation changes.'}],
 'cards':[('Direct manipulation becomes a code request','The properties panel changes spacing, typography, layout, borders, and more through selected elements and a DOM tree.','A specific selected target is less ambiguous than an unbounded visual prompt.','Use for small client polish rounds that should preserve existing color and typography tokens.','The panel currently works only with new Make designs.','Prototype one component polish pass; compare visual spec, generated diff, and token use.'),('Annotate interaction intent in place','Annotations attach natural-language instructions to marked canvas areas, including multi-element interaction and animation work.','Feedback can retain both location and intent instead of being translated through a generic ticket.','Use for hover, delay, navigation, and state-transition requests before handing a code diff to review.','Agent interpretation still needs accessibility and behavior checks.','Define an annotation template: target, trigger, expected behavior, and keyboard fallback.'),('Stage before committing credits and code','Figma says edits are staged in chat, can be reviewed or discarded, and consume credits only when applied into a new version.','Staging creates a decision point before cost and code mutation.','Use staged batches for stakeholder sign-off, then export changes into the normal branch/PR path.','A Make version is not a production deployment or an approved PR.','Set a client-review rule: approve staged visual changes before applying; require PR checks before release.')]
 },
 {'slug':'reproducible-build-boundaries','title':'Reproducible Build Boundaries','rationale':'Two July 30 platform changes expose build assumptions that are usually implicit: Cloudflare changed its default Node runtime, while GitHub added a same-commit reference for internal Actions. This is a practical infrastructure lane absent from recent coverage.','readout':'Pin the runtimes that matter and compose internal Actions at the running commit. These small defaults reduce two common sources of deployment surprise: a moving build image and a locally checked-out action that is not the workflow’s own revision.','signal':['version pin','build image','same commit','repeatable deploy'],
 'sources':[{'title':'Node.js 24 is now the default for Workers Builds','url':'https://developers.cloudflare.com/changelog/post/2026-07-30-workers-builds-nodejs-24/','source_type':'release','published_or_updated':'2026-07-30','why_selected':'Workers Builds now defaults to Node.js 24.18.0, with 22.23.2 and 24.18.0 preinstalled.','usefulness':'Prompts an immediate audit of projects that rely on an unpinned Cloudflare build runtime.'},{'title':'Reference same-repository actions with self-repository syntax','url':'https://github.blog/changelog/2026-07-30-reference-same-repository-actions-with-self-repository-syntax/','source_type':'release','published_or_updated':'2026-07-30','why_selected':'The new $/ syntax resolves an internal action or reusable workflow at the executing commit, without checkout.','usefulness':'Keeps internal CI composition aligned with full-SHA-pinning policy and avoids path/check-out coupling.'},{'title':'Using pre-written building blocks in your workflow','url':'https://docs.github.com/actions/how-tos/write-workflows/choose-what-workflows-do/find-and-customize-actions','source_type':'docs','published_or_updated':'2026-07-30','why_selected':'Official documentation specifies $/ as the recommended same-repository syntax and records GHES limits.','usefulness':'Provides the migration reference and the important portability caveat.'}],
 'cards':[('Pin before the default moves you','Cloudflare Workers Builds now uses Node 24.18.0 unless a project overrides it.','A build-image default is an external dependency; relying on it makes compatibility changes arrive on the platform’s schedule.','Add .nvmrc or NODE_VERSION to critical Workers projects and test 24 intentionally.','Pinning can defer upgrades; it is not a permanent security strategy.','Inventory active Workers projects and classify each as pin-22, adopt-24, or retired.'),('Reference internal Actions at the running commit','GitHub’s $/.github/actions/... resolves in the same repository at the exact executing revision and needs no checkout.','Internal composition no longer requires a relative-path checkout or a hardcoded ref that can diverge from the workflow.','Migrate reusable internal build, test, and publish actions after verifying runner version 2.336.0+.','The syntax is not available in GitHub Enterprise Server.','Convert one noncritical workflow; verify behavior, runner version, and GHES exposure.'),('Keep deployment evidence beside the decision','Version files and workflow references make runtime and composition choices visible in review.','Repeatability improves when the source of a build assumption is diffable, not buried in platform defaults.','Add a CI check that prints the selected Node version and validates internal action references.','Logs demonstrate execution, not compatibility.','Create a release checklist: runtime pin, lockfile, action ref, test matrix, rollback.')]
 }
]

def esc(s): return html.escape(str(s))
CSS='''<style>:root{--brand:#01dc82;--deep:#033330;--lime:#cfe66a;--red:#b3261e;--amber:#9a6700;--ink:#0f172a;--muted:#475569;--line:#e2e8f0;--bg:#fafaf9;--card:#fff;--serif:"Newsreader",Georgia,serif;--sans:"Plus Jakarta Sans",system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:var(--sans);line-height:1.55}main{max-width:70rem;margin:auto;padding:3rem 1.5rem 5rem}.wordmark{display:flex;align-items:center;gap:.55rem;font-weight:700;color:var(--deep)}header{margin-bottom:2rem}h1,h2{font-family:var(--serif);color:var(--deep)}h1{font-size:2.25rem;line-height:1.1;margin:.8rem 0 .4rem}h2{font-size:1.4rem;margin:0 0 .45rem}p{margin:.45rem 0 .85rem}a{color:#087c54}.date,.facts{font:.78rem ui-monospace,monospace;color:var(--muted)}.card{background:var(--card);border:1px solid var(--line);border-radius:.8rem;padding:1.35rem;margin:1.1rem 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(235px,1fr));gap:1rem}.badges{display:flex;gap:.45rem;flex-wrap:wrap;margin-bottom:.7rem}.badge{font-size:.67rem;text-transform:uppercase;letter-spacing:.07em;font-weight:700;padding:.16rem .48rem;border-radius:.35rem;background:#e2e8f0;color:#334155}.good{background:#dcfce7;color:#166534}.diagram{margin:1rem 0;border:1px solid var(--line);border-radius:.55rem;padding:.8rem;background:#fff}.diagram svg{display:block;width:100%;height:auto}.label{font:600 10px var(--sans);letter-spacing:.06em;fill:#475569}.matrix{width:100%;border-collapse:collapse;font-size:.83rem}.matrix th,.matrix td{border-bottom:1px solid var(--line);padding:.55rem;text-align:left;vertical-align:top}.callout{border-left:3px solid var(--amber);background:#fffbeb;color:#713f12;padding:.65rem .85rem;border-radius:.25rem;font-size:.9rem}.wins{margin:.4rem 0;padding-left:1.15rem}.wins li{margin:.18rem 0}.top{border-left-color:var(--brand);background:#ecfdf5;color:#14532d}@media(max-width:560px){main{padding:2rem 1rem}.matrix{font-size:.72rem}}</style>'''
def logo(): return '<div class="wordmark"><svg viewBox="0 0 24 28" width="19" aria-hidden="true"><path fill="#01dc82" d="M17 28H0L2 10c1-1 2-1 4-1L7 0h16l1 3-2 16c-1 2-2 2-4 2z"/><path fill="#033330" d="M9 5l-.5 5H14l-.4 5h5l.7-8c-.4-1-1-2-2-2zM5 21l1-7h5l-.4 4h5l-.5 5H7c-1 0-2-1-2-2z"/></svg><span>Buildn</span></div>'
def head(title): return f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">{CSS}</head><body><main>'
def signal(words):
 xs=[20,165,310,455]; boxes=''.join(f'<rect x="{xs[i]}" y="55" width="125" height="48" rx="7" fill="#fff" stroke="#cbd5e1"/><text x="{xs[i]+62}" y="83" text-anchor="middle" class="label">{esc(w)}</text>' for i,w in enumerate(words))
 arrows=''.join(f'<path d="M{xs[i]+125} 79H{xs[i+1]-10}" stroke="#94a3b8" fill="none" marker-end="url(#a)"/>' for i in range(3))
 return f'<div class="diagram"><svg viewBox="0 0 600 155" role="img" aria-label="Signal map"><defs><marker id="a" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0L6 3L0 6z" fill="#94a3b8"/></marker></defs><text x="20" y="26" class="label">DAY’S SIGNAL MAP</text>{arrows}{boxes}<path d="M82 104v27h430" stroke="#01dc82" fill="none"/><text x="297" y="148" text-anchor="middle" class="label">bounded pilot → reviewed evidence → rollout decision</text></svg></div>'
def report(l):
 cards=''.join(f'<article class="card"><div class="badges"><span class="badge good">actionable signal</span><span class="badge">{i+1:02d}</span></div><h2>{esc(c[0])}</h2><p><strong>What:</strong> {esc(c[1])}</p><p><strong>Why it matters:</strong> {esc(c[2])}</p><p><strong>Buildn / client use:</strong> {esc(c[3])}</p><div class="callout"><strong>Caveat:</strong> {esc(c[4])}</div><p><strong>Follow-up:</strong> {esc(c[5])}</p></article>' for i,c in enumerate(l['cards']))
 src=''.join(f'<li><a href="{esc(s["url"])}">{esc(s["title"])}</a> <span class="facts">— {esc(s["published_or_updated"])}</span></li>' for s in l['sources'])
 return head(f'Daily Ingest Dossier — {l["title"]} — {DATE}')+f'<header>{logo()}<h1>Daily Ingest Dossier — {esc(l["title"])}</h1><div class="date">{DATE} · adaptive lane</div><p>{esc(l["readout"])}</p><p><a href="index.html">← today’s overview</a></p></header><section><article class="card"><h2>Signal map</h2>{signal(l["signal"])}<p>{esc(l["rationale"])}</p></article>{cards}<article class="card"><h2>Use-case matrix</h2><table class="matrix"><tr><th>Lens</th><th>Buildn OS</th><th>Client work</th><th>Agent workflows</th><th>Personal leverage</th></tr><tr><td>Pilot</td><td>Reversible and logged</td><td>Approved narrow scope</td><td>Named inputs/outputs</td><td>Low-risk trial</td></tr><tr><td>Evidence</td><td>Traceable artifact</td><td>Reviewable decision</td><td>Acceptance checks</td><td>Reusable notes</td></tr><tr><td>Control</td><td>Owner and rollback</td><td>Consent and access</td><td>Least privilege</td><td>Manual fallback</td></tr></table></article><article class="card"><h2>Top actions</h2><ol class="wins"><li>Open the primary release.</li><li>Choose one bounded workflow.</li><li>Set success, owner, rollback.</li><li>Expand only on evidence.</li></ol></article><article class="card"><h2>Source trail</h2><ul class="wins">{src}</ul></article></section></main></body></html>'
ledger={'date':DATE,'generated_at':STAMP,'editorial_thesis':'Fresh platform changes favor a disciplined operating loop: route work by economics, keep delegated delivery reviewable, turn visual feedback into staged code change, and pin the build assumptions underneath it.','topic_groups':[{'slug':l['slug'],'title':l['title'],'selection_rationale':l['rationale'],'sources':l['sources']} for l in lanes]}
(OUT/'daily-ingest-20260731.json').write_text(json.dumps(ledger,indent=2)+'\n')
for l in lanes: (OUT/f'daily-ingest-{l["slug"]}-20260731.html').write_text(report(l))
links=''.join(f'<article class="card"><div class="badges"><span class="badge good">selected lane</span></div><h2><a href="{l["slug"]}.html">{esc(l["title"])}</a></h2><p>{esc(l["rationale"])}</p></article>' for l in lanes)
top=''.join(f'<li><strong>{esc(l["cards"][0][0])}</strong> — {esc(l["cards"][0][5])}</li>' for l in lanes[:3])
overview=head(f'Daily Ingest Dossier — Overview — {DATE}')+f'<header>{logo()}<h1>Daily Ingest Dossier</h1><div class="date">{DATE} · four adaptive lanes</div><p>Today’s thesis: route work by economics, keep delegated delivery reviewable, turn visual feedback into staged code change, and pin the build assumptions underneath it.</p></header><section><article class="card"><h2>Editorial map</h2>{signal(["task routing","reviewable delivery","visual change","repeatable build"])}<p>Four distinct primary-source updates earned coverage. The connecting pattern is controlled throughput: every new capability has a measurable boundary before it reaches a client or production system.</p></article><div class="grid">{links}</div><article class="card"><h2>All-lanes top three</h2><ol class="wins">{top}</ol><div class="callout top">Recommendation: re-baseline high-volume agent routing first; it makes the other pilots cheaper to run without changing their acceptance standard.</div></article></section></main></body></html>'
(OUT/'daily-ingest-overview-20260731.html').write_text(overview)
# Maintain rolling coverage; avoid overwriting same-date history if a corrected run exists.
p=PAGES/'topic-coverage.json'; cov=json.loads(p.read_text()); summary=cov.setdefault('rolling_theme_summary',{}); history=cov.setdefault('item_history',[])
newurls={s['url'] for l in lanes for s in l['sources']}
history[:]=[x for x in history if not (x.get('date')==DATE and x.get('url') in newurls)]
for l in lanes:
 prev=summary.get(l['slug'],{}); summary[l['slug']]={'title':l['title'],'times_covered':prev.get('times_covered',0)+1,'last_covered':DATE}
 for s in l['sources']: history.append({'date':DATE,'lane':l['slug'],'title':s['title'],'url':s['url'],'source_type':s['source_type'],'selection_rationale':s['why_selected']})
# Item detail covers at least 45 days; retain later dates and preserve compact theme history.
cutoff=(dt.date.fromisoformat(DATE)-dt.timedelta(days=45)).isoformat(); cov['item_history']=[x for x in history if x.get('date','')>=cutoff]; cov['updated_at']=STAMP
p.write_text(json.dumps(cov,indent=2)+'\n')
print('generated',len(lanes),'lanes')
