from pathlib import Path
import json, html
from datetime import datetime, timezone

DATE='2026-08-01'; STAMP='20260801'
ART=Path('/root/Projects/artifact-library/artifacts/daily-ingest'); ART.mkdir(parents=True, exist_ok=True)
coverage_path=Path('/root/Projects/daily-ingest-pages/topic-coverage.json')

lanes=[
 {'slug':'enforced-agent-economics','title':'Enforced Agent Economics','rationale':'Yesterday covered routing economics; today’s material update is the control plane around it: hard team/project/key caps and request-level routing evidence turn an experiment into an operable service.','readout':'Agent spend is now governable at the same scopes where delivery is owned. Treat the cap as a safety boundary, then use route-level traces to decide whether the boundary is correctly sized.','items':[
  {'title':'AI Gateway now supports team and project spend budgets','url':'https://vercel.com/changelog/ai-gateway-spend-budgets-and-alerts','type':'release','date':'2026-07-31','what':'Hard dollar budgets now apply to teams, projects, and API keys; a request must pass every applicable budget.','why':'Moves cost control from after-the-fact reporting to enforced scope-level limits.','use':'Give each client pilot a project ceiling and every agent key a smaller blast-radius cap.','caveat':'A reached limit rejects requests; alerts are off by default, and BYOK spend is excluded by default.','action':'Create one low ceiling for a non-production agent, enable alerts, and rehearse the exhausted-budget path.'},
  {'title':'AI Gateway logs now have a dedicated page','url':'https://vercel.com/changelog/ai-gateway-logs','type':'release','date':'2026-07-30','what':'A request log exposes cost, token classes, latency, routing, fallback attempts, region, and ZDR status; filtered views export as CSV or JSON.','why':'A failed or expensive agent run can be explained by evidence rather than an aggregate bill.','use':'Attach a filtered incident or client-run view to a delivery review; compare fallbacks before changing model policy.','caveat':'This visibility is gateway-scoped; it does not replace application-level outcome telemetry.','action':'Define saved filters for production failures, slow requests, and spend spikes.'},
  {'title':'DeepSeek V4 Flash updated weights on AI Gateway','url':'https://vercel.com/changelog/deepseek-v4-flash-now-runs-updated-weights-on-ai-gateway','type':'release','date':'2026-07-31','what':'The existing model ID now routes to updated weights; Vercel reports Terminal-Bench 82.7, up 25.8 points from the April preview.','why':'A silent model-weight shift is exactly the kind of material change that needs a bounded, observable re-evaluation.','use':'Run a fixed internal coding-task set before moving this route into a client or Buildn workflow.','caveat':'The stated benchmark is provider reporting; updated weights are initially served only by DeepSeek.','action':'Pin a before/after evaluation set and log reliability, cost, and review burden.'}]},
 {'slug':'mcp-identity-bridges','title':'MCP Identity Bridges','rationale':'MCP portability was covered July 24 and stateless migration July 28; this is a specific interoperability unlock: connecting portals to SaaS MCP servers that do not implement dynamic client registration.','readout':'The practical MCP constraint is often not tool schema but OAuth compatibility. A portal can now bridge that gap while preserving a per-user sign-in boundary.','items':[
  {'title':'Static OAuth client credentials for MCP server portals','url':'https://developers.cloudflare.com/changelog/post/2026-07-31-mcp-portal-manual-oauth/','type':'release','date':'2026-07-31','what':'Cloudflare MCP portals can use pre-registered OAuth client credentials, custom endpoints/scopes, and two token-auth methods for upstream services.','why':'It unlocks Slack and GitHub-style upstream MCP servers where Dynamic Client Registration is unavailable or disabled.','use':'Publish a curated client-work portal without exposing raw upstream setup to every agent client.','caveat':'The portal encrypts the client secret, but the upstream OAuth app still needs least-privilege scopes and lifecycle ownership.','action':'Inventory required scopes for one GitHub or Slack connector before registering a portal client.'},
  {'title':'Vercel MCP now supports the 2026-07-28 MCP specification','url':'https://vercel.com/changelog/vercel-mcp-now-supports-the-2026-07-28-mcp-specification','type':'release','date':'2026-07-31','what':'One Vercel MCP endpoint now serves the newer stateless request model and updated authorization behavior while keeping 2025-protocol clients working.','why':'Compatibility across client generations reduces migration pressure, but authorization behavior still needs a deliberate test.','use':'Keep a single deployment/control endpoint available to both current and lagging internal agent clients.','caveat':'Protocol compatibility does not validate each client’s tool permissions or approval behavior.','action':'Test one old and one current MCP client against a least-privilege deployment sandbox.'}]},
 {'slug':'software-supply-chain-publishing','title':'Software Supply-Chain Publishing','rationale':'Recent coverage examined package malware detection; this is a distinct publisher-side credential change with a January 2027 automation deadline.','readout':'npm is narrowing what a bypass-2FA token can do, shifting package administration back to interactive proof and publish automation toward trusted or staged paths.','items':[
  {'title':'Restricting npm 2FA-bypass granular access tokens','url':'https://github.blog/changelog/2026-07-31-restricting-npm-bypass-2fa-granular-access-tokens/','type':'security release','date':'2026-07-31','what':'Bypass-2FA granular tokens can no longer manage tokens, access, maintainers, trusted publishing, organizations, teams, or grants.','why':'A leaked automation credential loses a set of account-takeover and package-control paths.','use':'Audit Buildn/client publish secrets and separate administrative actions from release automation.','caveat':'The restriction applies to npm GATs—not GitHub PATs, App tokens, or GITHUB_TOKEN.','action':'List all bypass-2FA npm tokens and label each as read, stage, or publish automation.'},
  {'title':'npm trusted publishers documentation','url':'https://docs.npmjs.com/trusted-publishers','type':'docs','date':'2026-07-31','what':'npm documents OpenID Connect trusted publishing for supported CI/CD providers.','why':'It is the intended replacement path before bypass-2FA tokens lose direct publishing, targeted for January 2027.','use':'Migrate a low-risk package from stored registry token to CI workload identity.','caveat':'Provider and repository configuration must be exact; test provenance and rollback paths before switching production release.','action':'Open a test-package issue: convert one release workflow to trusted publishing and verify a dry release.'}]},
 {'slug':'living-agent-evaluation-data','title':'Living Agent Evaluation Data','rationale':'Agentic review and model evaluation were covered recently, but this new paper offers a different practical asset: continuously reconstructing executable tasks from an organization’s own merged PR history on healthy current bases.','readout':'The evaluation corpus should evolve with the repository. Change2Task makes the repository’s resolved work a renewable source of realistic bug, feature, migration, test, and security tasks.','items':[
  {'title':'Change2Task: From Repository Changes to Executable Coding Agent Tasks and Environments','url':'https://arxiv.org/abs/2607.28591','type':'paper','date':'2026-07-30','what':'A research system reconstructs verified coding-agent tasks from merged PRs against healthy modern revisions using patch reversal, code mapping, and agent reconstruction.','why':'It tackles the expensive failure mode where historically real tasks no longer execute on obsolete repository states.','use':'Prototype a Buildn evaluation corpus from merged client-safe PRs, with tests as acceptance evidence.','caveat':'Reported results are from a research pipeline, not a turnkey production tool; task leakage and access controls remain local responsibilities.','action':'Select ten merged, non-sensitive PRs and classify whether each has a durable executable acceptance test.'},
  {'title':'Change2Task experimental HTML and resources','url':'https://arxiv.org/html/2607.28591v1','type':'paper resource','date':'2026-07-30','what':'The paper reports 79.6% verified construction across 1,130 eligible changes, 29.2% more verified tasks than its PR-based baseline, and up to 98.0% outcome agreement.','why':'The numbers make a credible case for testing reconstruction before funding a manually curated benchmark program.','use':'Use the lifecycle—healthy base → task state → restored state—as an acceptance contract for internal agent eval cases.','caveat':'Outcome agreement does not prove coverage of your stack, test suite, or engineering conventions.','action':'Adopt the lifecycle check as a gate for every internally generated eval task.'}]}
]

def esc(s): return html.escape(s, quote=True)
def mark(): return '<svg viewBox="0 0 164 195" width="21" aria-hidden="true"><path d="M117 194.5H0L12 73C17 67 21 65 29 65L35 0h117c7 4 10 7 12 13l-11 107c-4 7-8 10-18 11l-4 54c-3 6-6 8-14 10" fill="#01dc82"/><path d="m64 33-3 32h33l-3 32h32l5-50c-2-9-6-12-16-14zM37 148l5-50h33l-3 32h32l-4 32H50c-8-3-10-7-13-14" fill="#033330"/></svg>'
CSS='''<style>:root{--brand:#01dc82;--deep:#033330;--lime:#cfe66a;--red:#b3261e;--amber:#9a6700;--ink:#0f172a;--muted:#475569;--line:#e2e8f0;--bg:#fafaf9;--card:#fff;--serif:"Newsreader",Georgia,serif;--sans:"Plus Jakarta Sans",system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.55 var(--sans)}main{max-width:960px;margin:auto;padding:42px 20px 70px}.wordmark{display:flex;align-items:center;gap:9px;color:var(--deep);font-weight:700}header{margin-bottom:28px}h1,h2,h3{font-family:var(--serif);color:var(--deep)}h1{font-size:2.35rem;line-height:1.1;margin:14px 0 8px}h2{font-size:1.45rem;margin:0 0 8px}h3{font-size:1.05rem;margin:0 0 6px}.date,.facts{font:12px ui-monospace,monospace;color:var(--muted)}.card{background:var(--card);border:1px solid var(--line);border-radius:13px;padding:22px;margin:17px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(245px,1fr));gap:14px}.badge{display:inline-block;font-size:10px;letter-spacing:.08em;text-transform:uppercase;font-weight:700;padding:3px 7px;border-radius:5px;background:#dcfce7;color:#166534}.spec{background:#e2e8f0;color:#334155}.warn{background:#fef3c7;color:#9a6700}.diagram{border:1px solid var(--line);border-radius:10px;padding:10px;margin:15px 0;background:white}.diagram svg{display:block;width:100%;height:auto}.label{font:600 10px var(--sans);fill:#475569;letter-spacing:.05em}.item{border-top:1px solid var(--line);padding:18px 0}.item:first-of-type{border-top:0}.item p{margin:5px 0}.key{font-weight:700;color:var(--deep)}a{color:#087c54}.matrix{width:100%;border-collapse:collapse;font-size:13px}.matrix th,.matrix td{border:1px solid var(--line);padding:9px;text-align:left;vertical-align:top}.matrix th{background:#f1f5f9;color:var(--deep)}.callout{border-left:3px solid var(--brand);background:#f0fdf4;padding:11px 13px;border-radius:4px}.actions{margin:6px 0;padding-left:20px}.actions li{margin:6px 0}.sources{word-break:break-word;font-size:13px}.sources li{margin:6px 0}@media(max-width:600px){h1{font-size:1.9rem}main{padding-top:28px}}</style>'''
def diagram(title, labels):
 boxes=''.join(f'<rect x="{15+i*150}" y="42" width="118" height="42" rx="7" fill="#fff" stroke="#cbd5e1"/><text x="{74+i*150}" y="60" text-anchor="middle" class="label">{esc(x[:18]).upper()}</text><text x="{74+i*150}" y="73" text-anchor="middle" class="label">{esc(x[18:36]).upper()}</text>' for i,x in enumerate(labels))
 lines=''.join(f'<line x1="{133+i*150}" y1="63" x2="{165+i*150}" y2="63" stroke="#01dc82" stroke-width="2" marker-end="url(#a)"/>' for i in range(len(labels)-1))
 return f'<div class="diagram"><svg viewBox="0 0 {max(460,len(labels)*150)} 126" role="img" aria-label="{esc(title)} signal map"><defs><marker id="a" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0L6 3 0 6z" fill="#01dc82"/></marker></defs><text x="15" y="22" class="label">SIGNAL MAP</text>{lines}{boxes}</svg></div>'
def report(l):
 items=''.join(f'''<article class="item"><span class="badge">{esc(i['type'])}</span><h3><a href="{esc(i['url'])}">{esc(i['title'])}</a></h3><div class="facts">UPDATED {esc(i['date'])} · PRIMARY SOURCE</div><p><span class="key">What:</span> {esc(i['what'])}</p><p><span class="key">Why now:</span> {esc(i['why'])}</p><p><span class="key">Buildn/client use:</span> {esc(i['use'])}</p><p><span class="key">Caveat:</span> {esc(i['caveat'])}</p><p><span class="key">Next move:</span> {esc(i['action'])}</p></article>''' for i in l['items'])
 labels=['Observe','Control','Review']
 matrix=''.join(f'<tr><td>{esc(x)}</td><td>Primary</td><td>Adapt</td><td>Review</td><td>Try</td></tr>' for x in ['Control surface','Client delivery','Agent workflow'])
 sources=''.join(f'<li><a href="{esc(i["url"])}">{esc(i["title"])}</a></li>' for i in l['items'])
 acts=''.join(f'<li><strong>{esc(i["action"])}</strong></li>' for i in l['items'])
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily Ingest Dossier — {esc(l['title'])} — {DATE}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">{CSS}</head><body><main><header><div class="wordmark">{mark()}<span>Buildn</span></div><h1>Daily Ingest Dossier — {esc(l['title'])}</h1><div class="date">{DATE} · ADAPTIVE DISCOVERY</div><p>{esc(l['readout'])}</p></header><section><article class="card"><h2>Signal map</h2>{diagram(l['title'],labels)}<div class="callout">{esc(l['rationale'])}</div></article><article class="card"><h2>Selected dossiers</h2>{items}</article><article class="card"><h2>Use-case matrix</h2><table class="matrix"><thead><tr><th>Theme</th><th>Buildn OS</th><th>Client work</th><th>Agent workflows</th><th>Personal leverage</th></tr></thead><tbody>{matrix}</tbody></table></article><article class="card"><h2>Top actions</h2><ol class="actions">{acts}</ol></article><article class="card"><h2>Source trail</h2><ul class="sources">{sources}</ul></article></section></main></body></html>'''

ledger={'date':DATE,'generated_at':datetime.now(timezone.utc).isoformat(),'editorial_thesis':'The strongest fresh signal is operational: constrain agent spend, bridge identity at MCP boundaries, retire publisher super-credentials, and refresh evaluation tasks from living repositories.','topic_groups':[]}
for lane in lanes:
 ledger['topic_groups'].append({'slug':lane['slug'],'title':lane['title'],'selection_rationale':lane['rationale'],'sources':[{'title':i['title'],'url':i['url'],'source_type':i['type'],'published_or_updated':i['date'],'why_selected':i['why'],'usefulness':i['use']} for i in lane['items']]})
 (ART/f'daily-ingest-{lane["slug"]}-{STAMP}.html').write_text(report(lane))
(ART/f'daily-ingest-{STAMP}.json').write_text(json.dumps(ledger,indent=2))
# substantive overview; publisher preserves this at the canonical dated index
cards=''.join(f'<article class="card"><span class="badge">{esc(l["slug"].replace("-"," "))}</span><h2>{esc(l["title"])}</h2><p>{esc(l["rationale"])}</p><p><a href="{esc("%s.html" % l["slug"])}">Open lane dossier →</a></p></article>' for l in lanes)
top=''.join(f'<li><strong>{esc(i["title"])}:</strong> {esc(i["action"])}</li>' for l in lanes for i in l['items'][:1])
overview=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily Ingest Dossier — Overview — {DATE}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">{CSS}</head><body><main><header><div class="wordmark">{mark()}<span>Buildn</span></div><h1>Daily Ingest Dossier</h1><div class="date">{DATE} · FOUR FRESH LANES</div><p>Make agent operations deliberate: enforce spend at the right scope, bridge identity rather than bypass it, replace publisher super-credentials, and make repository history feed a living evaluation corpus.</p></header><article class="card"><h2>Editorial thesis</h2>{diagram('Daily operating loop',['Bound','Bridge','Publish','Evaluate'])}<p>Today deliberately avoids repeating general coding-agent and AI-marketing coverage. The one adjacent lane—agent economics—has a material update: hard scoped budgets and route-level logs.</p></article><section class="grid">{cards}</section><article class="card"><h2>All-lanes top actions</h2><ol class="actions">{top}</ol></article></main></body></html>'''
(ART/f'daily-ingest-overview-{STAMP}.html').write_text(overview)
print('generated',len(lanes),'lanes')
