from pathlib import Path
from datetime import datetime, timezone
import html, json

DATE='2026-07-25'; STAMP='20260725'
OUT=Path('/root/Projects/artifact-library/artifacts/daily-ingest'); OUT.mkdir(parents=True,exist_ok=True)
lanes=[
 {'slug':'frontier-agent-runtime','title':'Frontier Agent Runtime','rationale':'A new long-context flagship arrived with an immediate API migration edge and a managed coding surface; this is a material update, not a repeat of prior MCP or delivery coverage.',
  'readout':'The useful signal is not a benchmark headline. Opus 5 combines a 1M-token context, effort controls, and a production coding surface, while retiring an older fast-mode path the same day. Treat it as a workload-routing experiment with explicit cost and acceptance gates.',
  'items':[
   ('Introducing Claude Opus 5','https://www.anthropic.com/news/claude-opus-5','product','2026-07-24','Anthropic released Opus 5 as a flagship for long-running agents, emphasizing verification, iteration, coding, automation, and adjustable effort.','Use it to test difficult Buildn/client tasks where a self-checking agent could replace repeated human re-prompting: migrations, debugging, research synthesis, and browser verification.','Vendor benchmarks and early-access accounts are directional, not proof for local workloads.','Define one hard task, a pass/fail rubric, a cost cap, and a control model before a trial.'),
   ('Claude Opus 5 Now Available in GitHub Copilot','https://github.blog/changelog/2026-07-24-claude-opus-5-is-now-available-in-github-copilot/','release','2026-07-24','GitHub is gradually exposing Opus 5 across Copilot surfaces for Pro+, Max, Business, and Enterprise; managed plans require an admin policy toggle.','Run the same bounded code task through a familiar Copilot surface before changing any agent harness or developer workflow.','Cybersecurity-adjacent prompts can be blocked; plan a model fallback rather than assuming uniform tool behavior.','Enable it for a small pilot group and compare merged, tested outcomes—not chat satisfaction.'),
   ('Claude Platform release notes — July 24','https://platform.claude.com/docs/en/release-notes/overview','docs','2026-07-24','The API release adds claude-opus-5 with 1M context and effort tiers, allows mid-conversation tool changes in beta, and removes Opus 4.7 fast mode.','Audit direct API callers for speed=fast, then use effort as a deliberate quality/cost dial in a test harness.','At xhigh and max, thinking cannot be disabled; workloads must accept that behavior and cost profile.','Search production configuration for claude-opus-4-7 plus speed=fast today.'),
  ]},
 {'slug':'agent-knowledge-trust','title':'Agent Knowledge + Trust','rationale':'This deliberately rotates toward an under-covered data-contract lane: agents need inspectable provenance and authorization boundaries before they can safely act on operational knowledge.',
  'readout':'Knowledge is moving from prose a model happens to retrieve toward typed, inspectable context. The practical design is a bundle with provenance, verification, freshness, and lifecycle signals—then a least-privilege action interface behind it.',
  'items':[
   ('OKF v0.2 adds trust signals','https://cloud.google.com/blog/products/data-analytics/okf-v0-2-adds-trust-signals/','blog','2026-07-24','Google’s Open Knowledge Format v0.2 adds optional provenance, generated/verified, stale_after, status, and attestation vocabulary to Markdown/YAML knowledge bundles.','Create a small Buildn project-context bundle for one client: canonical metrics, runbooks, ownership, source links, and a re-verification date.','The format records signals rather than enforcing policy; consumers still need rules for what they may trust or execute.','Prototype three files: a metric, a runbook, and a client constraint with stale_after dates.'),
   ('Open Knowledge Format reference implementation','https://github.com/GoogleCloudPlatform/knowledge-catalog/tree/main/okf','repo','2026-07-24','The public reference repository provides the concrete spec, samples, and tooling context behind OKF rather than leaving the trust model as a blog concept.','Use it to keep agent-readable context portable across tools instead of embedding key operating facts in a single vendor workspace.','A reference implementation is not a substitute for source-of-truth ownership or access control.','Fork nothing yet; inspect the sample bundle and map it to one existing project folder.'),
   ('ORDS 26.2 MCP support for agentic database access','https://www.oracle.com/tools/ords/ords-changelog.html','release','2026-07-01','Oracle REST Data Services 26.2 can act as an MCP server: authorized agents can list databases, inspect schema metadata, and run SQL/PLSQL under granted privileges.','The tool split is a useful pattern for client data work: discover, inspect, then act—each bounded by an existing identity and role.','SQL execution is high authority; OAuth compliance does not make broad database credentials safe for agents.','Write a three-tool policy for any database agent: read metadata, parameterized read queries, and separately approved writes.'),
  ]},
 {'slug':'agentic-marketplaces-and-transparency','title':'Agentic Marketplaces + Transparency','rationale':'Customer-facing agents and AI-generated media are becoming operationally visible. This lane connects the action surface, the evidence surface, and a realistic discovery workflow for client work.',
  'readout':'Agents are now reaching customers through search, calls, and content. The operating question is no longer whether to automate discovery; it is how to disclose synthetic material, verify actions, and use real demand evidence before building a workflow.',
  'items':[
   ('Ask Google to call local businesses for you','https://blog.google/products-and-platforms/products/shopping/how-to-agentic-calling-let-google-call/','product update','2026-07-24','Google updated its U.S. agentic-calling guidance: Search or AI Mode can gather local stock and discount information, call relevant businesses, then send a summary by text or email.','For local-service clients, use this as a discovery cue: map which inventory, availability, and FAQ answers are structured enough to survive agent-mediated shopping.','Availability is U.S.-specific and Google controls the interaction; it is not an API for a custom client agent.','Pick one local-client category and audit whether stock, hours, pricing, and booking data agree across every public channel.'),
   ('Google signs EU AI Act Transparency Code of Practice','https://blog.google/company-news/outreach-and-initiatives/public-policy/eu-ai-act-transparency-code-of-practice/','policy','2026-07-24','Google signed the EU code on transparency of AI-generated content and points to C2PA and SynthID as interoperable provenance/watermarking mechanisms.','Add a client-content delivery field for origin, editing method, approval owner, and retained source assets—especially for generated visual or audio work.','A watermark or label supports transparency but does not establish factual accuracy, copyright clearance, or audience comprehension.','Add C2PA/SynthID compatibility to the next AI-media vendor evaluation.'),
   ('Ask Claude about the Anthropic Economic Index','https://www.anthropic.com/news/anthropic-economic-index-connector','product','2026-07-22','Anthropic added a Claude connector that lets users query its Economic Index data and inspect the underlying data and limitations in conversation.','Use it as a hypothesis generator for client discovery: ask where AI usage is concentrated in an industry, then validate with customer interviews and first-party analytics.','It measures Claude usage patterns, not the full labor market or a client’s buying intent.','Run five industry questions for one target vertical and save only claims linked to underlying data.'),
   ('Google Search I/O 2026: AI agents and more','https://blog.google/products-and-platforms/products/search/search-io-2026/','product','2026-05-19','Google outlined AI Mode search agents, agentic booking, multimodal query input, and information agents that monitor needs over time.','Design client pages so an agent can recover the same decision facts a person needs: service scope, location, price basis, availability, proof, and a direct action route.','Most features were announced as staged rollouts; do not promise availability or traffic impact without checking the client’s market.','Audit one conversion page for answerable, consistent decision data before adding more AI-generated copy.'),
  ]}
]

def e(x): return html.escape(str(x),quote=True)
CSS='''<style>:root{--brand:#01dc82;--deep:#033330;--lime:#cfe66a;--red:#b3261e;--amber:#9a6700;--ink:#0f172a;--muted:#475569;--line:#e2e8f0;--bg:#fafaf9;--card:#fff;--serif:"Newsreader",Georgia,serif;--sans:"Plus Jakarta Sans",system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:var(--sans);line-height:1.55}main{max-width:68rem;margin:auto;padding:3rem 1.5rem 5rem}header{margin-bottom:2rem}.wordmark{display:flex;align-items:center;gap:.55rem;font-weight:700;color:var(--deep)}h1,h2,h3{font-family:var(--serif);color:var(--deep)}h1{font-size:2.35rem;line-height:1.1;margin:.8rem 0 .4rem}h2{font-size:1.45rem;margin:0 0 .45rem}p{margin:.4rem 0 1rem}.date,.facts{font:.78rem ui-monospace,monospace;color:var(--muted)}.card{background:var(--card);border:1px solid var(--line);border-radius:.8rem;padding:1.35rem;margin:1.15rem 0}.badges{display:flex;gap:.45rem;flex-wrap:wrap;margin-bottom:.75rem}.badge{font-size:.68rem;text-transform:uppercase;letter-spacing:.07em;font-weight:700;padding:.16rem .48rem;border-radius:.35rem;background:#e2e8f0;color:#334155}.good{background:#dcfce7;color:#166534}.warn{background:#fef3c7;color:#854d0e}.diagram{margin:1rem 0;border:1px solid var(--line);border-radius:.55rem;padding:.8rem;background:#fff}.diagram svg{display:block;width:100%;height:auto}.label{font:600 11px var(--sans);letter-spacing:.08em;fill:#475569}.grid{display:grid;grid-template-columns:1fr 1fr;gap:.8rem}.fact{background:#f8fafc;border:1px solid var(--line);border-radius:.5rem;padding:.75rem;font-size:.9rem}.callout{border-left:3px solid var(--amber);background:#fffbeb;color:#713f12;padding:.6rem .8rem;border-radius:.25rem;font-size:.9rem}a{color:#087d54}table{border-collapse:collapse;width:100%;font-size:.85rem}th,td{border:1px solid var(--line);padding:.55rem;text-align:left}th{background:#f8fafc;color:var(--deep)}.top{border-color:#9ee8ca;background:#f4fff9}@media(max-width:620px){.grid{grid-template-columns:1fr}h1{font-size:1.9rem}}</style>'''
LOGO='''<div class="wordmark"><svg viewBox="0 0 40 40" width="23" aria-hidden="true"><path d="M2 38 6 10 12 2h25l-4 26-7 8Z" fill="#01dc82"/><path d="M15 9h15l-2 12H13Z" fill="#033330"/></svg><span>Buildn</span></div>'''
def head(title): return f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily Ingest Dossier — {e(title)} — {DATE}</title><meta name="lib:group" content="report"><meta name="lib:date" content="{DATE}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">{CSS}</head><body><main><header>{LOGO}<h1>Daily Ingest Dossier — {e(title)}</h1><div class="date">{DATE} · Adaptive research brief</div>'
def report(lane):
 items=lane['items']; w=max(720,len(items)*220); nodes=''.join(f'<g transform="translate({20+i*220},55)"><rect width="184" height="72" rx="8" fill="#f8fafc" stroke="#cbd5e1"/><text x="92" y="29" text-anchor="middle" class="label">{e(x[0][:23])}</text><text x="92" y="49" text-anchor="middle" class="label">{e(x[3])}</text></g>' for i,x in enumerate(items))
 svg=f'<div class="diagram"><svg viewBox="0 0 {w} 175" role="img" aria-label="Signal map"><path d="M28 28H{w-28}" stroke="#01dc82" stroke-width="3"/><text x="20" y="18" class="label">TODAY’S SIGNALS</text>{nodes}<path d="M28 145H{w-28}" stroke="#cbd5e1" stroke-dasharray="5 5"/><text x="20" y="166" class="label">EVIDENCE → BOUNDED PILOT → OPERATING RULE</text></svg></div>'
 out=head(lane['title'])+f'<p>{e(lane["readout"])}</p></header><section><article class="card"><h2>Signal map</h2><div class="badges"><span class="badge good">fresh signal</span><span class="badge">coverage gap</span></div>{svg}<div class="callout"><strong>Why this lane:</strong> {e(lane["rationale"])}</div></article>'
 for n,x in enumerate(items,1):
  title,url,typ,pub,what,use,caveat,action=x
  out+=f'<article class="card"><div class="badges"><span class="badge good">{e(typ)}</span><span class="badge">{e(pub)}</span></div><h2>{n}. <a href="{e(url)}">{e(title)}</a></h2><div class="grid"><div class="fact"><strong>What it is</strong><br>{e(what)}</div><div class="fact"><strong>Buildn / client use</strong><br>{e(use)}</div></div><p><strong>Why useful now:</strong> {e(lane["rationale"])}</p><div class="callout"><strong>Caveat:</strong> {e(caveat)}</div><p><strong>Follow-up action:</strong> {e(action)}</p></article>'
 out+='<article class="card"><h2>Use-case matrix</h2><table><thead><tr><th>Theme</th><th>Buildn OS</th><th>Client work</th><th>Agent workflows</th><th>Personal leverage</th></tr></thead><tbody><tr><td>Evaluate</td><td>Sandbox first</td><td>Offer a bounded pilot</td><td>Set an acceptance test</td><td>Save a repeatable checklist</td></tr><tr><td>Operate</td><td>Scope authority</td><td>Keep named ownership</td><td>Log evidence and actions</td><td>Prefer reversible changes</td></tr></tbody></table></article><article class="card top"><h2>Top actions</h2><ol>'+''.join(f'<li><a href="{e(x[1])}">{e(x[0])}</a> — {e(x[7])}</li>' for x in items[:3])+'</ol></article><article class="card"><h2>Source trail</h2><ul>'+''.join(f'<li><a href="{e(x[1])}">{e(x[0])}</a> <span class="date">({e(x[2])}, {e(x[3])})</span></li>' for x in items)+'</ul></article></section></main></body></html>'
 return out
thesis='The fresh advantage is not more autonomous behavior alone: it is a verifiable path from trusted context, through bounded action, to transparent customer-facing evidence.'
ledger={'date':DATE,'generated_at':datetime.now(timezone.utc).isoformat(),'editorial_thesis':thesis,'topic_groups':[]}
for lane in lanes:
 ledger['topic_groups'].append({'slug':lane['slug'],'title':lane['title'],'selection_rationale':lane['rationale'],'sources':[{'title':x[0],'url':x[1],'source_type':x[2],'published_or_updated':x[3],'why_selected':x[4],'usefulness':x[5]} for x in lane['items']]})
 (OUT/f'daily-ingest-{lane["slug"]}-{STAMP}.html').write_text(report(lane))
(OUT/f'daily-ingest-{STAMP}.json').write_text(json.dumps(ledger,indent=2))
links=''.join(f'<li><a href="{e(l["slug"])}.html">{e(l["title"])}</a> — {e(l["rationale"])}</li>' for l in lanes)
overview=head('Overview')+f'<p>{e(thesis)}</p></header><section><article class="card top"><h2>Editorial thesis</h2><p>{e(thesis)}</p></article><article class="card"><h2>Selected lanes</h2><ul>{links}</ul></article><article class="card"><h2>All-lanes top three</h2><ol><li><a href="frontier-agent-runtime.html">Opus 5 API migration audit</a> — find retiring fast-mode calls before they become production errors.</li><li><a href="agent-knowledge-trust.html">OKF trust signals</a> — create a portable, expiring source-of-truth bundle for one active project.</li><li><a href="agentic-marketplaces-and-transparency.html">Agentic-marketplace readiness audit</a> — make customer decision facts consistent before agents become another discovery path.</li></ol></article><article class="card"><h2>Reports</h2><div class="grid">'+''.join(f'<div class="fact"><a href="{e(l["slug"])}.html"><strong>{e(l["title"])}</strong></a><br>{e(l["readout"])}</div>' for l in lanes)+'</div></article></section></main></body></html>'
(OUT/f'daily-ingest-overview-{STAMP}.html').write_text(overview)
coverage_path=Path('/root/Projects/daily-ingest-pages/topic-coverage.json'); coverage=json.loads(coverage_path.read_text()) if coverage_path.exists() else {'schema_version':1,'rolling_theme_summary':{},'item_history':[],'runs':[]}; summary=coverage.setdefault('rolling_theme_summary',{})
for lane in lanes:
 s=summary.setdefault(lane['slug'],{'title':lane['title'],'times_covered':0,'last_covered':None}); s['title']=lane['title']; s['times_covered']=int(s.get('times_covered',0))+1; s['last_covered']=DATE
 for x in lane['items']: coverage.setdefault('item_history',[]).append({'date':DATE,'lane':lane['slug'],'title':x[0],'url':x[1],'source_type':x[2],'selection_rationale':x[4]})
coverage['item_history']=[i for i in coverage['item_history'] if i.get('date','')>='2026-06-10']
run={'date':DATE,'selected_lanes':[{'slug':l['slug'],'title':l['title'],'selection_rationale':l['rationale']} for l in lanes],'editorial_thesis':thesis}
coverage['runs']=[r for r in coverage.setdefault('runs',[]) if r.get('date')!=DATE]+[run]; coverage['last_run']=run; coverage['last_editorial_thesis']=thesis; coverage['updated_at']=ledger['generated_at']; coverage_path.write_text(json.dumps(coverage,indent=2))
