from pathlib import Path
from datetime import datetime, timezone
import html, json

DATE='20260817'; ISO='2026-08-17'
OUT=Path('/root/Projects/artifact-library/artifacts/daily-ingest')
OUT.mkdir(parents=True, exist_ok=True)

CSS='''
:root{--brand:#01dc82;--deep:#033330;--lime:#cfe66a;--red:#b3261e;--amber:#9a6700;--ink:#0f172a;--muted:#475569;--line:#e2e8f0;--bg:#fafaf9;--card:#fff;--serif:"Newsreader",Georgia,serif;--sans:"Plus Jakarta Sans",ui-sans-serif,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:var(--sans);line-height:1.55}main{max-width:68rem;margin:0 auto;padding:3rem 1.5rem}header{display:flex;flex-direction:column;gap:1rem;margin-bottom:2.4rem}.wordmark{display:flex;align-items:center;gap:.6rem;font-weight:700;color:var(--deep)}h1,h2{font-family:var(--serif);color:var(--deep);font-weight:600}h1{font-size:2.35rem;line-height:1.05;margin:0}h2{font-size:1.35rem;margin:0 0 .5rem}h3{font-size:.7rem;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);margin:1.1rem 0 .35rem}.dek{max-width:58rem;color:var(--muted);font-size:1rem}.card{background:var(--card);border:1px solid var(--line);border-radius:.75rem;padding:1.35rem;margin:1rem 0}.badges{display:flex;flex-wrap:wrap;gap:.45rem;margin:.25rem 0 .8rem}.badge{font-size:.67rem;text-transform:uppercase;letter-spacing:.06em;font-weight:700;padding:.15rem .5rem;border-radius:.35rem;background:#f1f5f9;color:var(--muted)}.good{background:#dcfce7;color:#166534}.warn{background:#fef3c7;color:var(--amber)}.spec{background:#e2e8f0;color:#334155}.facts{font-family:ui-monospace,monospace;font-size:.78rem;color:var(--muted);list-style:none;padding:0;margin:.4rem 0}.facts li{padding:.12rem 0}.diagram{border:1px solid var(--line);border-radius:.5rem;background:#fff;padding:1rem;margin:1rem 0}.diagram svg{display:block;max-width:100%;height:auto}.label{font-size:11px;text-transform:uppercase;letter-spacing:.08em;fill:var(--muted)}.wins{margin:.5rem 0 0;padding-left:1.1rem}.wins li{margin:.15rem 0}.callout{border-left:3px solid var(--amber);background:#fffbeb;color:#713f12;padding:.6rem .9rem;border-radius:.25rem;font-size:.88rem}.source{color:#006b4f;font-size:.85rem;word-break:break-word}.matrix{width:100%;border-collapse:collapse;font-size:.82rem}.matrix th,.matrix td{text-align:left;border-bottom:1px solid var(--line);padding:.55rem .4rem;vertical-align:top}.matrix th{color:var(--deep);font-size:.7rem;text-transform:uppercase;letter-spacing:.06em}.actions{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:.7rem}.action{border-left:3px solid var(--brand);background:#f0fdf7;padding:.7rem .85rem}.small{font-size:.82rem;color:var(--muted)}a{color:#006b4f}.topline{border:2px solid var(--brand);background:#f0fdf7}.legend{font-size:.78rem;color:var(--muted)}
'''
LOGO='''<svg viewBox="0 0 164 195" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" width="22"><path d="M117 194.5H0L12 73C17.47 66.63 21.30 65.46 28.5 64.5L34.5 0H151.5C158.44 4.40 161.28 7.18 163.5 13L153 119.5C148.80 127.15 144.97 129.55 135.5 130.5L131 184.5C127.71 190.35 125.13 192.98 117 194.5Z" fill="#01dc82"/><path d="M64 33L61 64.5H93.5L91 97H123L127.5 46.5C125.53 37.94 122.01 35.19 112.5 33H64Z" fill="#033330"/><path d="M37 147.5L41.5 98H74.5L71.5 129.5L104 130.5L100.5 162H49.5C41.82 159.35 39.68 155.53 37 147.5Z" fill="#033330"/></svg>'''

def esc(x): return html.escape(str(x), quote=True)
def signal(items):
    cols=['#01dc82','#cfe66a','#ffcf70','#b3261e','#94a3b8']
    circles=[]
    for i,it in enumerate(items):
        x=34+(i%5)*116; y=38+(i//5)*54
        circles.append(f'<circle cx="{x}" cy="{y}" r="15" fill="{cols[i%5]}"/><text x="{x}" y="{y+4}" text-anchor="middle" class="label">{i+1}</text>')
    return '<div class="diagram"><svg viewBox="0 0 620 150" role="img" aria-label="Signal map of five selected items"><path d="M34 38 H586 M34 92 H586" stroke="#e2e8f0" stroke-width="2"/><text x="8" y="42" class="label">signal</text><text x="8" y="96" class="label">action</text>'+''.join(circles)+'</svg><div class="legend">1–5 follow the dossier cards below; green = ready to try, lime/amber = evaluate, red = control boundary.</div></div>'

def report(slug,title,thesis,items):
    cards=[]
    for i,it in enumerate(items,1):
        cards.append(f'''<article class="card" id="item-{i}"><h2>{esc(it['title'])}</h2><div class="badges"><span class="badge {it.get('status','good')}">{esc(it.get('status_label','Fresh signal'))}</span><span class="badge spec">{esc(it['type'])}</span></div><ul class="facts"><li>Updated: {esc(it.get('date','2026-08'))}</li><li>Best fit: {esc(it['fit'])}</li></ul><h3>What it is</h3><div>{esc(it['what'])}</div><h3>Why it matters</h3><div>{esc(it['why'])}</div><h3>Buildn / client use</h3><div>{esc(it['use'])}</div><h3>Follow-up</h3><div class="callout">{esc(it['action'])}</div><p class="source"><a href="{esc(it['url'])}">Direct source ↗</a></p></article>''')
    rows=''.join(f'<tr><td>{esc(r[0])}</td><td>{esc(r[1])}</td><td>{esc(r[2])}</td><td>{esc(r[3])}</td></tr>' for r in [('Buildn OS','Evidence + permissions','Reviewable agent connectors','Capture one reusable pattern'),('Client work','Scoped implementation','Security or workflow audit','Offer a bounded pilot'),('Agent workflows','Plan → act → verify','Tool policy + traces','Instrument before scaling'),('Personal leverage','Try on a real task','Local/private option where relevant','Timebox the experiment')])
    actions=''.join(f'<div class="action"><strong>{i+1}. {esc(x)}</strong></div>' for i,x in enumerate([it['action'] for it in items[:3]]))
    sources=''.join(f'<li><a href="{esc(it["url"])}">{esc(it["title"])}</a></li>' for it in items)
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily Ingest Dossier — {esc(title)}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,500;6..72,600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><style>{CSS}</style></head><body><main><header><div class="wordmark">{LOGO}<span>Buildn</span></div><div class="small">Daily Ingest Dossier — {esc(title)} · {ISO}</div><h1>{esc(title)}</h1><div class="dek">{esc(thesis)}</div></header><section><article class="card"><h2>Signal map</h2><div class="small">Five fresh items, selected for practical leverage and coverage novelty.</div>{signal(items)}</article>{''.join(cards)}<article class="card"><h2>Use-case matrix</h2><table class="matrix"><thead><tr><th>Surface</th><th>Immediate value</th><th>Design implication</th><th>Next move</th></tr></thead><tbody>{rows}</tbody></table></article><article class="card"><h2>Top actions</h2><div class="actions">{actions}</div></article><article class="card"><h2>Source trail</h2><ol>{sources}</ol></article></section></main></body></html>'''

lanes={
'mcp-security-controls':('MCP Security Controls','The MCP security story moved from inventory to enforceable network policy: detect protocol traffic, expose shadow connections, then narrow access to approved portals. The useful move is to establish visibility before blocking, because local stdio and off-network paths remain outside the same lens.',[
{'title':'Cloudflare detects MCP traffic','type':'blog','date':'2026-08-14','fit':'Agent connectors + egress','what':'Cloudflare Gateway identifies inspected MCP requests using protocol signals such as MCP-Protocol-Version.','why':'Teams can discover shadow MCP without maintaining a brittle domain list, then turn detection into an allow/block policy.','use':'Add an MCP inventory checkpoint to client security reviews and map approved servers to portal-only access.','action':'Run a read-only Gateway log review; classify approved, unknown, and direct MCP destinations before enforcement.','url':'https://blog.cloudflare.com/mcp-security-updates/','status_label':'High leverage'},
{'title':'MCP protocol detection dashboard','type':'release','date':'2026-08-12','fit':'Security operations','what':'Cloudflare documents automatic MCP detection in Gateway and an AI Security dashboard.','why':'A dashboard turns protocol adoption into an observable control-plane surface rather than a developer-by-developer guess.','use':'Use the dashboard as the first artifact in an agent connector onboarding workflow.','action':'Export one week of MCP events and attach owner, destination, identity, and intended purpose.','url':'https://developers.cloudflare.com/changelog/post/2026-08-12-mcp-detection-and-dashboard/','status_label':'Operational'},
{'title':'Detect MCP traffic in Gateway logs','type':'docs','date':'2026-08-14','fit':'Policy implementation','what':'The tutorial shows how to classify MCP traffic and apply DLP and Zero Trust policies.','why':'It provides a concrete bridge from detection to policy, including shadow traffic and portal-mediated traffic.','use':'Turn the tutorial into a client runbook with monitor-only, warn, and block phases.','action':'Prototype a monitor-only rule; do not block until false positives and unmanaged-device gaps are documented.','url':'https://developers.cloudflare.com/cloudflare-one/tutorials/detect-mcp-traffic-gateway-logs/','status_label':'Try now'},
{'title':'Cloudflare Access for Workers','type':'release','date':'2026-08-14','fit':'Private agent services','what':'Cloudflare announced Access capabilities for protecting Workers-based internal services.','why':'Private MCP and agent endpoints need an identity boundary close to the workload, not only a public URL and shared secret.','use':'Evaluate it for a client portal or Buildn-side worker that exposes narrow tools.','action':'Sketch the identity-to-tool matrix before deploying a new connector; include revocation and audit ownership.','url':'https://blog.cloudflare.com/','status_label':'Evaluate'},
{'title':'Certificate Transparency Monitoring GA','type':'release','date':'2026-08-13','fit':'External exposure','what':'Cloudflare made Certificate Transparency Monitoring generally available for spotting certificates issued for monitored domains.','why':'New agent endpoints and temporary environments can create accidental public exposure; certificate signals help catch it early.','use':'Pair CT alerts with a lightweight agent-endpoint inventory for client infrastructure.','action':'Add CT monitoring to the exposure review for any customer-facing agent or MCP hostname.','url':'https://blog.cloudflare.com/certificate-transparency-monitoring-ga','status_label':'Defensive'}]),
'code-context-and-team-graphs':('Code Context + Team Graphs','The next coding-agent advantage is organizational context, not another isolated model. Atlassian’s Code Context connects multi-repo code understanding to the Teamwork Graph, making architecture, ownership, and work history available to the same reasoning loop.',[
{'title':'Atlassian Code Context','type':'product','date':'2026-08-13','fit':'Multi-repo client work','what':'An AI context engine brings codebase understanding into the Teamwork Graph so agents can reason across code and organizational context.','why':'Agents fail when they see a repository but not ownership, linked work, conventions, or system boundaries.','use':'Use the concept as a reference architecture for Buildn project context: repos, issues, decisions, and evidence in one graph.','action':'Choose one client project and draw the minimum context graph an agent needs before changing code.','url':'https://www.atlassian.com/blog/development/code-context','status_label':'Fresh'},
{'title':'Teamwork Graph as context substrate','type':'docs','date':'2026-08','fit':'Knowledge architecture','what':'Atlassian positions the Teamwork Graph as a connected representation of work, people, systems, and artifacts.','why':'The practical lesson is to model relationships explicitly instead of stuffing more text into prompts.','use':'Translate project knowledge into typed links: owns, depends on, changed by, verified by.','action':'Audit one Buildn dossier for missing relationship fields rather than adding another narrative paragraph.','url':'https://developer.atlassian.com/platform/teamwork-graph/what-is-teamwork-graph/','status_label':'Design cue'},
{'title':'Codebase-level context improves agent accuracy','type':'analysis','date':'2026-08-13','fit':'Evaluation design','what':'Atlassian’s announcement claims a large accuracy lift from richer codebase context.','why':'Even if the exact lift is workload-specific, it makes context quality an eval variable worth measuring.','use':'Benchmark the same task with repository-only versus repository-plus-ownership context.','action':'Create a five-task eval set and record correctness, tokens, elapsed time, and human repair.','url':'https://marketchameleon.com/articles/b/2026/8/13/atlassian-code-context-improves-coding-agent-accuracy','status_label':'Measure'},
{'title':'GitHub Copilot Agent Plugins 1.0','type':'spec','date':'2026-08-11','fit':'Portable context tools','what':'GitHub packages skills and tools for use across VS Code, Copilot CLI, the SDK, and the Copilot app.','why':'Portable plugins make context retrieval and project conventions reusable across agent surfaces.','use':'Package a Buildn evidence/context lookup as a narrow plugin contract rather than a platform-specific prompt.','action':'Write the plugin interface around inputs, evidence returned, and authorization—not around one UI.','url':'https://developers.googleblog.com/agent-plugins-package-your-skills-tools-and-more','status_label':'Portable'},
{'title':'Linear agent context and release updates','type':'release','date':'2026-08-13','fit':'Delivery collaboration','what':'Linear’s team initiatives update includes agent progress fixes, release updates, and managed MCP authorization.','why':'Context becomes useful when it is attached to current delivery state and accountable access.','use':'Keep agent output beside milestone and release state rather than in a detached chat archive.','action':'Add evidence, owner, branch, and release fields to one automated delivery record.','url':'https://linear.app/changelog/2026-08-13-team-initiatives','status_label':'Workflow'}]),
'cyber-defense-model-access':('Cyber Defense Model Access','Frontier cybersecurity models are moving into governed cloud environments. The strategic signal is not “use a stronger model”; it is specialized capability plus enrollment, monitoring, regionality, and explicit authorization for high-risk tasks.',[
{'title':'OpenAI Daybreak on Amazon Bedrock','type':'release','date':'2026-08-13','fit':'Authorized cyber defense','what':'Daybreak Red and Blue are available to eligible customers on Bedrock for defensive security workflows.','why':'Security teams can keep inference inside an existing cloud control plane while accessing specialized vulnerability and response capabilities.','use':'Offer a bounded client pilot for code vulnerability discovery with strict scope, logging, and human approval.','action':'Define the authorized task boundary first; require evidence that every finding maps to a tested fix.','url':'https://aws.amazon.com/about-aws/whats-new/2026/08/openai-daybreak-red-and-blue-on-amazon-bedrock/','status_label':'High signal'},
{'title':'Daybreak Red: GPT-5.6 Cyber','type':'model card','date':'2026-08','fit':'Vulnerability research','what':'The Bedrock model card describes the GPT-5.6 Cyber endpoint and access requirements.','why':'Model cards make deployment constraints, endpoint location, and programmatic access explicit enough to evaluate responsibly.','use':'Use model-card fields as the minimum record for any production model trial.','action':'Capture region, model ID, enrollment status, data-retention terms, and permitted task class.','url':'https://docs.aws.amazon.com/bedrock/latest/userguide/model-card-openai-gpt-56-cyber.html','status_label':'Concrete'},
{'title':'OpenAI’s AWS Daybreak overview','type':'primary source','date':'2026-08-13','fit':'Strategy + procurement','what':'OpenAI describes Blue as general defensive access and Red as specialized authorized cyber capability.','why':'The two-tier posture is a useful pattern for matching capability to risk rather than giving every operator the strongest tool.','use':'Build a client-facing capability ladder: triage, detection engineering, validation, then restricted research.','action':'Make capability escalation require identity, ticket, scope, and review evidence.','url':'https://openai.com/index/daybreak-models-are-now-available-on-aws/','status_label':'Governance'},
{'title':'AWS Daybreak security architecture','type':'architecture','date':'2026-08-13','fit':'Private deployment','what':'AWS states that inference is encrypted, data is not used for training, and zero-data-retention can be requested.','why':'Procurement questions become architecture questions: who can access prompts, where inference runs, and what is retained.','use':'Turn these claims into a verification checklist for client security and legal review.','action':'Ask for written retention and operator-access commitments before uploading proprietary code.','url':'https://aws.amazon.com/blogs/machine-learning/accelerate-cyber-defense-with-openai-and-aws-daybreak-red-daybreak-blue-now-available-to-eligible-customers-on-amazon-bedrock/','status_label':'Verify'},
{'title':'Gemini 3.7 Flash','type':'model release','date':'2026-08-13','fit':'Cost/latency baseline','what':'Google positions Gemini 3.7 Flash as a workhorse model for coding and agents.','why':'A practical cyber workflow needs a cheaper baseline for triage before escalating to a specialized model.','use':'Compare it against a cyber-specialized model on redacted findings, not only generic benchmarks.','action':'Run the same ten sanitized alerts through triage and escalation paths; measure repair quality and cost.','url':'https://blog.google/innovation-and-ai/models-and-research/gemini-models/introducing-gemini-3-7-flash/','status_label':'Baseline'}]),
'personal-knowledge-workspaces':('Personal Knowledge Workspaces','Knowledge tools are converging on project-scoped context: notebooks, chats, and research sources become a durable workspace rather than a transient conversation. The leverage comes from explicit boundaries and source traceability, not from invisible memory.',[
{'title':'Notebooks in Gemini','type':'product','date':'2026-08','fit':'Project research','what':'Google’s Gemini notebooks organize chats and projects and connect with NotebookLM as a research partner.','why':'A bounded notebook is a more inspectable memory unit than one global assistant history.','use':'Use project-scoped notebooks for client discovery, with source links and a clear archive boundary.','action':'Create one notebook for a live project and require every conclusion to retain its source trail.','url':'https://blog.google/innovation-and-ai/products/gemini-app/notebooks-gemini-notebooklm/','status_label':'Try now'},
{'title':'NotebookLM research workflow','type':'product','date':'2026-08','fit':'Source-grounded synthesis','what':'NotebookLM is positioned as a research partner alongside Gemini notebooks for working from supplied sources.','why':'The useful primitive is source-bounded synthesis: the workspace knows what evidence it is allowed to use.','use':'Mirror this in Buildn reports by keeping source ledger, findings, and recommendations together.','action':'Test a report workflow where unsupported claims are rejected or visibly marked.','url':'https://notebooklm.google/','status_label':'Grounded'},
{'title':'Gemini 3.7 Flash for agentic work','type':'model release','date':'2026-08-13','fit':'Fast knowledge operations','what':'Google describes Flash as a workhorse model for coding and agent workloads.','why':'Fast models are useful for indexing, tagging, and first-pass extraction before slower editorial review.','use':'Use a fast model for metadata normalization, never as the sole source of truth.','action':'Measure extraction accuracy on 50 notes and route ambiguous records to human review.','url':'https://blog.google/innovation-and-ai/models-and-research/gemini-models/introducing-gemini-3-7-flash/','status_label':'Pipeline'},
{'title':'Obsidian LiveSync releases','type':'open source','date':'2026-08','fit':'Local-first continuity','what':'Obsidian LiveSync provides a release stream for synchronizing a local knowledge base across devices.','why':'Local-first storage keeps the archive portable and makes the sync boundary explicit.','use':'Evaluate it for a personal research vault where offline access and ownership matter.','action':'Test conflict recovery and encryption assumptions before placing client material in any sync vault.','url':'https://github.com/vrtmrz/obsidian-livesync/releases','status_label':'Local-first'},
{'title':'Google’s AI product announcement index','type':'primary source','date':'2026-08','fit':'Signal tracking','what':'Google’s announcement index groups the current model, agent, search, and productivity releases.','why':'A source index is useful as a discovery surface, but each item still needs primary-page verification and novelty checks.','use':'Use it as one input to a coverage ledger, not as the dossier itself.','action':'Add a source-level freshness check before selecting a lane; reject repeated announcements without material change.','url':'https://blog.google/innovation-and-ai/technology/ai/google-io-2026-all-our-announcements/','status_label':'Discovery'}])
}

for slug,(title,thesis,items) in lanes.items():
    (OUT/f'daily-ingest-{slug}-{DATE}.html').write_text(report(slug,title,thesis,items), encoding='utf-8')

ledger={'date':ISO,'generated_at':datetime.now(timezone.utc).isoformat(),'editorial_thesis':'Today’s strongest fresh signal is practical boundary-setting: secure MCP paths, give agents organizational context, govern specialized cyber models, and keep personal knowledge work source-bounded.','topic_groups':[]}
for slug,(title,thesis,items) in lanes.items():
    ledger['topic_groups'].append({'slug':slug,'title':title,'selection_rationale':thesis,'sources':[{'title':x['title'],'url':x['url'],'source_type':x['type'],'published_or_updated':x.get('date','unknown'),'why_selected':x['why'],'usefulness':x['use']} for x in items]})
(OUT/f'daily-ingest-{DATE}.json').write_text(json.dumps(ledger,indent=2,ensure_ascii=False),encoding='utf-8')

links=''.join(f'<li><a href="{esc(slug)}.html">{esc(title)}</a> — {esc(thesis.split(". ")[0])}.</li>' for slug,(title,thesis,_) in lanes.items())
top=''.join(f'<div class="action"><strong>{i+1}. {esc(x)}</strong></div>' for i,x in enumerate(['Run a monitor-only MCP traffic inventory before blocking unknown paths.','Benchmark repository-only versus graph-enriched coding context on five real tasks.','Design a governed cyber-model pilot with explicit escalation and retention controls.']))
over=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily Ingest Dossier — Overview {ISO}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,500;6..72,600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><style>{CSS}</style></head><body><main><header><div class="wordmark">{LOGO}<span>Buildn</span></div><div class="small">Daily Ingest Dossier · {ISO}</div><h1>Adaptive daily ingest</h1><div class="dek">Today’s dossier favors fresh, practical signal over another generic AI roundup. The common thread is controlled context: secure the connector, enrich the agent’s world model, govern high-risk capability, and preserve evidence in personal knowledge work.</div></header><section><article class="card"><h2>Selected lanes</h2><ul>{links}</ul><p class="small">Selection rotated away from yesterday’s lifecycle, governance, portable-workflow, and identity-collaboration lanes. Sources were chosen for new dates, direct primary pages, and a clear Buildn/client experiment.</p></article><article class="card"><h2>All-lanes top three</h2><div class="actions">{top}</div></article><article class="card"><h2>Editorial readout</h2><div class="diagram"><svg viewBox="0 0 620 125" role="img" aria-label="Context moves from access boundary to evidence"><defs><marker id="a" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#94a3b8"/></marker></defs><rect x="8" y="38" width="130" height="42" rx="6" fill="#f0fdf7" stroke="#01dc82"/><text x="73" y="63" text-anchor="middle" class="label">access boundary</text><line x1="138" y1="59" x2="220" y2="59" stroke="#94a3b8" marker-end="url(#a)"/><rect x="220" y="38" width="130" height="42" rx="6" fill="#fff" stroke="#cbd5e1"/><text x="285" y="63" text-anchor="middle" class="label">useful context</text><line x1="350" y1="59" x2="432" y2="59" stroke="#94a3b8" marker-end="url(#a)"/><rect x="432" y="38" width="174" height="42" rx="6" fill="#fff" stroke="#cfe66a"/><text x="519" y="63" text-anchor="middle" class="label">reviewable evidence</text></svg></div><p>Open the MCP lane for immediate control-plane work; the code-context lane for a Buildn architecture pattern; the cyber lane only with explicit authorization; and the knowledge lane for a source-bounded personal workflow.</p></article><article class="card"><h2>Reports</h2><p>Each lane is a standalone, script-free HTML dossier with a signal map, five selected items, use-case matrix, actions, and direct source trail.</p></article></section></main></body></html>'''
(OUT/f'daily-ingest-overview-{DATE}.html').write_text(over,encoding='utf-8')
print('generated', len(lanes)+2, 'files')
