from pathlib import Path
from datetime import datetime, timezone
import html, json

DATE='2026-08-08'; KEY='20260808'
ART=Path('/root/Projects/artifact-library/artifacts/daily-ingest')
PAGES=Path('/root/Projects/daily-ingest-pages')
ART.mkdir(parents=True, exist_ok=True)

data={
 'date':DATE,
 'generated_at':datetime.now(timezone.utc).isoformat(),
 'editorial_thesis':'The practical shift today is control-plane maturity: measure which agent actually works, isolate where it runs, and make every external integration explicitly admissible and observable.',
 'topic_groups':[
  {'slug':'agent-portfolio-controls','title':'Agent Portfolio Controls','selection_rationale':'Yesterday’s GitHub releases turn agent rollout from a single adoption number into review depth, per-agent activity, and directional spend/output evidence—a fresh operational lane after recent runtime coverage.','sources':[
   {'title':'Copilot code review effort levels are generally available','url':'https://github.blog/changelog/2026-08-07-copilot-code-review-effort-levels-are-generally-available/','source_type':'release','published_or_updated':'2026-08-07','why_selected':'GA effort levels make review depth a deliberate policy choice rather than an invisible model setting.','usefulness':'Map Lite and Balanced review to change risk in a client or Buildn repository.','what':'GitHub Copilot code review now offers GA Lite and Balanced effort levels, configurable per review or as organization defaults.','matters':'Routine documentation edits and cross-service or security-sensitive changes should not consume the same review budget.','use':'Set a default for routine changes; require Balanced on sensitive paths, migrations, and externally exposed code.','caveat':'Review effort is not an acceptance test. Preserve CI, human ownership, and security review for high-consequence changes.','action':'Write a one-page PR risk rubric that assigns Lite, Balanced, or human-only review.'},
   {'title':'Copilot usage metrics API adds agent app activity','url':'https://github.blog/changelog/2026-08-07-copilot-usage-metrics-api-adds-agent-app-activity/','source_type':'API release','published_or_updated':'2026-08-07','why_selected':'It separates recognized third-party agent activity by stable agent identifier in 1- and 28-day reports.','usefulness':'It supplies a practical schema for evaluating a mixed agent fleet rather than relying on anecdotes.','what':'The Copilot usage metrics API adds optional totals_by_3rd_party_agent entries, including agent_id, job starts, and aggregate session counts.','matters':'A shared “agent usage” bucket hides whether a new harness is complementing or displacing the one it was meant to improve.','use':'If a client uses GitHub enterprise controls, join reports on agent_id and compare adoption, cost, cycle time, and accepted output by agent.','caveat':'Unrecognized agents are omitted; job starts are not the same metric as top-level prompts, and activity is not outcome quality.','action':'Add agent_id, accepted PRs, rework rate, and human-review time to a 28-day experiment sheet.'},
   {'title':'Copilot impact dashboard adds a return on investment section','url':'https://github.blog/changelog/2026-08-07-copilot-impact-dashboard-adds-a-return-on-investment-section/','source_type':'product update','published_or_updated':'2026-08-07','why_selected':'It puts actual AI-credit-derived cost beside pull-request output for passive and agent-first adoption cohorts.','usefulness':'Use the framing to start a better client conversation about enablement without treating PR volume as ROI.','what':'GitHub’s impact dashboard adds a potential ROI view with cost per developer, payroll percentage, and pull requests per month across adoption cohorts.','matters':'The release makes the cost/output trade-off visible, while also showing why volume alone must not become the success metric.','use':'Pair dashboard data with defect escapes, reviewer burden, and delivery lead time before choosing an agent rollout path.','caveat':'GitHub labels the figures directional: salary is modeled, costs are estimates, and pull-request volume does not prove value or quality.','action':'Use the dashboard only as one panel in a scorecard with quality and cycle-time guardrails.'}
  ]},
  {'slug':'bounded-agent-execution','title':'Bounded Agent Execution','selection_rationale':'New browser and microVM options are concrete enough to test now, while avoiding a repeat of this week’s runtime/observability lens: the focus here is where untrusted work is allowed to execute.','sources':[
   {'title':'Introducing Kitesurf, an agent-first browser on Browser Run','url':'https://developers.cloudflare.com/changelog/post/2026-08-06-kitesurf/','source_type':'beta release','published_or_updated':'2026-08-06','why_selected':'It offers a stateless browser designed for agent workloads with an opt-in compatibility path through existing Browser Run endpoints.','usefulness':'It is a viable benchmark candidate for bursty screenshot and extraction jobs.','what':'Cloudflare’s Kitesurf is a beta stateless browser on Workers; Cloudflare reports 3–7× lower CPU and memory for common agent screenshots and HTML extraction.','matters':'Browser sessions are expensive and high-risk. Stateless, elastic execution can reduce capacity pressure when tasks are narrow and repeatable.','use':'Benchmark one research or QA job against the existing browser path, keeping credentials, uploads, and destructive interactions out of the trial.','caveat':'Vendor performance figures need workload-specific validation; beta status and browser compatibility differences can surface at the edges.','action':'Run a 20-job screenshot/extraction benchmark with latency, error, and fidelity checks.'},
   {'title':'Vercel AI Gateway and Vercel Sandbox now available on Hermes Agent','url':'https://vercel.com/changelog/vercel-ai-gateway-and-vercel-sandbox-now-available-on-hermes-agent','source_type':'integration release','published_or_updated':'2026-08-07','why_selected':'The integration joins multi-model routing with a configurable microVM command backend in the agent workflow used for this ingest.','usefulness':'It gives a direct path to trial cloud-isolated commands without rebuilding the orchestration layer.','what':'Hermes Agent can use Vercel AI Gateway and switch terminal commands to Vercel Sandbox microVMs, with a workspace rooted in the sandbox.','matters':'Model access and command execution are separate boundaries; treating the latter as a backend makes containment an explicit operating choice.','use':'Prototype a client automation with read-only inputs and an isolated workspace, then promote only reviewed artifacts to the real repository.','caveat':'A sandbox limits execution blast radius but does not remove the need for secret scoping, egress policy, artifact review, or cost controls.','action':'Run one non-production task in a sandbox and document filesystem, network, credential, and promotion boundaries.'},
   {'title':'Give every agent in Herdr its own Vercel Sandbox','url':'https://vercel.com/changelog/give-every-agent-in-herdr-its-own-vercel-sandbox','source_type':'integration release','published_or_updated':'2026-08-07','why_selected':'It shows a practical multi-agent pattern: local orchestration with separate sandboxes, reviewed uploads, conflict checks, and human-confirmed deletion.','usefulness':'Borrow the boundary design even if neither product becomes the production platform.','what':'Herdr can assign terminal agents their own Vercel Sandboxes while retaining local orchestration and review controls around files and deletion.','matters':'Concurrency is safer when agents do not share mutable workspace state by default and transfers have named checkpoints.','use':'For parallel client work, give each agent a disposable branch/workspace and merge only reviewable patches with provenance.','caveat':'Isolation does not solve conflicting requirements or validate output. Human acceptance criteria still need to be explicit.','action':'Adopt per-task worktrees today; add stronger runtime isolation only after the workflow proves valuable.'}
  ]},
  {'slug':'integration-trust-boundaries','title':'Integration Trust Boundaries','selection_rationale':'This lane fills a gap between agent capability and real deployment: current releases expose the three seams that fail first—tool admission, application permissions, and security-event evidence.','sources':[
   {'title':'MCP allowlists in enterprise managed settings','url':'https://github.blog/changelog/2026-08-06-mcp-allowlists-in-enterprise-managed-settings','source_type':'security release','published_or_updated':'2026-08-06','why_selected':'GitHub now provides centrally managed, fail-closed MCP allow/deny policies across Copilot app, CLI, and VS Code.','usefulness':'It is an immediately usable reference for a client MCP admission policy.','what':'Enterprise settings can allow or deny MCP servers by canonicalized remote URL, exact local command/arguments, or name; malformed or unverifiable configurations are blocked.','matters':'Tool discovery turns an integration into effective agent authority. An allowlist makes that authority reviewable before it reaches developer machines.','use':'Maintain a small approved-server inventory; match remote URLs or exact commands, not friendly server names, and specify an owner and renewal date.','caveat':'This is GitHub-specific enforcement. Names are explicitly not a security control, and policy coverage is limited to supported clients.','action':'Inventory every MCP server in use and classify it approved, experimental, blocked, or unknown.'},
   {'title':'Enterprises can now install third-party GitHub Apps','url':'https://github.blog/changelog/2026-08-07-enterprises-can-now-install-third-party-github-apps/','source_type':'platform release','published_or_updated':'2026-08-07','why_selected':'It opens an enterprise-level installation path while preserving an important restriction for the most powerful organization-installation permissions.','usefulness':'It creates a clearer delivery route for Buildn integrations that need enterprise-management scope.','what':'GitHub enterprise owners can install external public GitHub Apps; apps with enterprise organization-installation permissions cannot be installed across enterprise boundaries.','matters':'Enterprise-level distribution is useful, but the permission model must be designed for the blast radius rather than for the easiest onboarding flow.','use':'For any client app, request the smallest permission set, document the installation scope, and avoid cross-enterprise plans if restricted permissions are required.','caveat':'Installing at enterprise scope does not grant organization or repository access by itself; every follow-on permission still needs explicit review.','action':'Create a permission table for the next GitHub App: user, org, repository, enterprise, data read, data write, and exit plan.'},
   {'title':'Audit Log Drains now support Datadog, Splunk, and Panther','url':'https://vercel.com/changelog/audit-log-drains-now-support-datadog-splunk-and-panther','source_type':'observability release','published_or_updated':'2026-08-07','why_selected':'It adds direct audit-event destinations and a migration away from the prior custom SIEM streaming path.','usefulness':'It closes the evidence loop for hosted client delivery where deployment and configuration actions need independent visibility.','what':'Vercel Audit Log Drains now stream team activity events plus audit metadata to Datadog, Splunk, or Panther, alongside HTTPS and S3 destinations.','matters':'A permission boundary cannot be reviewed after an incident if deployment, access, and configuration actions remain trapped in a vendor console.','use':'For Enterprise clients, send audit logs to the existing detection platform and verify retention, alert ownership, and the migration from Custom SIEM Log Streaming.','caveat':'The feature is Enterprise-only; log forwarding is not monitoring until high-signal rules, retention, and response ownership are configured.','action':'Choose three auditable events—access change, production deploy, secret change—and prove they arrive in the team’s response system.'}
  ]}
 ]
}

def e(v): return html.escape(str(v),quote=True)
css='''<style>:root{--brand:#01dc82;--deep:#033330;--lime:#cfe66a;--red:#b3261e;--amber:#9a6700;--ink:#0f172a;--muted:#475569;--line:#e2e8f0;--bg:#fafaf9;--card:#fff;--serif:Newsreader,Georgia,serif;--sans:"Plus Jakarta Sans",ui-sans-serif,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:var(--sans);line-height:1.55}main{max-width:68rem;margin:auto;padding:3rem 1.5rem}header{margin-bottom:2rem}.wordmark{display:flex;align-items:center;gap:.55rem;color:var(--deep);font-weight:700}.wordmark svg{height:24px}h1,h2,h3{font-family:var(--serif);color:var(--deep);line-height:1.15}h1{font-size:2.35rem;margin:.8rem 0 .4rem}h2{font-size:1.45rem;margin:0 0 .5rem}h3{font-size:1.08rem;margin:0}.deck{max-width:55rem;color:var(--muted)}section{display:grid;gap:1.25rem;margin:1.5rem 0}.card{background:var(--card);border:1px solid var(--line);border-radius:.8rem;padding:1.35rem}.badges{display:flex;gap:.45rem;flex-wrap:wrap;margin:.5rem 0 .8rem}.badge{font-size:.69rem;text-transform:uppercase;letter-spacing:.06em;font-weight:700;background:#f1f5f9;color:var(--muted);padding:.16rem .45rem;border-radius:.3rem}.good{background:#dcfce7;color:#166534}.warn{background:#fef3c7;color:var(--amber)}.facts{list-style:none;padding:0;margin:.65rem 0;font:.77rem ui-monospace,monospace;color:var(--muted)}.diagram{border:1px solid var(--line);border-radius:.5rem;padding:.7rem;margin:1rem 0;background:#fff}.diagram svg{display:block;width:100%;height:auto}.label{font:600 11px var(--sans);fill:#475569}.label2{font:700 13px var(--sans);fill:#033330}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:.8rem}.mini{border-top:2px solid var(--brand);padding-top:.5rem}.mini p{margin:.35rem 0}.callout{border-left:3px solid var(--amber);background:#fffbeb;color:#713f12;padding:.6rem .85rem;border-radius:.2rem;font-size:.9rem}.matrix{width:100%;border-collapse:collapse;font-size:.82rem}.matrix th,.matrix td{padding:.5rem;border-bottom:1px solid var(--line);text-align:left}.yes{color:#087f55;font-weight:700}.no{color:#94a3b8}.top{border-color:#b7e7ce}a{color:#087f55;font-weight:600}.hl{background:color-mix(in srgb,var(--lime) 60%,transparent);padding:0 .15em}footer{color:var(--muted);font-size:.78rem;margin-top:2rem}@media(max-width:600px){main{padding:2rem 1rem}h1{font-size:1.9rem}.matrix{font-size:.7rem}}</style>'''
def logo(): return '<svg viewBox="0 0 164 195" width="22" aria-hidden="true"><path d="M117 194H0L12 73c5-7 9-8 17-9L35 0h117c7 4 10 7 12 13l-10 106c-4 8-8 10-18 11l-5 54c-3 6-6 9-14 10Z" fill="#01dc82"/><path d="m64 33-3 31h32l-2 33h32l5-51c-2-8-6-11-15-13H64Zm-27 115 5-50h33l-3 32 32 1-4 31H50c-8-3-10-7-13-14Z" fill="#033330"/></svg>'
def head(title): return f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,500;6..72,600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">{css}</head><body><main>'
def signal(g):
 items=g['sources']; boxes=[]
 for i,s in enumerate(items):
  x=14+i*154; label=e(s['title'][:18]); arrow='' if i==len(items)-1 else f'<path d="M{x+118} 83H{x+143}" stroke="#01dc82" stroke-width="2" marker-end="url(#a)"/>'
  boxes.append(f'<rect x="{x}" y="55" width="118" height="56" rx="7" fill="#fff" stroke="#cbd5e1"/><text x="{x+59}" y="78" text-anchor="middle" class="label2">{label}</text><text x="{x+59}" y="95" text-anchor="middle" class="label">signal {i+1}</text>{arrow}')
 return f'<div class="diagram"><svg viewBox="0 0 480 148" role="img" aria-label="Three linked signals for {e(g["title"])}"><defs><marker id="a" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 6 3 0 6Z" fill="#01dc82"/></marker></defs><text x="14" y="24" class="label">TODAY’S SIGNAL MAP</text>{"".join(boxes)}<text x="240" y="135" text-anchor="middle" class="label">SELECT → BOUND → MEASURE</text></svg></div>'
def report(g):
 cards=''
 for i,s in enumerate(g['sources'],1):
  cards+=f'''<article class="card" id="item-{i}"><h2>{e(s['title'])}</h2><div class="badges"><span class="badge good">{e(s['source_type'])}</span><span class="badge">{e(s['published_or_updated'])}</span><span class="badge warn">test before adoption</span></div><ul class="facts"><li>DIRECT — <a href="{e(s['url'])}">{e(s['url'])}</a></li></ul><div class="grid"><div class="mini"><h3>What it is</h3><p>{e(s['what'])}</p></div><div class="mini"><h3>Why it matters</h3><p>{e(s['matters'])}</p></div><div class="mini"><h3>Buildn / client use</h3><p>{e(s['use'])}</p></div></div><div class="callout"><strong>Caveat.</strong> {e(s['caveat'])}</div><p><strong>Follow-up:</strong> {e(s['action'])}</p></article>'''
 rows=''.join(f'<tr><td>{e(s["title"])}</td><td class="yes">●</td><td class="yes">●</td><td class="yes">●</td><td class="no">—</td></tr>' for s in g['sources'])
 trail=''.join(f'<li><a href="{e(s["url"])}">{e(s["title"])}</a> <span class="badge">{e(s["source_type"])}</span></li>' for s in g['sources'])
 return head('Daily Ingest Dossier — '+g['title'])+f'''<header><div class="wordmark">{logo()}<span>Buildn</span></div><h1>Daily Ingest Dossier — {e(g['title'])}</h1><div class="badges"><span class="badge">{DATE}</span><span class="badge good">adaptive coverage</span></div><p class="deck">{e(g['selection_rationale'])} Three primary-source signals; each earns attention because it can become a bounded operating experiment.</p></header><section><article class="card"><h2>Signal map</h2>{signal(g)}<p><span class="hl">Editorial read:</span> capability is cheap; admissibility, isolation, and evidence are the compounding advantages.</p></article>{cards}<article class="card"><h2>Use-case matrix</h2><table class="matrix"><tr><th>Signal</th><th>Buildn OS</th><th>Client work</th><th>Agent workflows</th><th>Personal leverage</th></tr>{rows}</table></article><article class="card top"><h2>Top actions</h2><ol>{''.join(f'<li><a href="#item-{i}">{e(s["action"])}</a></li>' for i,s in enumerate(g['sources'],1))}</ol></article><article class="card"><h2>Source trail</h2><ul>{trail}</ul></article></section><footer>Daily Ingest • {DATE} • Direct primary sources</footer></main></body></html>'''

for g in data['topic_groups']:
 (ART/f'daily-ingest-{g["slug"]}-{KEY}.html').write_text(report(g))
links=''.join(f'<article class="card"><h2>{e(g["title"])}</h2><p>{e(g["selection_rationale"])}</p><p><a href="{e(g["slug"])}.html">Open lane dossier →</a></p><div class="badges"><span class="badge good">3 signals</span></div></article>' for g in data['topic_groups'])
top=[(g['title'],g['sources'][0]['title'],g['sources'][0]['action'],g['slug']) for g in data['topic_groups']]
overview=head('Daily Ingest — '+DATE)+f'''<header><div class="wordmark">{logo()}<span>Buildn</span></div><h1>Daily Ingest — {DATE}</h1><p class="deck">{e(data['editorial_thesis'])}</p></header><section><article class="card"><h2>Today’s editorial thesis</h2><div class="diagram"><svg viewBox="0 0 600 150" role="img" aria-label="Operational control loop"><path d="M100 74H500" stroke="#01dc82" stroke-width="3"/><circle cx="100" cy="74" r="22" fill="#fff" stroke="#cbd5e1"/><circle cx="300" cy="74" r="22" fill="#fff" stroke="#01dc82" stroke-width="3"/><circle cx="500" cy="74" r="22" fill="#fff" stroke="#cbd5e1"/><text x="100" y="120" text-anchor="middle" class="label2">Measure</text><text x="300" y="120" text-anchor="middle" class="label2">Bound</text><text x="500" y="120" text-anchor="middle" class="label2">Prove</text></svg></div></article>{links}<article class="card top"><h2>All-lanes top three</h2><ol>{''.join(f'<li><strong>{e(t)}</strong> — {e(a)} <a href="{e(slug)}.html">Open</a></li>' for lane,t,a,slug in top)}</ol></article></section><footer>Adaptive Daily Ingest • {DATE}</footer></main></body></html>'''
(ART/f'daily-ingest-overview-{KEY}.html').write_text(overview)
(ART/f'daily-ingest-{KEY}.json').write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')

coverage_path=PAGES/'topic-coverage.json'; coverage=json.loads(coverage_path.read_text()); summary=coverage.setdefault('rolling_theme_summary',{})
for g in data['topic_groups']:
 entry=summary.setdefault(g['slug'],{'title':g['title'],'times_covered':0,'last_covered':None}); entry['title']=g['title']; entry['times_covered']+=1; entry['last_covered']=DATE
history=[x for x in coverage.get('item_history',[]) if x.get('date')!=DATE]
for g in data['topic_groups']:
 for s in g['sources']: history.append({'date':DATE,'lane':g['slug'],'title':s['title'],'url':s['url'],'source_type':s['source_type'],'selection_rationale':s['why_selected']})
coverage['item_history']=[x for x in history if x.get('date','')>='2026-06-24']; coverage['updated_at']=data['generated_at']; coverage['last_run']={'date':DATE,'selected_lanes':[g['slug'] for g in data['topic_groups']],'editorial_thesis':data['editorial_thesis']}
coverage_path.write_text(json.dumps(coverage,indent=2,ensure_ascii=False)+'\n')
print('Generated 3 lane dossiers, overview, ledger, and coverage memory.')
