#!/usr/bin/env python3
from pathlib import Path
import json, html, datetime as dt

DATE='2026-07-30'
STAMP=dt.datetime.now(dt.timezone.utc).isoformat()
ROOT=Path('/root/Projects/artifact-library/artifacts/daily-ingest')
PAGES=Path('/root/Projects/daily-ingest-pages')
ROOT.mkdir(parents=True, exist_ok=True)

lanes=[
 {'slug':'grounded-retrieval-framework-bridges','title':'Grounded Retrieval Framework Bridges','rationale':'Cloudflare shipped first-party AI Search guides for three agent ecosystems today. This is a practical coverage gap: retrieval can now sit behind the same framework interfaces used for Buildn and client agents, with sources returned to the calling workflow.',
  'readout':'Grounding is becoming a provider capability rather than a custom glue project. The useful move is a small, source-citing retrieval pilot that can be exercised from the framework already in use.','signal':['Cloudflare AI Search','Vercel AI SDK','LangChain','Cloudflare Agents SDK'],
  'sources':[
   {'title':'Use AI Search with the Agents SDK, AI SDK, and LangChain','url':'https://developers.cloudflare.com/changelog/post/2026-07-30-ai-search-agent-sdks/','source_type':'release','published_or_updated':DATE,'why_selected':'Today’s release makes Cloudflare AI Search directly usable from three popular agent frameworks.','usefulness':'A portable path to cited retrieval without hand-writing REST integration.'},
   {'title':'AI Search + Vercel AI SDK guide','url':'https://developers.cloudflare.com/ai-search/agent-sdks/ai-sdk/','source_type':'docs','published_or_updated':DATE,'why_selected':'Shows AI Search as a chat model and as a callable search tool within AI SDK flows.','usefulness':'Prototype a client knowledge assistant while keeping citations in the response path.'},
   {'title':'AI Search + LangChain guide','url':'https://developers.cloudflare.com/ai-search/agent-sdks/langchain/','source_type':'docs','published_or_updated':DATE,'why_selected':'Introduces CloudflareAISearchRetriever and retriever-tool patterns.','usefulness':'Useful where existing client workflows already use LangChain retrieval chains.'}],
  'cards':[
   ('Framework-native AI Search','release','AI Search now has integration guides for Cloudflare Agents SDK, Vercel AI SDK, and LangChain.','It lowers the integration cost of a grounded assistant; the retrieval layer can follow the agent framework rather than forcing a new orchestration stack.','Buildn OS: source-backed workspace answers. Client: scoped project knowledge assistant. Agents: a named retrieval tool. Personal: research with traceable links.','Confirm index tenancy, document permissions, retention, and citation behavior before production use.','Create one 20-document pilot; log answer, source set, and missed retrievals.'),
   ('AI SDK: chat plus tool','docs','The AI SDK guide supports an AI Search chat interface and explicit instance.search() tool exposure.','This creates two controllable patterns: retrieval-led conversations or model-led tool invocation.','Buildn OS: answer a help query. Client: allow a project agent to fetch approved facts. Agents: require source capture per tool call. Personal: use one curated namespace.','Tool descriptions and result limits shape behavior; do not treat retrieved text as authority without evaluation.','Implement both patterns against the same questions; compare citation completeness.'),
   ('LangChain retriever path','docs','The LangChain integration adds CloudflareAISearchRetriever for standalone retrieval, retriever tools, and RAG chains.','It offers a direct bridge when a client already has LangChain rather than a reason to rebuild their chain.','Buildn OS: reuse a retrieval contract. Client: add hybrid search to a service agent. Agents: expose a retriever tool. Personal: test cross-source queries.','Framework adapters do not solve content quality or access control; assess both separately.','Run a fixed 15-question set with hybrid retrieval and inspect the returned documents.')]
 },
 {'slug':'review-context-and-code-scanning','title':'Review Context + Code Scanning','rationale':'GitHub’s July 29 releases make code review more context-aware while improving static-analysis coverage. The material update is GA support for skills and read-only MCP in review, distinct from yesterday’s supply-chain prevention coverage.',
  'readout':'Put repository standards and read-only evidence into review, then let static scanning catch newly modeled flows. The control is not more automation; it is explainable, bounded context attached to an existing PR gate.','signal':['Repository skill','Read-only MCP','Review attribution','CodeQL 2.26.1'],
  'sources':[
   {'title':'Copilot code review: Agent skills and MCP now generally available','url':'https://github.blog/changelog/2026-07-29-copilot-code-review-agent-skills-and-mcp-now-generally-available/','source_type':'release','published_or_updated':'2026-07-29','why_selected':'Agent skills and MCP connections are now GA in Copilot code review, with read-only tool calls and attribution.','usefulness':'Turn client-specific review standards into a visible, auditable PR control.'},
   {'title':'CodeQL 2.26.1 improves analysis accuracy and framework coverage','url':'https://github.blog/changelog/2026-07-29-codeql-2-26-1-improves-analysis-accuracy-and-framework-coverage/','source_type':'release','published_or_updated':'2026-07-29','why_selected':'New modeling improves Go, Java/Kotlin, JS/TS coverage and reduces Rust false positives.','usefulness':'Directs teams to inspect new SSRF and origin-check findings rather than treating upgrades as background noise.'},
   {'title':'Default model enablement for Copilot Business and Enterprise','url':'https://github.blog/changelog/2026-07-29-default-model-enablement-for-copilot-business-and-enterprise/','source_type':'release','published_or_updated':'2026-07-29','why_selected':'A global policy can govern which generally available Copilot models are enabled.','usefulness':'Keeps model availability separate from repository review controls and pilot policy.'}],
  'cards':[
   ('Skills in code review','release','Copilot code review can now consume repository or organization skills; skills live under .github/skills/<name>/SKILL.md.','Review guidance can be versioned beside the code instead of remaining an unwritten team habit.','Buildn OS: a report-review skill. Client: acceptance criteria and service conventions. Agents: consistent pre-merge checks. Personal: reusable code-review rubric.','A skill is guidance, not enforcement; retain tests, human ownership, and branch protection.','Add one narrow skill for auth and data-boundary changes; sample ten reviews.'),
   ('Read-only MCP with attribution','release','Copilot review MCP calls are read-only, and comments disclose use of skills or MCP-provided context.','This yields a safer context boundary and lets reviewers distinguish grounded feedback from generic suggestions.','Buildn OS: issue and docs lookups. Client: service-catalog context. Agents: no mutation from review. Personal: trace why a comment appeared.','Every server and secret still needs owner, scope, and allow-list review.','Connect one documentation MCP server; inspect attribution and false-positive rate.'),
   ('CodeQL 2.26.1 changes the finding set','release','The release adds Spring WebFlux SSRF sink modeling, Angular message-handler analysis, Go slog modeling, and Rust false-positive barriers.','Scanner changes are operational events: newly surfaced findings require triage, not silent acceptance.','Buildn OS: alert-routing baseline. Client: targeted Java/Angular review. Agents: raise findings into PR triage. Personal: learn scanner deltas.','New detections can be valid or noisy; compare against an explicit baseline before marking regressions.','Run scans on active Java and TypeScript repos; triage all net-new high-severity findings.')]
 },
 {'slug':'realtime-client-interfaces','title':'Realtime Client Interfaces','rationale':'Two July 29 Vercel releases make low-latency agent interaction easier to route and instrument: a speech-to-speech model via a gateway and provider-neutral fast mode. This opens a client-experience lane that has been under-covered relative to back-office agents.',
  'readout':'Realtime interaction is now a product surface with explicit latency and spend choices. Treat voice and fast routing as measured interface experiments, not a blanket model upgrade.','signal':['Realtime voice','Short-lived tokens','Fast routing','Spend control'],
  'sources':[
   {'title':'Grok Voice Think Fast 2.0 now available on AI Gateway','url':'https://vercel.com/changelog/grok-voice-think-fast-2-0-now-available-on-ai-gateway','source_type':'release','published_or_updated':'2026-07-29','why_selected':'A speech-to-speech model is exposed through a gateway with routing, observability, spend controls, and failover.','usefulness':'A bounded way to test voice intake or client-facing assistance without shipping provider keys to browsers.'},
   {'title':'AI Gateway adds unified fast mode support','url':'https://vercel.com/changelog/ai-gateway-adds-unified-fast-mode-support','source_type':'release','published_or_updated':'2026-07-29','why_selected':'Fast serving can be requested on a base model with fallback to standard routing.','usefulness':'Lets an operator measure whether responsiveness is worth its per-token premium by workflow class.'},
   {'title':'Realtime voice, speech, and transcription now supported on AI Gateway','url':'https://vercel.com/changelog/realtime-voice-speech-and-transcription-now-supported-on-ai-gateway','source_type':'release','published_or_updated':'2026-07-29','why_selected':'The gateway’s realtime surface supports voice, speech generation, and transcription through a common API.','usefulness':'Supports a controlled comparison of voice intake, transcription, and text fallback in one product prototype.'}],
  'cards':[
   ('Speech-to-speech, gateway-controlled','release','Grok Voice Think Fast 2.0 accepts audio and returns audio; Vercel recommends minting short-lived server tokens for browser sessions.','It is a credible prototype path for an interactive intake instead of a chain of separate STT, model, and TTS services.','Buildn OS: spoken status intake. Client: guided discovery. Agents: voice-triggered research triage. Personal: hands-free capture.','Voice requires consent, retention rules, fallback UX, and careful evaluation on noisy calls.','Build a five-minute internal intake with explicit transcript review before any action.'),
   ('Fast mode is a routing policy','release','AI Gateway fast mode requests a lower-latency tier when available and falls back to standard; it costs more per token.','Speed becomes a workflow-level dial instead of a provider-specific integration decision.','Buildn OS: urgent operator requests. Client: first-response experience. Agents: short interactive turns. Personal: reserve for time-sensitive work.','It is beta and not universal; pricing and actual latency must be measured per model and route.','Instrument p50/p95 latency, completion quality, and cost for fast versus standard on 30 tasks.'),
   ('One modality surface, several fallbacks','release','The realtime API covers realtime voice, speech generation, and transcription.','A prototype can preserve accessibility and reliability with text and transcript paths, not just a single voice interaction.','Buildn OS: transcript-first audit trail. Client: text fallback. Agents: classify voice requests. Personal: searchable notes.','Do not let audio novelty obscure authorization, disclosure, and escalation requirements.','Define a voice-to-text fallback and human escalation before testing external users.')]
 }
]

def esc(s): return html.escape(s)
def logo(): return '<div class="wordmark"><svg viewBox="0 0 24 28" width="19" aria-hidden="true"><path fill="#01dc82" d="M17 28H0L2 10c1-1 2-1 4-1L7 0h16l1 3-2 16c-1 2-2 2-4 2z"/><path fill="#033330" d="M9 5l-.5 5H14l-.4 5h5l.7-8c-.4-1.2-1-1.7-2.4-2zM5.5 21l.6-7h5l-.4 4.5h5l-.5 4.5H7c-1-.3-1.2-.8-1.5-2z"/></svg><span>Buildn</span></div>'
CSS='''<style>:root{--brand:#01dc82;--deep:#033330;--lime:#cfe66a;--red:#b3261e;--amber:#9a6700;--ink:#0f172a;--muted:#475569;--line:#e2e8f0;--bg:#fafaf9;--card:#fff;--serif:"Newsreader",Georgia,serif;--sans:"Plus Jakarta Sans",system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:var(--sans);line-height:1.55}main{max-width:70rem;margin:auto;padding:3rem 1.5rem 5rem}.wordmark{display:flex;align-items:center;gap:.55rem;font-weight:700;color:var(--deep)}header{margin-bottom:2rem}h1,h2,h3{font-family:var(--serif);color:var(--deep)}h1{font-size:2.25rem;line-height:1.1;margin:.8rem 0 .4rem}h2{font-size:1.4rem;margin:0 0 .4rem}h3{font-size:1.08rem;margin:.1rem 0 .35rem}p{margin:.42rem 0 .8rem}a{color:#087c54}.date,.facts{font:.78rem ui-monospace,SFMono-Regular,monospace;color:var(--muted)}.card{background:var(--card);border:1px solid var(--line);border-radius:.8rem;padding:1.35rem;margin:1.1rem 0}.badges{display:flex;gap:.45rem;flex-wrap:wrap;margin-bottom:.7rem}.badge{font-size:.67rem;text-transform:uppercase;letter-spacing:.07em;font-weight:700;padding:.16rem .48rem;border-radius:.35rem;background:#e2e8f0;color:#334155}.good{background:#dcfce7;color:#166534}.warn{background:#fef3c7;color:#854d0e}.diagram{margin:1rem 0;border:1px solid var(--line);border-radius:.55rem;padding:.8rem;background:#fff}.diagram svg{display:block;width:100%;height:auto}.label{font:600 10px var(--sans);letter-spacing:.06em;fill:#475569}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:1rem}.matrix{width:100%;border-collapse:collapse;font-size:.83rem}.matrix th,.matrix td{border-bottom:1px solid var(--line);padding:.55rem;text-align:left;vertical-align:top}.matrix th{color:var(--deep)}.callout{border-left:3px solid var(--amber);background:#fffbeb;color:#713f12;padding:.65rem .85rem;border-radius:.25rem;font-size:.9rem}.wins{margin:.45rem 0;padding-left:1.1rem}.wins li{margin:.14rem 0}.top{border-left-color:var(--brand);background:#f0fdf4;color:#14532d}.overview-link{font-size:.86rem}</style>'''
def head(title): return f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">{CSS}</head><body><main>'
def signal_svg(words):
 x=[24,172,320,468]; boxes=''.join(f'<rect x="{x[i]}" y="58" width="118" height="46" rx="7" fill="#fff" stroke="#cbd5e1"/><text x="{x[i]+59}" y="84" text-anchor="middle" class="label">{esc(w)}</text>' for i,w in enumerate(words))
 arrows=''.join(f'<path d="M{x[i]+118} 81H{x[i+1]-10}" stroke="#94a3b8" fill="none" marker-end="url(#a)"/>' for i in range(3))
 return f'<div class="diagram"><svg viewBox="0 0 610 160" role="img" aria-label="Signal map"><defs><marker id="a" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0L6 3L0 6z" fill="#94a3b8"/></marker></defs><text x="24" y="28" class="label">DAY’S SIGNAL MAP</text>{arrows}{boxes}<path d="M83 104v28h444" stroke="#01dc82" fill="none"/><text x="305" y="149" text-anchor="middle" class="label">bounded pilot → measured decision</text></svg></div>'
def report(l):
 cards=''.join(f'''<article class="card"><div class="badges"><span class="badge good">{typ}</span><span class="badge">direct source</span></div><h2><a href="{esc(l['sources'][i]['url'])}">{esc(name)}</a></h2><p><strong>What:</strong> {esc(what)}</p><p><strong>Why now:</strong> {esc(why)}</p><p><strong>Use:</strong> {esc(use)}</p><div class="callout"><strong>Caveat:</strong> {esc(caveat)}</div><p><strong>Next:</strong> {esc(action)}</p></article>''' for i,(name,typ,what,why,use,caveat,action) in enumerate(l['cards']))
 sources=''.join(f'<li><a href="{esc(s["url"])}">{esc(s["title"])}</a> <span class="facts">— {s["published_or_updated"]}</span></li>' for s in l['sources'])
 return head(f"Daily Ingest Dossier — {l['title']} — {DATE}")+f'''<header>{logo()}<h1>Daily Ingest Dossier — {esc(l['title'])}</h1><div class="date">{DATE} · adaptive lane</div><p>{esc(l['readout'])}</p><p class="overview-link"><a href="daily-ingest-overview-20260730.html">← today’s overview</a></p></header><section><article class="card"><h2>Signal map</h2>{signal_svg(l['signal'])}<p>{esc(l['rationale'])}</p></article>{cards}<article class="card"><h2>Use-case matrix</h2><table class="matrix"><tr><th>Theme</th><th>Buildn OS</th><th>Client work</th><th>Agent workflow</th><th>Personal leverage</th></tr><tr><td>Bounded pilot</td><td>Instrumented, reversible</td><td>Small approved scope</td><td>Named inputs and outputs</td><td>Low-risk trial</td></tr><tr><td>Evidence</td><td>Traceable artifact</td><td>Reviewable outcome</td><td>Logs and owner</td><td>Reusable decision note</td></tr><tr><td>Control</td><td>Policy and rollback</td><td>Consent and access</td><td>Least privilege</td><td>Manual fallback</td></tr></table></article><article class="card"><h2>Top actions</h2><ul class="wins"><li>Open the primary release</li><li>Choose one bounded workflow</li><li>Define success and rollback</li><li>Measure before expanding</li></ul></article><article class="card"><h2>Source trail</h2><ul class="wins">{sources}</ul></article></section></main></body></html>'''

ledger={'date':DATE,'generated_at':STAMP,'editorial_thesis':'Use newly native agent interfaces to make client-facing intelligence more grounded, code review more context-aware, and interactive assistance more measurable.','topic_groups':[{k:v for k,v in l.items() if k in ('slug','title','rationale','sources')} | {'selection_rationale':l['rationale']} for l in lanes]}
# remove transient key not permitted schema
for g in ledger['topic_groups']: g.pop('rationale',None)
(ROOT/'daily-ingest-20260730.json').write_text(json.dumps(ledger,indent=2)+'\n')
for l in lanes: (ROOT/f"daily-ingest-{l['slug']}-20260730.html").write_text(report(l))
links=''.join(f'<article class="card"><div class="badges"><span class="badge good">selected lane</span></div><h2><a href="daily-ingest-{l["slug"]}-20260730.html">{esc(l["title"])}</a></h2><p>{esc(l["rationale"])}</p></article>' for l in lanes)
top=''.join(f'<li><strong>{esc(l["cards"][0][0])}</strong> — {esc(l["cards"][0][6])}</li>' for l in lanes)
overview=head(f'Daily Ingest Dossier — Overview — {DATE}')+f'''<header>{logo()}<h1>Daily Ingest Dossier</h1><div class="date">{DATE} · three adaptive lanes</div><p>Today’s thesis: use newly native agent interfaces to make client-facing intelligence more grounded, code review more context-aware, and interactive assistance more measurable.</p></header><section><article class="card"><h2>Editorial map</h2>{signal_svg(['Grounded retrieval','Code review','Realtime interface','Measured rollout'])}<p>Fresh primary releases earned three deliberately distinct lanes. Each is a practical integration or control surface; none requires a speculative platform rewrite.</p></article><div class="grid">{links}</div><article class="card"><h2>All-lanes top three</h2><ol class="wins">{top}</ol><div class="callout top">Recommendation: start with a source-citing retrieval pilot; it creates reusable evidence for the other two lanes.</div></article></section></main></body></html>'''
(ROOT/'daily-ingest-overview-20260730.html').write_text(overview)
# update coverage memory without overwriting historical runs
coverage_path=PAGES/'topic-coverage.json'; cov=json.loads(coverage_path.read_text())
summary=cov.setdefault('rolling_theme_summary',{})
items=cov.setdefault('item_history',[])
for l in lanes:
 key=l['slug']; prev=summary.get(key,{})
 summary[key]={'title':l['title'],'times_covered':prev.get('times_covered',0)+1,'last_covered':DATE}
 for s in l['sources']: items.append({'date':DATE,'theme':key,'title':s['title'],'url':s['url'],'source_type':s['source_type'],'selection_rationale':s['why_selected']})
# retain at least 45 days (all existing recent history is retained)
cov['updated_at']=STAMP
coverage_path.write_text(json.dumps(cov,indent=2)+'\n')
print('generated',len(lanes),'lane reports')
