from pathlib import Path
import json
from datetime import datetime, timezone

DATE='2026-07-29'
STAMP='20260729'
OUT=Path('/root/Projects/artifact-library/artifacts/daily-ingest')
OUT.mkdir(parents=True, exist_ok=True)

lanes=[
{'slug':'supply-chain-defensive-defaults','title':'Supply-chain Defensive Defaults','rationale':'A clustered July 28 release set changes the default posture at publish, dependency, and CI execution time; it is a meaningful, fresh security-operating signal and a coverage gap since the July 23 runtime patch sweep.','items':[
('GitHub Actions holds potentially malicious workflows for approval','https://github.blog/changelog/2026-07-28-github-actions-holds-potentially-malicious-workflows-for-approval/','release','2026-07-28','GitHub now pauses certain suspicious public-repository workflow runs for authenticated collaborator approval before execution.','Stops a compromised credential from immediately turning a workflow change into CI-secret theft.','Enable least-privilege Actions tokens; review held runs through an incident playbook.','Public github.com only; it is a safety net, not a substitute for branch protection.','Add “held workflow” ownership to the release-security checklist.'),
('npm publish-time malware scanning and dual-use metadata','https://github.blog/changelog/2026-07-28-npm-publish-time-malware-scanning-and-dual-use-metadata/','release','2026-07-28','npm scans a new package before install availability; dual-use packages require declared metadata, a DISCLOSURE file, and 2FA-enforced publishing.','Release pipelines that immediately install a just-published package now have a real availability dependency.','Make package smoke tests retry-aware; use trusted publishing for client packages.','Scanning can delay availability and declaration does not guarantee publication.','Audit any publish → install CI chain for a 15-minute readiness window.'),
('Dependabot alerts on malicious packages across more ecosystems','https://github.blog/changelog/2026-07-28-dependabot-alerts-on-malicious-packages-across-more-ecosystems/','release','2026-07-28','GitHub now ingests OpenSSF malicious-packages advisories into the Advisory Database for Dependabot malware alerts.','Detection coverage broadens beyond one registry and converts community malware intelligence into repository alerts.','Confirm Dependabot malware alerts at organization level; route alerts into the same triage queue as vulnerabilities.','Only known, reported malware is covered; lockfiles and dependency review still matter.','Verify malware alerts are enabled in Buildn and active client repositories.') ]},
{'slug':'human-checkpoints-browser-agents','title':'Human Checkpoints for Browser Agents','rationale':'Browser agents are moving from brittle manual intervention to explicit pause-and-resume contracts, a practical control gap distinct from yesterday’s protocol and memory coverage.','items':[
('Browser Run adds structured handoff for Human in the Loop','https://developers.cloudflare.com/changelog/post/2026-07-28-human-in-the-loop/','release','2026-07-28','Cloudflare Browser Run adds CDP commands to request operator help, expose a Live View, wait for completion, and resume the agent.','Login walls and unexpected prompts become named workflow states rather than silent browser-run failures.','Use for supervised intake, vendor portals, and authenticated client research where credentials never enter the agent prompt.','Requires an available operator and a bounded handoff timeout; it does not authorize unsafe actions.','Prototype one browser flow with explicit pause reasons, operator instructions, and resume evidence.'),
('Cloudflare MCP servers support the MCP 2026-07-28 Specification','https://developers.cloudflare.com/changelog/post/2026-07-28-cloudflare-mcp-servers-mcp-2026-07-28/','release','2026-07-28','Cloudflare moved product MCP servers to fresh stateless servers per request, retaining Streamable HTTP compatibility for older clients.','Explicit state and transport reduce hidden continuity assumptions around agent tool sessions.','Use /mcp for new connections and test reconnect behavior in client tool chains.','Clients forcing deprecated SSE need transport changes; statelessness shifts state design into the application.','Add a reconnect and interrupted-handoff test to one agent integration.'),
('Introducing Loops','https://linear.app/changelog/2026-07-20-introducing-loops','product','2026-07-20','Linear Agent can run shared, inspectable recurring jobs on schedules or events, with run history and team-level controls.','It is a useful operating reference: recurring agent work needs visible instructions, configuration, and traceable outcomes.','Apply the pattern to weekly client-status drafts or issue triage—review before dispatching code work.','Business/Enterprise only and consumes AI credits; automation scope must remain narrow.','Write one recurring-work spec with trigger, allowed actions, review gate, and stop condition.') ]},
{'slug':'governed-model-choice','title':'Governed Model Choice + Adoption Evidence','rationale':'The Copilot surface now couples a new selectable reasoning model with client-specific policy and richer attribution, creating an actionable model-evaluation loop rather than another model announcement.','items':[
('Grok 4.5 is now available in GitHub Copilot','https://github.blog/changelog/2026-07-28-grok-4-5-is-now-available-in-github-copilot/','release','2026-07-28','GitHub is gradually rolling Grok 4.5 into Copilot surfaces, with text/image input, reasoning-effort controls, and provider-list-price billing.','A candidate model is available inside existing PR, audit, and policy controls—useful for a bounded comparison, not blanket rollout.','Run a fixed set of exploration and terminal tasks; compare completed work, review burden, latency, and spend.','Business/Enterprise administrators must enable the policy; rollout is gradual and usage is billable.','Create a five-task evaluation card before enabling for a pilot group.'),
('GitHub Copilot app usage metrics now expand across report rollups','https://github.blog/changelog/2026-07-28-github-copilot-app-usage-metrics-now-expand-across-report-rollups','release','2026-07-28','Copilot app activity now appears by user, feature, model, language, code generation, acceptance, and daily-active-user metrics.','It closes an attribution gap: model experiments can be evaluated by workflow surface rather than license count alone.','Track an opt-in pilot against a baseline and pair the API with PR-quality review.','Generated lines and acceptance are proxies, not proof of customer value or code quality.','Pull one 28-day baseline before changing model policy.'),
('Manage GitHub Copilot app access with a dedicated policy','https://github.blog/changelog/2026-07-27-manage-github-copilot-app-access-with-a-dedicated-policy','release','2026-07-27','Copilot app access is now independently governed from Copilot CLI at enterprise and organization levels.','Separate client policy enables a smaller experiment surface while retaining central plugin and audit controls.','Enable only the client needed for the pilot; keep review, checks, and audit history mandatory.','The app policy is enabled by default, so existing organizations should deliberately review it.','Review AI Controls → Copilot Clients and document the permitted pilot surface.') ]}
]

ledger={'date':DATE,'generated_at':datetime.now(timezone.utc).isoformat(),'editorial_thesis':'Make automation earn trust at its boundaries: stop suspicious code before CI, pause browser agents for people, and measure model choices inside governed clients.','topic_groups':[]}
for l in lanes:
    sources=[]
    for i in l['items']:
        sources.append({'title':i[0],'url':i[1],'source_type':i[2],'published_or_updated':i[3],'why_selected':i[5],'usefulness':i[6]})
    ledger['topic_groups'].append({'slug':l['slug'],'title':l['title'],'selection_rationale':l['rationale'],'sources':sources})
(OUT/f'daily-ingest-{STAMP}.json').write_text(json.dumps(ledger,indent=2)+'\n')

css='''<style>:root{--brand:#01dc82;--deep:#033330;--lime:#cfe66a;--red:#b3261e;--amber:#9a6700;--ink:#0f172a;--muted:#475569;--line:#e2e8f0;--bg:#fafaf9;--card:#fff;--serif:"Newsreader",Georgia,serif;--sans:"Plus Jakarta Sans",system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:var(--sans);line-height:1.55}main{max-width:70rem;margin:auto;padding:3rem 1.5rem 5rem}.wordmark{display:flex;align-items:center;gap:.55rem;font-weight:700;color:var(--deep)}header{margin-bottom:2rem}h1,h2,h3{font-family:var(--serif);color:var(--deep)}h1{font-size:2.25rem;line-height:1.1;margin:.8rem 0 .4rem}h2{font-size:1.4rem;margin:0 0 .35rem}h3{font-size:1.08rem;margin:.1rem 0 .35rem}p{margin:.42rem 0 .78rem}a{color:#087c54}.date,.facts{font:.78rem ui-monospace,SFMono-Regular,monospace;color:var(--muted)}.card{background:var(--card);border:1px solid var(--line);border-radius:.8rem;padding:1.35rem;margin:1.1rem 0}.badges{display:flex;gap:.45rem;flex-wrap:wrap;margin-bottom:.7rem}.badge{font-size:.67rem;text-transform:uppercase;letter-spacing:.07em;font-weight:700;padding:.16rem .48rem;border-radius:.35rem;background:#e2e8f0;color:#334155}.good{background:#dcfce7;color:#166534}.warn{background:#fef3c7;color:#854d0e}.diagram{margin:1rem 0;border:1px solid var(--line);border-radius:.55rem;padding:.8rem;background:#fff}.diagram svg{display:block;width:100%;height:auto}.label{font:600 10px var(--sans);letter-spacing:.06em;fill:#475569}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:.75rem}.mini{border:1px solid var(--line);border-radius:.55rem;padding:.8rem}.mini strong{display:block;color:var(--deep)}.callout{border-left:3px solid var(--amber);background:#fffbeb;color:#713f12;padding:.65rem .85rem;border-radius:.25rem;font-size:.9rem}.matrix{width:100%;border-collapse:collapse;font-size:.86rem}.matrix th,.matrix td{border-bottom:1px solid var(--line);text-align:left;padding:.55rem}.matrix th{color:var(--muted)}.actions{padding-left:1.15rem}.actions li{margin:.35rem 0}.hl{background:color-mix(in srgb,var(--lime) 60%,transparent);padding:0 .15em}@media(max-width:560px){main{padding:2rem 1rem}.matrix{font-size:.74rem}}</style>'''
logo='''<div class="wordmark"><svg viewBox="0 0 164 195" width="22" aria-hidden="true"><path d="M117 194.5H0L12 73C17 66 21 65 28 64L34 0h117c7 4 10 7 12 13l-10 106c-4 8-8 10-18 11l-4 54c-3 6-6 9-14 10Z" fill="#01dc82"/><path d="m64 33-3 31h32l-2 33h32l4-50c-2-9-5-12-15-14H64Z" fill="#033330"/></svg><span>Buildn</span></div>'''
def esc(s):
    return s.replace('&','&amp;').replace('<','&lt;').replace('>','&gt;')
def map_svg(items):
    n=len(items); width=180*n
    boxes=''; lines=''
    for x,i in enumerate(items):
        px=15+x*180
        boxes+=f'<rect x="{px}" y="40" width="145" height="58" rx="7" fill="#fff" stroke="#cbd5e1"/><text x="{px+72}" y="64" text-anchor="middle" class="label">{esc(i[0][:22])}</text><text x="{px+72}" y="80" text-anchor="middle" class="label">{esc(i[2].upper())}</text>'
        if x<n-1: lines+=f'<path d="M{px+145} 69H{px+175}" stroke="#01dc82" stroke-width="2"/>'
    return f'<div class="diagram"><svg viewBox="0 0 {width} 140" role="img" aria-label="Signal map for selected items"><text x="15" y="19" class="label">TODAY’S CLUSTER · {n} DIRECT SIGNALS</text>{lines}{boxes}</svg></div>'
def report(l):
    cards=''
    for i in l['items']:
        cards+=f'''<article class="card"><div class="badges"><span class="badge good">{esc(i[2])}</span><span class="badge">{i[3]}</span></div><h2><a href="{i[1]}">{esc(i[0])}</a></h2><p class="facts">SOURCE · {i[1]}</p><div class="grid"><div class="mini"><strong>What changed</strong>{esc(i[4])}</div><div class="mini"><strong>Why it matters</strong>{esc(i[5])}</div><div class="mini"><strong>Buildn / client use</strong>{esc(i[6])}</div></div><p class="callout"><b>Caveat.</b> {esc(i[7])}</p><p><b>Follow-up:</b> <span class="hl">{esc(i[8])}</span></p></article>'''
    trails=''.join(f'<li><a href="{i[1]}">{esc(i[0])}</a> <span class="facts">({i[3]})</span></li>' for i in l['items'])
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily Ingest Dossier — {esc(l['title'])} — {DATE}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">{css}</head><body><main><header>{logo}<p class="date">DAILY INGEST DOSSIER · {DATE}</p><h1>{esc(l['title'])}</h1><p>{esc(l['rationale'])}</p><p>Executive readout: turn the fresh platform change into a <span class="hl">bounded operating experiment</span>, retain an explicit review point, and record the outcome before expanding scope.</p></header><section class="card"><h2>Signal map</h2>{map_svg(l['items'])}</section><section><h2>Dossier cards</h2>{cards}</section><section class="card"><h2>Use-case matrix</h2><table class="matrix"><tr><th>Theme</th><th>Buildn OS</th><th>Client work</th><th>Agent workflows</th><th>Personal leverage</th></tr><tr><td>Control boundary</td><td>Policy + audit</td><td>Reviewable delivery</td><td>Explicit pause / scope</td><td>Less hidden risk</td></tr><tr><td>Trial</td><td>Small cohort</td><td>One low-risk workflow</td><td>Trace inputs / outcome</td><td>Reusable checklist</td></tr><tr><td>Success signal</td><td>Quality + cost</td><td>Finished work</td><td>Safe recovery</td><td>Time saved</td></tr></table></section><section class="card"><h2>Top actions</h2><ol class="actions">{''.join(f'<li>{esc(i[8])}</li>' for i in l['items'])}</ol></section><section class="card"><h2>Source trail</h2><ul>{trails}</ul></section></main></body></html>'''
for l in lanes: (OUT/f'daily-ingest-{l["slug"]}-{STAMP}.html').write_text(report(l))
links=''.join(f'<article class="card"><div class="badges"><span class="badge good">Selected lane</span></div><h2>{esc(l["title"])}</h2><p>{esc(l["rationale"])}</p><p><a href="daily-ingest-{l["slug"]}-{STAMP}.html">Open mini-dossier →</a></p></article>' for l in lanes)
overview=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily Ingest Dossier — Overview — {DATE}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">{css}</head><body><main><header>{logo}<p class="date">DAILY INGEST DOSSIER · {DATE}</p><h1>Trust boundaries, not more autonomous surface area</h1><p>Today’s signals align around a practical operating principle: block suspicious code before it runs, formalize the human interruption, and measure model use inside a governed client.</p></header><section>{links}</section><section class="card"><h2>All-lanes top three</h2><ol class="actions"><li>Audit publish → install release automation for npm’s scan-induced readiness gap.</li><li>Prototype a browser-agent handoff with a named operator, timeout, and resume artifact.</li><li>Set a five-task, metrics-backed Copilot model pilot before enabling a new model broadly.</li></ol></section></main></body></html>'''
(OUT/f'daily-ingest-overview-{STAMP}.html').write_text(overview)
print('Generated',len(lanes),'lane reports, overview, and ledger in',OUT)
