from pathlib import Path
import json, datetime

DATE='20260816'; ISO='2026-08-16'
OUT=Path('/root/Projects/artifact-library/artifacts/daily-ingest'); OUT.mkdir(parents=True,exist_ok=True)

CSS='''<style>:root{--brand:#01dc82;--deep:#033330;--lime:#cfe66a;--red:#b3261e;--amber:#9a6700;--ink:#0f172a;--muted:#475569;--line:#e2e8f0;--bg:#fafaf9;--card:#fff;--serif:Newsreader,Georgia,serif;--sans:"Plus Jakarta Sans",ui-sans-serif,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:var(--sans);line-height:1.55}main{max-width:64rem;margin:auto;padding:3rem 1.5rem}header{display:flex;flex-direction:column;gap:1rem;margin-bottom:2.2rem}.wordmark{display:flex;align-items:center;gap:.6rem;font-weight:700;color:var(--deep)}h1,h2{font-family:var(--serif);color:var(--deep);font-weight:600}h1{font-size:2.25rem;margin:0}h2{font-size:1.35rem;margin:0 0 .5rem}h3{font-size:.72rem;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);margin:1.1rem 0 .35rem}.dek{max-width:54rem;color:var(--muted);font-size:1rem}.card{background:var(--card);border:1px solid var(--line);border-radius:.75rem;padding:1.4rem;margin:1rem 0}.badges{display:flex;flex-wrap:wrap;gap:.45rem;margin:.25rem 0 .8rem}.badge{font-size:.68rem;text-transform:uppercase;letter-spacing:.06em;font-weight:700;padding:.15rem .5rem;border-radius:.35rem;background:#f1f5f9;color:var(--muted)}.good{background:#dcfce7;color:#166534}.warn{background:#fef3c7;color:var(--amber)}.spec{background:#e2e8f0;color:#334155}.facts{font-family:ui-monospace,monospace;font-size:.78rem;color:var(--muted);list-style:none;padding:0;margin:.4rem 0}.facts li{padding:.12rem 0}.diagram{border:1px solid var(--line);border-radius:.5rem;background:#fff;padding:.8rem;margin:1rem 0}.diagram svg{display:block;max-width:100%;height:auto}.label{font-size:11px;text-transform:uppercase;letter-spacing:.08em;fill:var(--muted)}.wins{margin:.5rem 0 0;padding-left:1.1rem}.wins li{margin:.15rem 0}.callout{border-left:3px solid var(--amber);background:#fffbeb;color:#713f12;padding:.6rem .9rem;border-radius:.25rem;font-size:.88rem}a{color:#087f55}.source{font-size:.85rem;word-break:break-word}.matrix{width:100%;border-collapse:collapse;font-size:.82rem}.matrix th,.matrix td{border-bottom:1px solid var(--line);padding:.55rem;text-align:left;vertical-align:top}.matrix th{color:var(--deep);font-size:.72rem;text-transform:uppercase;letter-spacing:.06em}.top{border-left:4px solid var(--brand)}.small{font-size:.86rem;color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:1rem}.grid .card{margin:0}ul{padding-left:1.1rem}</style>'''
LOGO='''<svg viewBox="0 0 164 195" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" width="22"><path d="M117 194.5H0L12 73C17.47 66.63 21.30 65.46 28.5 64.5L34.5 0H151.5C158.44 4.40 161.28 7.18 163.5 13L153 119.5C148.80 127.15 144.97 129.55 135.5 130.5L131 184.5C127.71 190.35 125.13 192.98 117 194.5Z" fill="#01dc82"/><path d="M64 33L61 64.5H93.5L91 97H123L127.5 46.5C125.53 37.94 122.01 35.19 112.5 33H64Z" fill="#033330"/><path d="M37 147.5L41.5 98H74.5L71.5 129.5L104 130.5L100.5 162H49.5C41.82 159.35 39.68 155.53 37 147.5Z" fill="#033330"/></svg>'''

def shell(title,dek,body):
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,500;6..72,600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">{CSS}</head><body><main><header><div class="wordmark">{LOGO}<span>Buildn</span></div><h1>{title}</h1><div class="small">{ISO} · Adaptive daily ingest</div><div class="dek">{dek}</div></header>{body}</main></body></html>'''

def signal(labels):
 xs=[30,145,260,375,490,605]; boxes=''.join(f'<rect x="{x}" y="38" width="92" height="42" rx="6" fill="#fff" stroke="#cbd5e1"/><text x="{x+46}" y="63" text-anchor="middle" class="label">{lab}</text>' for x,lab in zip(xs,labels))
 arrows=''.join(f'<line x1="{x+92}" y1="59" x2="{x+115}" y2="59" stroke="#94a3b8" marker-end="url(#a)"/>' for x in xs[:-1])
 return f'<div class="diagram"><svg viewBox="0 0 730 110" role="img" aria-label="Signal map"><defs><marker id="a" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#94a3b8"/></marker></defs>{arrows}{boxes}<text x="365" y="101" text-anchor="middle" class="label">fresh signals converge on a practical control surface</text></svg></div>'

def item(title,badge,url,what,why,use,now,caveat,action):
 return f'''<article class="card"><h2>{title}</h2><div class="badges"><span class="badge {badge[0]}">{badge[1]}</span><span class="badge">{badge[2]}</span></div><ul class="facts"><li>source · <a href="{url}">{url}</a></li></ul><h3>What it is</h3><div>{what}</div><h3>Why it matters</h3><div>{why}</div><h3>Buildn / client use</h3><div>{use}</div><h3>Why now</h3><div>{now}</div><div class="callout"><b>Caveat:</b> {caveat}</div><h3>Follow-up</h3><div><span class="hl">{action}</span></div></article>'''

def lane(slug,title,dek,labels,items,rows,actions):
 cards=''.join(item(*x) for x in items)
 matrix='<table class="matrix"><thead><tr><th>Theme</th><th>Buildn OS</th><th>Client work</th><th>Agent workflow</th><th>Personal leverage</th></tr></thead><tbody>'+''.join('<tr>'+''.join(f'<td>{c}</td>' for c in r)+'</tr>' for r in rows)+'</tbody></table>'
 body=f'<section><article class="card"><h2>Executive readout</h2><p>{dek}</p>{signal(labels)}</article><h2>Dossier cards</h2>{cards}<article class="card"><h2>Use-case matrix</h2>{matrix}</article><article class="card top"><h2>Top actions</h2><ol>'+''.join(f'<li>{a}</li>' for a in actions)+'</ol></article><article class="card"><h2>Source trail</h2><ul>'+''.join(f'<li class="source"><a href="{x[2]}">{x[0]}</a></li>' for x in items)+'</ul></article></section>'
 return shell(f'Daily Ingest Dossier — {title}',dek,body)

lanes={
'agent-development-lifecycle':('Agent Development Lifecycle','Implementation is no longer the bottleneck; validation, deployment, observability, and maintenance are. Cloudflare’s ADLC and open Cloudflare OS point toward agent systems that own durable work rather than merely emitting code.', ['Plan','Build','Trace','Ship','Maintain','Retire'], [
('Agent Development Lifecycle','good','architecture','https://blog.cloudflare.com/agent-development-lifecycle/','Cloudflare proposes a lifecycle in which agents plan, implement, test, deploy, observe, improve, and retire software using Workflows, traces, artifacts, and programmable infrastructure.','It reframes agent adoption from “coding assistant” to an operating model with explicit post-generation accountability.','Model Buildn jobs as durable state machines: research → draft → review → publish → observe, with a human gate only where judgment is needed.','The proposal is directional and vendor-shaped; do not confuse a compelling lifecycle diagram with evidence of safe autonomy.','Pick one recurring Buildn job and map every handoff after generation.'),
('Cloudflare OS','good','platform','https://blog.cloudflare.com/cloudflare-os/','An open platform combining agent workspaces, company context, secure internal access, live apps, and reusable skills.','The valuable abstraction is a governed workspace that can grow from a chat into a connected artifact or workflow.','Use it as a reference for client portals where knowledge, permissions, generated files, and automations share one boundary.','Deployment is tied to Cloudflare primitives and the open-source maturity is still emerging.','Extract its capability, approval, and observation concepts into a vendor-neutral checklist.'),
('OpenTelemetry traces in local development','good','observability','https://blog.cloudflare.com/local-tracing/','Local development can expose production-like agent traces so agents and humans can inspect tool calls and failures before deployment.','Trace visibility is the missing feedback loop between generated code and trustworthy operation.','Add trace IDs, tool spans, and failure reasons to any Buildn agent that performs multi-step work.','Tracing shows behavior; it does not by itself enforce least privilege or correctness.','Define a minimum trace schema before adding more agent tools.'),
('Software factory issue triage','warn','workflow','https://blog.cloudflare.com/astro-issue-triage/','Cloudflare describes an agent workflow that triages, reproduces, verifies, and fixes issues at scale.','This is a concrete pattern for turning an unbounded inbox into bounded, testable work packets.','Prototype automated intake for client bug reports with reproduction evidence and a human merge gate.','Issue quality and test coverage determine whether automation reduces or multiplies noise.','Run ten historical issues through a replay harness and score false fixes.'),
('ADLC as an operating thesis','spec','strategy','https://blog.cloudflare.com/agent-development-lifecycle/','A strategic argument that software factories should own the full lifecycle while people focus on product judgment, design, and customer context.','It identifies the real organizational constraint: review and operations capacity, not prompt capacity.','Use it to scope service offerings around reliability, governance, and maintenance—not prompt libraries.','The thesis may overstate autonomy and understate socio-technical coordination.','Rewrite one client proposal around lifecycle outcomes instead of model features.')],
[('Durability','checkpointed jobs','resumable delivery','pause/resume state','fewer repeated prompts'),('Observability','trace ledger','production evidence','tool-span debugging','reviewable sessions'),('Governance','approval gates','release policy','bounded permissions','clear stopping rules')],['Instrument one workflow end-to-end.','Create a lifecycle scorecard: test, deploy, observe, maintain.','Keep humans at product and irreversible-action boundaries.']),
'agent-security-governance':('Agent Security Governance','Fresh guidance is moving from principles to operational controls: inventory the AI surface, bind identity to actions, assess DevSecOps, and make revocation and evidence part of the default path.', ['Inventory','Identity','Least privilege','Observe','Revoke','Recover'], [
('Zero Trust Assessment for AI','good','control plane','https://www.microsoft.com/en-us/security/blog/2026/08/04/advance-zero-trust-for-ai-new-tools-and-guidance-to-secure-ai-agents-and-devsecops/','Microsoft expanded its assessment with AI, SecOps, and infrastructure pillars and added a DevSecOps workshop pillar with 15 control groups and 91 tasks.','It gives teams a practical bridge from “we need AI security” to a prioritized remediation roadmap.','Turn the control groups into a client discovery worksheet for repositories, CI/CD, agents, memory, tools, and runtime.','It is Microsoft-centric and assessment outputs still require technical validation.','Run a lightweight gap assessment against one real agent workflow.'),
('AI memory and runtime guidance','good','architecture','https://www.microsoft.com/en-us/security/blog/2026/08/04/advance-zero-trust-for-ai-new-tools-and-guidance-to-secure-ai-agents-and-devsecops/','The guidance treats memory, tools, data, and runtime behavior as distinct trust surfaces.','Separating these surfaces makes threat modeling less vague than “prompt injection risk.”','Add memory provenance, retention, tool authority, runtime isolation, and egress to Buildn design reviews.','Guidance is not a tested reference implementation.','Add five explicit trust-boundary questions to the agent intake form.'),
('GHES 3.22 disconnected Copilot CLI','warn','air-gapped','https://github.blog/changelog/2026-08-11-github-enterprise-server-3-22-release-candidate/','The release candidate supports Copilot CLI in disconnected or air-gapped GHES deployments with a centrally configured model provider.','It makes local or restricted-network coding assistance a governance and deployment question, not only a model question.','Use the pattern when clients require data locality, private repositories, or controlled model egress.','Technical preview; provider and feature behavior may change.','Document a reference deployment with explicit network and credential boundaries.'),
('Individual bypasses and required reviewers','good','repository policy','https://github.blog/changelog/2026-08-11-github-enterprise-server-3-22-release-candidate/','GHES rulesets can target individual bypasses and require reviewers by path, including security, QA, design, or data teams.','Policy granularity is exactly what agent-generated changes need when code volume rises.','Require named review classes for agent changes touching auth, data, prompts, or deployment manifests.','Overly granular rules can create approval fatigue and shadow bypasses.','Create a path-based ruleset for one agent-owned repository.'),
('Threat model beyond prompts','warn','method','https://www.microsoft.com/en-us/security/blog/2026/08/04/advance-zero-trust-for-ai-new-tools-and-guidance-to-secure-ai-agents-and-devsecops/','The combined guidance covers dependencies, build artifacts, infrastructure-as-code, memory, and runtime operations.','It broadens the threat model to the whole agent supply chain.','Use a “source → model → tool → data → artifact → deploy” walk-through in client workshops.','Vendor guidance can miss product-specific abuse cases.','Run a 30-minute attack-path exercise on a current automation.')],
[('Identity','owner + expiry','delegated operator','service principal policy','know who can act'),('Supply chain','review gates','artifact provenance','dependency checks','less mystery code'),('Response','revoke + recover','incident playbook','kill switch','safe stopping')],['Inventory every agent and delegated identity.','Adopt path-based review rules for irreversible changes.','Treat memory and runtime as first-class assets.']),
'portable-agent-workflows':('Portable Agent Workflows','GitHub’s August release cluster makes agent behavior more portable and inspectable: plugins work across surfaces, CLI tasks can be planned and rewound, and local models can enter the same workflow.', ['Plugin','Plan','Queue','Rewind','Memory','Local model'], [
('Agent Plugins 1.0','good','portable tooling','https://github.blog/changelog/2026-08-12-agent-plugins-1-0-in-vs-code-copilot-cli-and-the-copilot-app/','A plugin can be built once and used across VS Code, Copilot CLI, the Copilot SDK, and the Copilot app.','Portability shifts reuse from prompt text to packaged tools, skills, and policy-aware interfaces.','Package recurring Buildn research or reporting actions as a portable plugin contract.','Compatibility does not guarantee identical permissions or behavior on every host.','Write one plugin manifest with explicit inputs, outputs, and side effects.'),
('Headless plan + autopilot','good','execution','https://github.blog/changelog/2026-08-13-github-copilot-weekly-releases-august-10/','Copilot CLI can create a plan and implement it headlessly, while centralized task management handles subagents and queued work.','The useful primitive is a visible plan boundary before autonomous execution.','Require plan artifacts before agents modify client repositories or publish reports.','Autopilot remains sensitive to repository context and test quality.','Compare planned versus changed files on five low-risk tasks.'),
('Non-destructive rewind','good','recovery','https://github.blog/changelog/2026-08-13-github-copilot-weekly-releases-august-10/','The CLI can restore agent changes without requiring Git or discarding user edits.','Recovery is a prerequisite for safe experimentation with higher autonomy.','Mirror the idea in Buildn workspaces: isolate agent edits and expose a reversible checkpoint.','Rewind semantics must be tested around generated files, renames, and concurrent edits.','Define a reversible-change contract and test it with fixtures.'),
('Copilot memory in JetBrains','warn','continuity','https://github.blog/changelog/2026-08-11-copilot-memory-and-ollama-in-github-copilot-for-jetbrains/','JetBrains sessions can preserve project details and preferences across agent chats.','Cross-session memory reduces repeated setup but raises provenance and staleness questions.','Use explicit project memory files rather than invisible personalization for client work.','Memory may preserve wrong assumptions unless users can inspect and clear it.','Adopt a visible memory ledger with source, owner, and expiry.'),
('Ollama BYOK in JetBrains','good','local inference','https://github.blog/changelog/2026-08-11-copilot-memory-and-ollama-in-github-copilot-for-jetbrains/','JetBrains users can route Copilot through local Ollama models as a BYOK provider.','Local inference creates a useful privacy and cost fallback for bounded coding tasks.','Benchmark local models for redaction, refactors, and documentation where cloud access is undesirable.','Quality, hardware, and context limits may erase the apparent savings.','Run a small task matrix with latency, quality, and data-egress scores.')],
[('Reuse','portable plugin','shared skill','same contract, many hosts','less setup'),('Control','plan artifact','review policy','queued tasks','visible intent'),('Recovery','rewind','checkpointed branch','safe experimentation','lower fear of trying')],['Standardize agent plugins around contracts, not prompts.','Make plans and checkpoints visible deliverables.','Benchmark local inference on bounded, low-risk tasks.']),
'identity-aware-collaboration':('Identity-Aware Collaboration','Linear’s latest team initiative update joins MCP authorization to everyday collaboration controls. The signal is practical: agent access should inherit managed identity, while teams need better visibility into what work is active and who can act.', ['Identity','MCP','Teams','Projects','Review','Audit'], [
('Enterprise-managed MCP authorization','good','identity','https://linear.app/changelog/2026-08-13-team-initiatives','Linear MCP access can be managed through existing Okta-managed identity.','MCP becomes an enterprise access surface that can inherit joiner/mover/leaver controls.','Use managed identity as the default for client-facing agent connectors; avoid ad hoc shared tokens.','The update is specific to Linear’s MCP surface and does not solve authorization inside tools.','Map every connector to an owner, identity provider, scope, and revocation path.'),
('Agent widgets on project milestones','warn','collaboration','https://linear.app/changelog/2026-08-13-team-initiatives','Linear added project milestone agent widgets on iOS alongside broader initiative and project improvements.','The workflow is moving from chat into ambient project surfaces where status and next actions are visible.','Prototype a Buildn project view that shows agent-produced evidence beside milestone state.','Widgets can become decorative if they do not link to source evidence or actions.','Define one milestone widget with a measurable decision it supports.'),
('Branch-status visibility','good','delivery','https://linear.app/changelog/2026-08-13-team-initiatives','A branch-status widget shows whether a branch is up to date, behind, or conflicted.','Small status primitives reduce coordination cost around agent-generated diffs.','Expose freshness and conflict state beside automated implementation tasks.','Status is only useful when updated reliably and tied to the actual merge target.','Add freshness checks to any agent task that opens a PR.'),
('Mermaid diagram comments','good','design ops','https://linear.app/changelog/2026-08-13-team-initiatives','Linear editor comments now support Mermaid diagrams.','Diagram review becomes part of the work record rather than a separate image artifact.','Use diagrams to review agent workflow changes and architecture decisions in context.','Static diagrams can still drift from implementation.','Require an owner and source link on decision diagrams.'),
('GPT-5.6 Luna in coding sessions','warn','model choice','https://linear.app/changelog/2026-08-13-team-initiatives','Linear added GPT-5.6 Luna as a coding-session model option.','Model choice is entering the project-management surface, making task routing part of delivery operations.','Record model, task type, and outcome so clients can compare cost and quality by workflow.','A model picker is not an evaluation system.','Create a tiny eval set from real issue types before standardizing on a model.')],
[('Access','Okta identity','client SSO','connector scope','fewer shared secrets'),('Evidence','milestone widget','status + source','freshness checks','context at a glance'),('Decisions','diagram comments','review trail','model/task record','reusable judgment')],['Treat MCP as an enterprise connector, not a personal shortcut.','Attach evidence and freshness to agent-produced status.','Record model choice as part of workflow evaluation.'])
}

ledger={'date':'2026-08-16','generated_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'editorial_thesis':'The useful frontier is operational: durable agent lifecycles, explicit security controls, portable execution, and identity-aware collaboration outperform another generic model roundup.','topic_groups':[]}
for slug,(title,dek,labels,items,rows,actions) in lanes.items():
 (OUT/f'daily-ingest-{slug}-{DATE}.html').write_text(lane(slug,title,dek,labels,items,rows,actions),encoding='utf-8')
 ledger['topic_groups'].append({'slug':slug,'title':title,'selection_rationale':dek,'sources':[{'title':x[0],'url':x[2],'source_type':'blog' if 'blog' in x[2] else 'release','published_or_updated':'2026-08-13' if 'linear' in x[2] else '2026-08-11','why_selected':x[3],'usefulness':x[5]} for x in items]})

links=''.join(f'<article class="card"><h2>{t}</h2><p>{d}</p><a href="{slug}.html">Open lane report →</a></article>' for slug,(t,d,*_) in lanes.items())
top='<ol><li>Map one Buildn workflow to an ADLC with checkpoints, traces, and a human gate.</li><li>Run a zero-trust gap assessment across one agent’s identity, tools, memory, and runtime.</li><li>Package one recurring task as a portable plugin contract with plan and rewind semantics.</li></ol>'
source_links=''.join('<li><a href="{0}">{1}</a></li>'.format(s['url'],s['title']) for g in ledger['topic_groups'] for s in g['sources'])
overview_body='''<section><article class="card top"><h2>Executive readout</h2><p>{thesis}</p><div class="diagram"><svg viewBox="0 0 680 150" role="img" aria-label="Four selected lanes"><rect x="20" y="30" width="140" height="55" rx="8" fill="#dcfce7"/><text x="90" y="63" text-anchor="middle" class="label">lifecycle</text><rect x="185" y="30" width="140" height="55" rx="8" fill="#fef3c7"/><text x="255" y="63" text-anchor="middle" class="label">security</text><rect x="350" y="30" width="140" height="55" rx="8" fill="#e2e8f0"/><text x="420" y="63" text-anchor="middle" class="label">portability</text><rect x="515" y="30" width="140" height="55" rx="8" fill="#dcfce7"/><text x="585" y="63" text-anchor="middle" class="label">identity</text><path d="M90 105 H585" stroke="#01dc82" stroke-width="3" stroke-dasharray="5 5"/><text x="340" y="135" text-anchor="middle" class="label">operational controls are the connective tissue</text></svg></div></article><h2>Selected lanes</h2><div class="grid">{links}</div><article class="card"><h2>All-lanes top three</h2>{top}</article><article class="card"><h2>Selection rationale</h2><ul><li>Rotates away from yesterday’s platform-release and security-report emphasis toward lifecycle design and collaboration.</li><li>Prioritizes primary sources with direct implementation consequences.</li><li>Uses only sources not present in the durable coverage ledger.</li></ul></article><article class="card"><h2>Source trail</h2><ul>{source_links}</ul></article></section>'''.format(thesis=ledger['editorial_thesis'],links=links,top=top,source_links=source_links)
overview=shell('Daily Ingest Dossier — Overview',ledger['editorial_thesis'],overview_body)
(OUT/f'daily-ingest-overview-{DATE}.html').write_text(overview,encoding='utf-8')
(OUT/f'daily-ingest-{DATE}.json').write_text(json.dumps(ledger,indent=2),encoding='utf-8')
print('generated',len(lanes)+2,'files')
