from pathlib import Path
from html import escape
import json
from datetime import datetime, timezone

DATE='2026-08-12'; KEY='20260812'; NOW=datetime.now(timezone.utc).isoformat()
ART=Path('/root/Projects/artifact-library/artifacts/daily-ingest'); PAGES=Path('/root/Projects/daily-ingest-pages')
ART.mkdir(parents=True,exist_ok=True); (PAGES/DATE).mkdir(parents=True,exist_ok=True)

CSS='''
:root{--brand:#01dc82;--deep:#033330;--lime:#cfe66a;--red:#b3261e;--amber:#9a6700;--ink:#0f172a;--muted:#475569;--line:#e2e8f0;--bg:#fafaf9;--card:#fff;--serif:Newsreader,Georgia,serif;--sans:'Plus Jakarta Sans',system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.55 var(--sans)}main{max-width:64rem;margin:auto;padding:3rem 1.5rem}header{display:flex;flex-direction:column;gap:1rem;margin-bottom:2rem}.wordmark{font-weight:700;color:var(--deep);display:flex;gap:.5rem;align-items:center}h1,h2{font-family:var(--serif);color:var(--deep);font-weight:600}h1{font-size:2.2rem;margin:0}h2{font-size:1.35rem;margin:0 0 .4rem}h3{font-size:1rem;margin:.8rem 0 .2rem}a{color:#007a53}.readout{font-size:1.05rem;max-width:54rem}.date{color:var(--muted);font-size:.82rem}.card{background:var(--card);border:1px solid var(--line);border-radius:.75rem;padding:1.35rem;margin:1rem 0}.badges{display:flex;gap:.45rem;flex-wrap:wrap;margin:.3rem 0 .8rem}.badge{font-size:.68rem;text-transform:uppercase;letter-spacing:.06em;font-weight:700;padding:.15rem .5rem;border-radius:.35rem;background:#e2e8f0;color:#334155}.good{background:#dcfce7;color:#166534}.warn{background:#fef3c7;color:var(--amber)}.facts{list-style:none;padding:0;color:var(--muted);font:12px ui-monospace,monospace}.facts li{margin:.15rem 0}.diagram{border:1px solid var(--line);border-radius:.5rem;background:#fff;padding:1rem;margin:1rem 0}.diagram svg{display:block;width:100%;height:auto}.label{font:12px var(--sans);fill:var(--muted)}.wins{padding-left:1.1rem;margin:.5rem 0}.wins li{margin:.2rem 0}.callout{border-left:3px solid var(--amber);background:#fffbeb;color:#713f12;padding:.6rem .9rem;border-radius:.25rem;font-size:.9rem}.matrix{width:100%;border-collapse:collapse;font-size:.88rem}.matrix th,.matrix td{text-align:left;vertical-align:top;border-bottom:1px solid var(--line);padding:.65rem}.matrix th{color:var(--deep);font-size:.75rem;text-transform:uppercase;letter-spacing:.05em}.source-trail li{margin:.35rem 0}.top{border-left:5px solid var(--brand)}
'''

def logo(): return '<div class="wordmark"><svg viewBox="0 0 164 195" width="22" aria-hidden="true"><path d="M117 194.5H0L12 73C17 67 21 65 28.5 64.5L34.5 0H151.5C158 4 161 7 163.5 13L153 119.5C149 127 145 130 135.5 130.5L131 184.5C128 190 125 193 117 194.5Z" fill="#01dc82"/><path d="M64 33L61 64.5H93.5L91 97H123L127.5 46.5C125 38 122 35 112.5 33H64Z" fill="#033330"/><path d="M37 147.5L41.5 98H74.5L71.5 129.5L104 130.5L100.5 162H49.5C42 159 40 156 37 147.5Z" fill="#033330"/></svg><span>Buildn</span></div>'

def head(title): return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,500;6..72,600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><style>{CSS}</style></head><body><main>'''
def foot(): return '</main></body></html>'
def svg(nodes,edges):
    parts=['<svg viewBox="0 0 760 150" role="img" aria-label="Signal map">','<defs><marker id="arr" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#94a3b8"/></marker></defs>']
    for x,y,w,h,label,color in nodes:
        xf,yf,wf,hf=map(float,(x,y,w,h)); parts += [f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="7" fill="{color}" stroke="#cbd5e1"/><text x="{xf+wf/2}" y="{yf+27}" text-anchor="middle" class="label">{escape(label)}</text>']
    for x1,y1,x2,y2,red in edges: parts.append(f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{"#b3261e" if red else "#94a3b8"}" stroke-dasharray="{"5 4" if red else "0"}" marker-end="url(#arr)"/>')
    return '<div class="diagram">'+''.join(parts)+'</svg></div>'

lanes=[
 {'slug':'agent-cost-memory-controls','title':'Agent Cost + Memory Controls','rationale':'GitHub’s same-day Copilot updates connect three operational controls that are usually shipped separately: persistent context, local-model escape hatches, and token-level cost attribution.','readout':'The practical shift is from “use an agent” to “operate an agent portfolio.” Memory needs a toggle and ownership model; local inference needs a workload boundary; token detail makes cost a debuggable engineering variable.','nodes':[('20',55,155,44,'Memory toggle','#f0fdf4'),('220',55,155,44,'Ollama / BYOK','#f0fdf4'),('420',55,155,44,'Token ledger','#fefce8'),('620',55,120,44,'Policy','#dcfce7')],'edges':[(175,77,220,77,False),(375,77,420,77,False),(575,77,620,77,True)],'items':[
  ('Copilot memory and Ollama in JetBrains','https://github.blog/changelog/2026-08-11-copilot-memory-and-ollama-in-github-copilot-for-jetbrains/','release','Persistent cross-session memory, Ollama BYOK, enterprise-managed settings, and better MCP/Codex reliability arrive together.','Pilot memory only for stable project preferences; route sensitive or repetitive tasks to a local Ollama model where quality permits.','Memory can retain stale or sensitive context; BYOK support is not the same as a complete local-first privacy boundary.','Define a memory retention test and compare one local model against one hosted model.'),
  ('Per-model token breakdown in usage reports','https://github.blog/changelog/2026-08-11-per-model-token-breakdown-in-the-usage-report/','release','Admins can now see input, output, cache-read, and cache-write tokens per model alongside AI credits.','Use the export as a baseline for workflow cost attribution and cache hygiene, then feed it into a weekly route review.','The report explains consumption, not outcome quality; pair it with task success and review-time measures.','Download one report and build a top-five cost-by-workflow table.'),
  ('MAI-Code-1.1-Flash in GitHub Copilot','https://github.blog/changelog/2026-08-11-mai-code-1-1-flash-available-in-github-copilot','release','A smaller coding model adds vision, improved tool use, and a 73% lower list price than its predecessor; the old model is being deprecated.','Use it for low-risk triage, visual bug intake, and first-pass edits while reserving larger models for design or architecture decisions.','Business and Enterprise admins must enable the policy; benchmark claims need a task replay.','Replay 20 routine coding tasks and compare quality, latency, and credits.'),
 ]},
 {'slug':'edge-resilience-under-machine-speed','title':'Edge Resilience Under Machine-Speed Attacks','rationale':'The latest Cloudflare threat report fills a security and infrastructure gap with quantified evidence that short attacks can still demand always-on controls.','readout':'Security posture is becoming an availability product, not an incident ritual. The useful design response is to automate the first containment layer, instrument the path, and reserve human judgment for policy changes rather than the first seconds of an attack.','nodes':[('20',55,155,44,'Small bursts','#fef2f2'),('220',55,155,44,'DNS / CLDAP','#fef2f2'),('420',55,155,44,'Auto-mitigation','#dcfce7'),('620',55,120,44,'Continuity','#dcfce7')],'edges':[(175,77,220,77,True),(375,77,420,77,False),(575,77,620,77,False)],'items':[
  ('Cloudflare DDoS Threat Report — H1 2026','https://blog.cloudflare.com/ddos-threat-report-2026-h1/','report','Cloudflare reports 23.2 million network-layer attacks in H1, 935 above 1 Tbps, and a shift toward DNS reflection/amplification.','Treat edge protection, DNS resilience, and rate limits as default client architecture rather than add-ons.','Cloudflare’s data is vendor telemetry; local exposure, provider concentration, and application-layer risk still need separate measurement.','Run a 30-minute resilience review: DNS, origin exposure, rate limits, and failover.'),
  ('1 Tbps attacks rose 519% quarter over quarter','https://blog.cloudflare.com/ddos-threat-report-2026-h1/','finding','Q2 accounted for 805 attacks above 1 Tbps, while 90.60% of attacks ended within ten minutes.','Short duration strengthens the case for pre-authorized automated controls and clear rollback paths.','Large-volume figures do not predict a specific client’s likelihood; use them to test assumptions, not to create fear.','Document which mitigations may execute without human approval.'),
  ('DNS attacks became the dominant vector','https://blog.cloudflare.com/ddos-threat-report-2026-h1/','finding','DNS-based attacks represented 34.3% of H1 network-layer activity; DNS floods reached 40% in Q2.','Make DNS provider health, TTL strategy, and authoritative-path monitoring part of the service map.','DNS changes can create their own blast radius; separate emergency controls from routine configuration.','Add DNS failure and cache-staleness scenarios to the next tabletop.'),
 ]},
 {'slug':'open-infrastructure-beyond-models','title':'Open Infrastructure Beyond Models','rationale':'Google’s August 11 OpenROAD commitment opens a neglected hardware and open-infrastructure lane: the leverage may be in reproducible compute foundations, not another model wrapper.','readout':'Open source is widening from software packages to the silicon toolchain. This is not an immediate Buildn dependency, but it is a useful long-horizon signal for local-first compute, supply-chain visibility, and clients who need more control over infrastructure primitives.','nodes':[('20',55,155,44,'Open tooling','#f0fdf4'),('220',55,155,44,'Chip design','#f0fdf4'),('420',55,155,44,'Reproducible build','#dcfce7'),('620',55,120,44,'Local leverage','#dcfce7')],'edges':[(175,77,220,77,False),(375,77,420,77,False),(575,77,620,77,False)],'items':[
  ('Google joins the OpenROAD Initiative','https://opensource.googleblog.com/2026/%20google-joins-the-openroad-initiative-as-principal-member-to-accelerate-open-source-silicon-innovation.html','announcement','Google joined OpenROAD as a principal member to accelerate open-source silicon innovation.','Track the project as a reference for transparent, inspectable infrastructure pipelines and future edge-compute experiments.','The announcement page is light on implementation detail; the practical value today is strategic, not a ready-to-run integration.','Watch the initiative’s repository and identify one local-compute use case worth benchmarking.'),
  ('Open source reaches the physical stack','https://opensource.googleblog.com/2026/','ecosystem','Google’s 2026 open-source blog places OpenROAD in a broader ecosystem of tools, standards, and infrastructure contributions.','Use the signal to widen technology scouting beyond SaaS and model releases when evaluating durable client leverage.','Ecosystem membership does not guarantee near-term maturity, support, or production suitability.','Add “open hardware / silicon tooling” to the quarterly opportunity scan.'),
  ('Reproducibility is the common thread','https://opensource.googleblog.com/2026/%20google-joins-the-openroad-initiative-as-principal-member-to-accelerate-open-source-silicon-innovation.html','lens','A transparent design toolchain makes artifacts, versions, and build conditions inspectable—similar to a well-governed agent runtime.','Borrow the pattern for Buildn: version prompts, tools, environments, and outputs as one reviewable chain.','This is an analogy, not evidence that OpenROAD solves agent reproducibility.','Sketch a minimal “build manifest” for one agent-delivered artifact.'),
 ]}
]

def lane_html(l):
    cards=''
    for title,url,kind,what,use,caveat,action in l['items']:
        cards+=f'''<article class="card"><div class="badges"><span class="badge good">{escape(kind)}</span><span class="badge">fresh signal</span></div><h2>{escape(title)}</h2><ul class="facts"><li>source: {escape(url)}</li><li>published / updated: 2026-08-11</li></ul><h3>What it is</h3><p>{escape(what)}</p><h3>Buildn / client use</h3><p>{escape(use)}</p><h3>Why useful now</h3><p>{escape(action)}</p><div class="callout"><strong>Caveat:</strong> {escape(caveat)}</div></article>'''
    return head(f'Daily Ingest Dossier — {l["title"]}')+f'''<header>{logo()}<h1>Daily Ingest Dossier — {escape(l['title'])}</h1><div class="date">{DATE} · adaptive lane</div><p class="readout">{escape(l['readout'])}</p><p><a href="index.html">← today’s overview</a></p></header><section><article class="card"><h2>Signal map</h2>{svg(l['nodes'],l['edges'])}<p>{escape(l['rationale'])}</p></article>{cards}<article class="card"><h2>Use-case matrix</h2><table class="matrix"><tr><th>Theme</th><th>Buildn OS</th><th>Client work</th><th>Agent workflows</th><th>Personal leverage</th></tr><tr><td>Control surface</td><td>Budget and review evidence</td><td>Measured rollout</td><td>Explicit permissions</td><td>Repeatable defaults</td></tr><tr><td>First experiment</td><td>Instrument one path</td><td>Replay one workflow</td><td>Set a rollback</td><td>Keep a short log</td></tr></table></article><article class="card"><h2>Top actions</h2><ol class="wins"><li>{escape(l['items'][0][6])}</li><li>{escape(l['items'][1][6])}</li><li>Capture the result as a dated artifact.</li></ol></article><article class="card"><h2>Source trail</h2><ol class="source-trail">{''.join(f'<li><a href="{escape(x[1])}">{escape(x[0])}</a></li>' for x in l['items'])}</ol></article></section>{foot()}'''

thesis='Today’s signal moves the operating surface outward: agents need cost and memory controls, internet-facing systems need always-on resilience, and open infrastructure is expanding below the software layer.'
ledger={'date':DATE,'generated_at':NOW,'editorial_thesis':thesis,'topic_groups':[]}
for l in lanes:
    sources=[]
    for title,url,kind,what,use,caveat,action in l['items']:
        sources.append({'title':title,'url':url,'source_type':kind,'published_or_updated':'2026-08-11','why_selected':what,'usefulness':use})
    ledger['topic_groups'].append({'slug':l['slug'],'title':l['title'],'selection_rationale':l['rationale'],'sources':sources})
    html=lane_html(l); (ART/f'daily-ingest-{l["slug"]}-{KEY}.html').write_text(html); (PAGES/DATE/f'{l["slug"]}.html').write_text(html)

links=''.join(f'<article class="card"><div class="badges"><span class="badge good">selected lane</span></div><h2><a href="{l["slug"]}.html">{escape(l["title"])}</a></h2><p>{escape(l["rationale"])}</p></article>' for l in lanes)
overview=head(f'Daily Ingest Dossier — {DATE}')+f'''<header>{logo()}<h1>Daily Ingest Dossier — {DATE}</h1><div class="date">Adaptive discovery · 3 lanes selected</div><p class="readout">{escape(thesis)} The editorial choice favors fresh primary-source signals with direct experiments over a fixed daily subject quota.</p></header><section>{links}<article class="card top"><h2>Top three today</h2><ol class="wins"><li>Download GitHub’s per-model token report and turn cost into a workflow metric.</li><li>Run a DNS and edge-resilience review before the next client launch.</li><li>Track OpenROAD as a long-horizon local-compute and reproducibility signal.</li></ol></article><article class="card"><h2>Source trail</h2><ol class="source-trail">{''.join(f'<li><a href="{escape(x[1])}">{escape(x[0])}</a></li>' for l in lanes for x in l['items'])}</ol></article></section>{foot()}'''
(ART/f'daily-ingest-overview-{KEY}.html').write_text(overview); (PAGES/DATE/'index.html').write_text(overview); (ART/f'daily-ingest-{KEY}.json').write_text(json.dumps(ledger,indent=2,ensure_ascii=False)+'\n'); (PAGES/DATE/'ledger.json').write_text(json.dumps(ledger,indent=2,ensure_ascii=False)+'\n')
print(json.dumps({'lanes':[l['slug'] for l in lanes],'artifacts':len(lanes)+2}))
