from pathlib import Path
import html, json
from datetime import datetime, timezone

DATE='2026-07-28'; STAMP='20260728'
OUT=Path('/root/Projects/artifact-library/artifacts/daily-ingest')
OUT.mkdir(parents=True, exist_ok=True)
logo='''<svg viewBox="0 0 164 195" width="22" aria-hidden="true"><path d="M117 194.5H0L12 73C17.47 66.63 21.3 65.46 28.5 64.5L34.5 0H151.5C158.44 4.4 161.28 7.18 163.5 13L153 119.5C148.8 127.15 144.97 129.55 135.5 130.5L131 184.5C127.71 190.35 125.13 192.98 117 194.5Z" fill="#01dc82"/><path d="M64 33L61 64.5H93.5L91 97H123L127.5 46.5C125.53 37.94 122.01 35.19 112.5 33H64Z" fill="#033330"/><path d="M37 147.5L41.5 98H74.5L71.5 129.5L104 130.5L100.5 162H49.5C41.82 159.35 39.68 155.53 37 147.5Z" fill="#033330"/></svg>'''
css='''<style>:root{--brand:#01dc82;--deep:#033330;--lime:#cfe66a;--red:#b3261e;--amber:#9a6700;--ink:#0f172a;--muted:#475569;--line:#e2e8f0;--bg:#fafaf9;--card:#fff;--serif:"Newsreader",Georgia,serif;--sans:"Plus Jakarta Sans",system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:var(--sans);line-height:1.55}main{max-width:70rem;margin:auto;padding:3rem 1.5rem 5rem}.wordmark{display:flex;align-items:center;gap:.55rem;font-weight:700;color:var(--deep)}header{margin-bottom:2rem}h1,h2,h3{font-family:var(--serif);color:var(--deep)}h1{font-size:2.35rem;line-height:1.12;margin:.85rem 0 .4rem}h2{font-size:1.45rem;margin:0 0 .45rem}h3{font-size:1.06rem;margin:.1rem 0 .38rem}p{margin:.45rem 0 .85rem}a{color:#087c54}.date,.facts{font:.78rem ui-monospace,SFMono-Regular,monospace;color:var(--muted)}.card{background:var(--card);border:1px solid var(--line);border-radius:.8rem;padding:1.35rem;margin:1.1rem 0}.badges{display:flex;gap:.45rem;flex-wrap:wrap;margin-bottom:.75rem}.badge{font-size:.68rem;text-transform:uppercase;letter-spacing:.07em;font-weight:700;padding:.16rem .48rem;border-radius:.35rem;background:#e2e8f0;color:#334155}.good{background:#dcfce7;color:#166534}.warn{background:#fef3c7;color:#854d0e}.diagram{margin:1rem 0;border:1px solid var(--line);border-radius:.55rem;padding:.8rem;background:#fff}.diagram svg{display:block;width:100%;height:auto}.label{font:600 10px var(--sans);letter-spacing:.08em;fill:#475569}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:.75rem}.mini{padding:.8rem;border:1px solid var(--line);border-radius:.5rem}.callout{border-left:3px solid var(--amber);background:#fffbeb;color:#713f12;padding:.65rem .85rem;border-radius:.25rem;font-size:.9rem}.wins{padding-left:1.2rem;margin:.5rem 0}.wins li{margin:.18rem 0}.matrix{width:100%;border-collapse:collapse;font-size:.86rem}.matrix th,.matrix td{border-bottom:1px solid var(--line);padding:.55rem;text-align:left;vertical-align:top}.matrix th{color:var(--deep)}.top{border-left:4px solid var(--brand)}.hl{background:color-mix(in srgb,var(--lime) 60%,transparent);padding:0 .15em}</style>'''
def page(title, readout, sources, actions, matrix):
    signal=''.join(f'<rect x="{12+i*150}" y="35" width="128" height="54" rx="7" fill="#fff" stroke="#cbd5e1"/><text x="{76+i*150}" y="58" text-anchor="middle" class="label">{html.escape(s["title"][:17])}</text><text x="{76+i*150}" y="73" text-anchor="middle" class="label">{html.escape(s["source_type"])}</text>' for i,s in enumerate(sources))
    cards=''.join(f'''<article class="card"><div class="badges"><span class="badge good">{html.escape(s['source_type'])}</span><span class="badge">{html.escape(s['published_or_updated'])}</span></div><h2><a href="{html.escape(s['url'])}">{html.escape(s['title'])}</a></h2><p><strong>What:</strong> {html.escape(s['what'])}</p><p><strong>Why it matters:</strong> {html.escape(s['why_selected'])}</p><p><strong>Buildn / client use:</strong> {html.escape(s['usefulness'])}</p><p><strong>Useful now:</strong> {html.escape(s['now'])}</p><div class="callout"><strong>Caveat:</strong> {html.escape(s['caveat'])}</div><p><strong>Follow-up:</strong> {html.escape(s['action'])}</p></article>''' for s in sources)
    rows=''.join(f'<tr><th>{html.escape(r[0])}</th><td>{html.escape(r[1])}</td><td>{html.escape(r[2])}</td><td>{html.escape(r[3])}</td><td>{html.escape(r[4])}</td></tr>' for r in matrix)
    trail=''.join(f'<li><a href="{html.escape(s["url"])}">{html.escape(s["title"])}</a></li>' for s in sources)
    acts=''.join(f'<li>{html.escape(a)}</li>' for a in actions)
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily Ingest Dossier — {html.escape(title)} — {DATE}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">{css}</head><body><main><header><div class="wordmark">{logo}<span>Buildn</span></div><div class="date">DAILY INGEST DOSSIER · {DATE}</div><h1>{html.escape(title)}</h1><p>{html.escape(readout)}</p></header><section><article class="card"><h2>Signal map</h2><div class="diagram"><svg viewBox="0 0 470 125" role="img" aria-label="Today's source cluster"><path d="M75 28V14H375V28" fill="none" stroke="#01dc82" stroke-width="2"/>{signal}</svg></div><p class="facts">PRIMARY SOURCES · FRESH RELEASES / PAPERS · BOUNDED EXPERIMENTS</p></article>{cards}<article class="card"><h2>Use-case matrix</h2><table class="matrix"><thead><tr><th>Theme</th><th>Buildn OS</th><th>Client work</th><th>Agent workflows</th><th>Personal leverage</th></tr></thead><tbody>{rows}</tbody></table></article><article class="card top"><h2>Top actions</h2><ul class="wins">{acts}</ul></article><article class="card"><h2>Source trail</h2><ul class="wins">{trail}</ul></article></section></main></body></html>'''
lanes=[
('stateless-mcp-migration','Stateless MCP Migration','MCP’s July release candidate makes protocol sessions optional, but it is a breaking change. Treat it as an infrastructure migration: inventory sessionful features, dual-run a legacy route, and make state explicit in tool arguments.',[
{'title':'MCP 2026-07-28 release candidate','url':'https://blog.modelcontextprotocol.io/posts/2026-07-28-release-candidate/','source_type':'release','published_or_updated':'2026-07-28','what':'A breaking, stateless-core MCP revision with extensions, stronger authorization alignment, and explicit state handles.','why_selected':'The protocol revision changes how remote tool servers scale, route, cache, and request user input.','usefulness':'Audit Buildn MCP servers for hidden session dependence; model durable state as explicit IDs.','now':'The release candidate starts the compatibility clock before final adoption.','caveat':'Stateless transport does not make an application stateless; handles still need access control and lifecycle rules.','action':'Create a one-page inventory of session, stream, replay, and server-push dependencies.'},
{'title':'Cloudflare Agents SDK v0.20.0','url':'https://developers.cloudflare.com/changelog/post/2026-07-27-agents-sdk-v0.20.0-mcp-sdk-v2/','source_type':'release','published_or_updated':'2026-07-27','what':'A concrete SDK v2 path that serves new and legacy MCP clients from a compatible route.','why_selected':'It turns the protocol change into a deployable migration pattern: factory handler, fallback, and parallel legacy support.','usefulness':'Use the handler pattern as a reference for Workers-hosted client tools.','now':'McpAgent is deprecated and feature-frozen.','caveat':'Sessionful RPC, standalone streams, replay, and pushed requests require deliberate bridging.','action':'Prototype one read-only tool behind the v2 factory and exercise both protocol generations.'}],['Build a dependency inventory before changing routes.','Pilot a read-only v2 tool with dual compatibility.','Write explicit handle and authorization rules.'],[('Protocol migration','Inventory endpoints','Offer a transition plan','Dual-route test','Understand explicit state'),('Tool design','Version contracts','Trace user confirmation','Pass scoped handles','Keep context portable')]),
('residency-and-realtime-agents','Residency + Real-time Agent Transport','AI gateways are gaining two operational controls at once: provable regional placement and persistent Responses sessions. Use them only where the workload and evidence model justify their added routing and connection complexity.',[
{'title':'Regional inference on AI Gateway','url':'https://vercel.com/changelog/regional-inference-now-available-on-ai-gateway','source_type':'release','published_or_updated':'2026-07-27','what':'A single request option pins inference to US or EU, with served-region confirmation returned in the response.','why_selected':'It converts an informal residency promise into a request-level control that can be logged and checked.','usefulness':'Build a region assertion into client workflows handling residency-sensitive briefs.','now':'Without the setting, routing remains global; compliance is opt-in.','caveat':'Regional capacity can fail closed and commonly costs more.','action':'Add region, provider, and served-region fields to one agent run log.'},
{'title':'WebSocket mode for OpenAI Responses API','url':'https://vercel.com/changelog/websocket-support-for-openai-responses-api-live-on-ai-gateway','source_type':'release','published_or_updated':'2026-07-27','what':'Persistent Responses API connections that continue with previous_response_id instead of resending full context.','why_selected':'Long tool-call rollouts can reduce repeated context transfer and improve interactive latency.','usefulness':'Benchmark a supervised, multi-tool client workflow against current HTTP behavior.','now':'The route supports store=false and Zero Data Retention.','caveat':'Persistent sockets require reconnect, timeout, backpressure, and audit handling.','action':'Measure latency, token transfer, and recovery behavior across 20-tool test runs.'}],['Log served region before promising residency.','Benchmark WebSockets on one tool-heavy workflow.','Keep HTTP fallback and explicit reconnect policy.'],[('Residency evidence','Record served region','Clarify data boundaries','Pin qualifying requests','Choose appropriate defaults'),('Long tool runs','Log request chain','Improve live handoff','Reuse response state','Reduce repeated context')]),
('evidence-first-agent-memory','Evidence-first Agent Memory','Two fresh papers argue for a useful production principle: memory and search output should be transformed into inspectable evidence before an agent answers or acts. The methods are research, but the evidence boundary is immediately usable.',[
{'title':'MemChain: interpretable memory traces','url':'https://arxiv.org/abs/2607.24097','source_type':'paper','published_or_updated':'2026-07-27','what':'A trainable post-retrieval policy that plans, orders, and acts on memory candidates before answer generation.','why_selected':'It makes the intermediate evidence context inspectable rather than treating raw retrieval as ready-to-use truth.','usefulness':'Adopt the artifact pattern: plan, selected evidence, conflicts, and final answer.','now':'The paper reports compact contexts and strong benchmark results without fine-tuning answer models.','caveat':'Claims are preprint results; do not infer production reliability or licensing fit.','action':'Add an evidence packet to one Buildn knowledge-agent evaluation set.'},
{'title':'EviBack: evidence-constrained teacher backoff','url':'https://arxiv.org/abs/2607.23955','source_type':'paper','published_or_updated':'2026-07-27','what':'An Agentic RAG training approach that separates evidence adequacy from answer refinement.','why_selected':'The separation guards against a polished answer being mistaken for an adequately supported one.','usefulness':'Use an evidence-sufficiency gate before drafting client-facing research claims.','now':'It reports fewer duplicate searches and forced terminations alongside answer-quality gains.','caveat':'Code is not yet available and reported outcomes need independent reproduction.','action':'Define a “insufficient evidence” result path in one research workflow.'}],['Add evidence sufficiency to research-agent outputs.','Store selected sources and rejected conflicts.','Evaluate abstention before optimizing prose.'],[('Memory retrieval','Keep evidence packet','Explain recommendation basis','Show selection trace','Retrieve less, decide better'),('Research answers','Require citations','Gate client claims','Allow abstention','Preserve an audit trail')])]
ledger={'date':DATE,'generated_at':datetime.now(timezone.utc).isoformat(),'editorial_thesis':'The day’s leverage is operational evidence: make protocol state explicit, verify where requests run, and make agent memory and research support inspectable before action.','topic_groups':[]}
for slug,title,readout,sources,actions,matrix in lanes:
    ledger['topic_groups'].append({'slug':slug,'title':title,'selection_rationale':'Fresh primary releases or research in a coverage gap; selected for a bounded, inspectable operational experiment.','sources':[{k:s[k] for k in ('title','url','source_type','published_or_updated','why_selected','usefulness')} for s in sources]})
    (OUT/f'daily-ingest-{slug}-{STAMP}.html').write_text(page(title,readout,sources,actions,matrix))
(OUT/f'daily-ingest-{STAMP}.json').write_text(json.dumps(ledger,indent=2))
links=''.join(f'<article class="card"><h2>{title}</h2><p>{readout}</p><p><a href="{slug}.html">Open lane dossier →</a></p></article>' for slug,title,readout,*_ in lanes)
overview=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily Ingest Dossier — Overview — {DATE}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">{css}</head><body><main><header><div class="wordmark">{logo}<span>Buildn</span></div><div class="date">DAILY INGEST DOSSIER · {DATE}</div><h1>Make the evidence boundary explicit</h1><p>Today’s selection rotates away from yesterday’s model, cost, and design coverage. The common thread: predictable systems expose state, placement, and evidence instead of leaving them implicit.</p></header><section><article class="card"><h2>Editorial thesis</h2><p><span class="hl">Make protocol state explicit, verify where requests run, and make memory evidence inspectable before action.</span></p></article>{links}<article class="card top"><h2>All-lanes top three</h2><ol class="wins"><li>Inventory MCP sessionful dependencies before the v2 migration.</li><li>Log requested and served inference region for sensitive workflows.</li><li>Add an evidence-sufficiency gate to research-agent outputs.</li></ol></article></section></main></body></html>'''
(OUT/f'daily-ingest-overview-{STAMP}.html').write_text(overview)
