from pathlib import Path
from datetime import datetime, timezone
import json, html

DATE='2026-08-07'; DATEKEY='20260807'
pages=Path('/root/Projects/daily-ingest-pages')/DATE
art=Path('/root/Projects/artifact-library/artifacts/daily-ingest')
pages.mkdir(parents=True, exist_ok=True); art.mkdir(parents=True, exist_ok=True)

data={
 'date':DATE,
 'generated_at':datetime.now(timezone.utc).isoformat(),
 'editorial_thesis':'Today’s strongest practical signal is not another general-purpose agent: it is the operating detail around live interaction, cross-functional delivery, and narrow safety controls that lets automation become usable in real work.',
 'topic_groups':[
  {'slug':'realtime-agent-systems','title':'Realtime Agent Systems','selection_rationale':'A new primary architecture write-up makes the fast-path/slow-path split concrete, while current browser tooling offers an immediately testable client-side feedback surface.','sources':[
   {'title':'How OpenAI built GPT-Live','url':'https://openai.com/index/continuous-voice-interaction-with-gpt-live/','source_type':'engineering blog','published_or_updated':'2026-08-03','why_selected':'It documents a production full-duplex voice architecture rather than announcing a model feature.','usefulness':'Use its fast-path boundary as a design review checklist for voice, browser, and streaming client work.','what':'A six-month rebuild of realtime voice around continuous, stateful audio; tools, persistence, and deeper reasoning run asynchronously.','matters':'The decisive design is isolation: a slow tool must not interrupt the media loop.','use':'For Buildn/client voice copilots, keep audio transport and frame scheduling independent from retrieval, CRM calls, or approval workflows.','caveat':'This is an architectural account, not a reusable hosted component; measure end-to-end jitter and interruption behavior yourself.','action':'Diagram one proposed live workflow and label every synchronous dependency.'},
   {'title':'Cloudflare Internal DNS is generally available','url':'https://blog.cloudflare.com/internal-dns/','source_type':'product release','published_or_updated':'2026-08-06','why_selected':'It consolidates private authoritative DNS, recursive resolution, policy, and auditability in one control plane.','usefulness':'It is a credible option when private tool endpoints and split-horizon names become deployment friction.','what':'Private authoritative zones, DNS views, and Gateway resolver policies on Cloudflare’s network.','matters':'Agent tools often need internal services; name resolution and who can resolve a name are part of the boundary.','use':'Assess it for client environments that already use Cloudflare Gateway and need private MCP, staging, or database service names.','caveat':'Enterprise Gateway availability and a Cloudflare control-plane dependency make this unsuitable as a casual local-dev default.','action':'Inventory internal hostnames and identify where split-horizon DNS is currently duplicated.'},
   {'title':'Chrome DevTools 151 release notes','url':'https://developer.chrome.com/docs/devtools/release-notes','source_type':'release notes','published_or_updated':'2026-07-28','why_selected':'The latest release adds CSS specificity breakdowns and AI-assistance widgets; the same release stream documents stable DevTools-for-agents tooling.','usefulness':'It provides a local, inspectable feedback loop before automating visual fixes in a client site.','what':'Chrome 151’s DevTools update, including CSS specificity inspection and AI-assistance UI improvements.','matters':'Visual-agent reliability improves when the agent can interrogate the actual rendering and CSS cascade.','use':'Add a DevTools MCP-assisted reproduction step to front-end QA, then retain human review for the final diff.','caveat':'Treat browser assistance as diagnostic support; it does not validate product intent, accessibility, or regression coverage.','action':'Try it on one stubborn CSS override and record whether the diagnosis reduces edit/retest cycles.'}
  ]},
  {'slug':'collaborative-agent-delivery','title':'Collaborative Agent Delivery','selection_rationale':'Figma’s fresh account of shipping a complex permissions feature and two newly visible open-source workflow surfaces point to a coverage gap: agents help most when the team’s proposal-and-review loop is explicit.','sources':[
   {'title':'Code, craft, and the making of nested folders','url':'https://www.figma.com/blog/code-craft-and-the-making-of-nested-folders/','source_type':'engineering blog','published_or_updated':'2026-08-03','why_selected':'It is a detailed primary case study of changing collaboration mechanics during a difficult permissions-model rebuild.','usefulness':'It gives Buildn a practical operating pattern: prototype in code, test in staging, then converge with cross-functional review.','what':'Figma’s account of delivering nested folders by using code and staging as proposals instead of waiting for complete handoffs.','matters':'The valuable pattern is not role blur; it is short, inspectable feedback loops with a real artifact.','use':'Run client discovery as a thin vertical slice in staging, with a named decision owner and visible acceptance checks.','caveat':'Merging rough work into staging is safe only with containment, rollback, and a clear distinction from production.','action':'For the next ambiguous request, open a small proposal PR before drafting a full implementation plan.'},
   {'title':'Tracewell','url':'https://github.com/Tracewell-code/Tracewell','source_type':'repo','published_or_updated':'2026-08-05','why_selected':'This newly created open-source workspace focuses on building, running, and observing workflow automations rather than only prompting them.','usefulness':'It is a quick scan candidate for teams that need a visual operations surface around repeatable automations.','what':'An early open-source visual workspace for workflow automation construction, execution, and observation.','matters':'The interface framing—build, run, observe—matches the operational lifecycle client automations need.','use':'Evaluate its workflow model for internal prototypes; borrow the surface pattern even if the project is not adopted.','caveat':'A very new repository: validate maintainer activity, security model, and deployment maturity before client use.','action':'Open the repo and assess licensing, persistence, credentials, and run-history design in 30 minutes.'},
   {'title':'hud-mode','url':'https://github.com/adrida/hud-mode','source_type':'repo','published_or_updated':'2026-08-05','why_selected':'A small new open-source HUD targets the neglected moment while a coding agent works and when it stops.','usefulness':'It may reduce context-switching for supervised Claude Code, Codex, or OpenCode work.','what':'A compact heads-up display for coding-agent status and completion state.','matters':'Supervision fails when an agent’s state is invisible; a minimal status surface can make review timing deliberate.','use':'Try it on one local coding task and compare interruption frequency with the current terminal-only workflow.','caveat':'It is early-stage and should receive no credentials or privileged execution rights merely for convenience.','action':'Test it in an isolated repository and keep the existing terminal log as the source of truth.'}
  ]},
  {'slug':'safety-classifiers-trusted-access','title':'Safety Classifiers + Trusted Access','selection_rationale':'Anthropic’s same-day update is unusually concrete about a hard operational trade-off: reduce false positives without flattening safeguards for genuinely dual-use work.','sources':[
   {'title':'Improving Fable 5’s biology safeguards','url':'https://www.anthropic.com/news/improving-fable-5-s-biology-safeguards','source_type':'product announcement','published_or_updated':'2026-08-07','why_selected':'It reports an explicit classifier refinement, quantified fallback reductions, and continued restrictions for dual-use professional biology tasks.','usefulness':'It is a useful governance pattern for any high-impact workflow: tune the routing boundary, preserve escalation, and measure collateral friction.','what':'Anthropic refined Fable 5’s biology classifier, reporting about 85% fewer biology-related fallbacks while retaining restricted routing for dual-use work.','matters':'A blanket block is not a durable product boundary; the operational question is how to lower benign friction without expanding hazardous access.','use':'Apply the pattern to Buildn/client agent controls: classify requests, log uncertainty, route sensitive cases to a less-capable path or human approval.','caveat':'The figures are vendor-reported and biology-specific. Do not infer equivalent accuracy for finance, HR, security, or legal workflows.','action':'Choose one risky tool action and define the benign path, escalation path, evidence captured, and reviewer.'}
  ]}
 ]
}

def esc(x): return html.escape(str(x),quote=True)
def logo(): return '<svg viewBox="0 0 164 195" width="22" aria-hidden="true"><path d="M117 194.5H0L12 73C17 66 21 65 28 64L34 0h117c7 4 10 7 12 13l-10 106c-4 8-8 10-18 11l-4 54c-3 6-6 9-14 10Z" fill="#01dc82"/><path d="m64 33-3 31h32l-2 33h32l5-51c-2-8-6-11-15-13H64Zm-27 115 5-50h33l-3 32 32 1-4 31H50c-8-3-10-7-13-14Z" fill="#033330"/></svg>'
css='''<style>:root{--brand:#01dc82;--deep:#033330;--lime:#cfe66a;--red:#b3261e;--amber:#9a6700;--ink:#0f172a;--muted:#475569;--line:#e2e8f0;--bg:#fafaf9;--card:#fff;--serif:Newsreader,Georgia,serif;--sans:"Plus Jakarta Sans",ui-sans-serif,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:var(--sans);line-height:1.55}main{max-width:68rem;margin:auto;padding:3rem 1.5rem}header{margin-bottom:2rem}.wordmark{display:flex;align-items:center;gap:.55rem;color:var(--deep);font-weight:700}.wordmark svg{height:24px}h1,h2,h3{font-family:var(--serif);color:var(--deep);line-height:1.15}h1{font-size:2.35rem;margin:.8rem 0 .4rem}h2{font-size:1.45rem;margin:0 0 .5rem}h3{font-size:1.1rem;margin:0}.deck{max-width:55rem;color:var(--muted)}section{display:grid;gap:1.25rem;margin:1.5rem 0}.card{background:var(--card);border:1px solid var(--line);border-radius:.8rem;padding:1.35rem}.badges{display:flex;gap:.45rem;flex-wrap:wrap;margin:.5rem 0 .8rem}.badge{font-size:.69rem;text-transform:uppercase;letter-spacing:.06em;font-weight:700;background:#f1f5f9;color:var(--muted);padding:.16rem .45rem;border-radius:.3rem}.good{background:#dcfce7;color:#166534}.warn{background:#fef3c7;color:var(--amber)}.facts{list-style:none;padding:0;margin:.65rem 0;font: .77rem ui-monospace,monospace;color:var(--muted)}.facts li{padding:.08rem 0}.diagram{border:1px solid var(--line);border-radius:.5rem;padding:.65rem;margin:1rem 0;background:#fff}.diagram svg{display:block;width:100%;height:auto}.label{font:600 11px var(--sans);fill:#475569}.label2{font:700 13px var(--sans);fill:#033330}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:.8rem}.mini{border-top:2px solid var(--brand);padding-top:.5rem}.wins{padding-left:1.1rem;margin:.5rem 0}.callout{border-left:3px solid var(--amber);background:#fffbeb;color:#713f12;padding:.6rem .85rem;border-radius:.2rem;font-size:.9rem}a{color:#087f55;font-weight:600}.matrix{width:100%;border-collapse:collapse;font-size:.84rem}.matrix th,.matrix td{padding:.5rem;text-align:left;border-bottom:1px solid var(--line)}.yes{color:#166534;font-weight:700}.no{color:#94a3b8}.top{border-left:4px solid var(--brand);background:#f0fdf4}footer{color:var(--muted);font-size:.78rem;margin-top:2rem}@media(max-width:560px){main{padding:2rem 1rem}h1{font-size:1.9rem}}</style>'''
head=lambda title: f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Newsreader:opsz,wght@6..72,400;6..72,500;6..72,600&family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">{css}</head><body><main>'''
def svg(title, n):
 boxes=''.join(f'<rect x="{18+i*142}" y="55" width="112" height="48" rx="7" fill="#fff" stroke="#cbd5e1"/><text x="{74+i*142}" y="77" text-anchor="middle" class="label2">{esc(s["title"][:16])}</text><text x="{74+i*142}" y="92" text-anchor="middle" class="label">signal {i+1}</text>'+(f'<path d="M{130+i*142} 79H{151+i*142}" stroke="#01dc82" stroke-width="2" marker-end="url(#a)"/>' if i<n-1 else '') for i,s in enumerate(title['sources']))
 return f'<div class="diagram"><svg viewBox="0 0 450 150" role="img" aria-label="Signal map"><defs><marker id="a" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 6 3 0 6Z" fill="#01dc82"/></marker></defs><text x="18" y="25" class="label">TODAY’S SIGNAL MAP</text>{boxes}<text x="225" y="132" text-anchor="middle" class="label">{esc(title["title"]).upper()} — TESTABLE, REVIEWABLE, BOUNDED</text></svg></div>'
def report(g):
 cards=''
 for i,s in enumerate(g['sources'],1):
  cards+=f'''<article class="card" id="item-{i}"><h2>{esc(s['title'])}</h2><div class="badges"><span class="badge good">{esc(s['source_type'])}</span><span class="badge">{esc(s['published_or_updated'])}</span><span class="badge warn">test before adoption</span></div><ul class="facts"><li>DIRECT — <a href="{esc(s['url'])}">{esc(s['url'])}</a></li></ul><div class="grid"><div class="mini"><h3>What it is</h3><p>{esc(s['what'])}</p></div><div class="mini"><h3>Why it matters</h3><p>{esc(s['matters'])}</p></div><div class="mini"><h3>Buildn / client use</h3><p>{esc(s['use'])}</p></div></div><div class="callout"><strong>Caveat.</strong> {esc(s['caveat'])}</div><p><strong>Next move:</strong> {esc(s['action'])}</p></article>'''
 matrix=''.join(f'<tr><td>{esc(s["title"])}</td><td class="yes">●</td><td class="yes">●</td><td class="yes">●</td><td class="no">—</td></tr>' for s in g['sources'])
 trail=''.join(f'<li><a href="{esc(s["url"])}">{esc(s["title"])}</a> <span class="badge">{esc(s["source_type"])}</span></li>' for s in g['sources'])
 return head('Daily Ingest Dossier — '+g['title'])+f'''<header><div class="wordmark">{logo()}<span>Buildn</span></div><h1>Daily Ingest Dossier — {esc(g['title'])}</h1><div class="badges"><span class="badge">{DATE}</span><span class="badge good">adaptive coverage</span></div><p class="deck">{esc(g['selection_rationale'])} This is a selective scan: {len(g['sources'])} primary-source signals, chosen over filler.</p></header><section><article class="card"><h2>Signal map</h2>{svg(g,len(g['sources']))}<p><span class="hl">Editorial read:</span> turn the signal into a bounded experiment, not a platform commitment.</p></article>{cards}<article class="card"><h2>Use-case matrix</h2><table class="matrix"><tr><th>Signal</th><th>Buildn OS</th><th>Client work</th><th>Agent workflows</th><th>Personal leverage</th></tr>{matrix}</table></article><article class="card top"><h2>Top actions</h2><ol>{''.join(f'<li><a href="#item-{i}">{esc(s["action"])}</a></li>' for i,s in enumerate(g['sources'],1))}</ol></article><article class="card"><h2>Source trail</h2><ul class="wins">{trail}</ul></article></section><footer>Daily Ingest • {DATE} • Primary sources linked directly</footer></main></body></html>'''

for g in data['topic_groups']:
 content=report(g)
 (pages/(g['slug']+'.html')).write_text(content)
 (art/(f'daily-ingest-{g["slug"]}-{DATEKEY}.html')).write_text(content)

lane_links=''.join(f'<article class="card"><h2>{esc(g["title"])}</h2><p>{esc(g["selection_rationale"])}</p><p><a href="{esc(g["slug"])}.html">Open lane dossier →</a></p><div class="badges"><span class="badge good">{len(g["sources"])} signals</span></div></article>' for g in data['topic_groups'])
top=[]
for g in data['topic_groups']:
 for s in g['sources']:
  top.append((g['title'],s['title'],s['action'],g['slug']))
top=top[:3]
overview=head('Daily Ingest — '+DATE)+f'''<header><div class="wordmark">{logo()}<span>Buildn</span></div><h1>Daily Ingest — {DATE}</h1><p class="deck">{esc(data['editorial_thesis'])}</p></header><section><article class="card"><h2>Today’s editorial thesis</h2><div class="diagram"><svg viewBox="0 0 600 150" role="img" aria-label="From novelty to operational leverage"><path d="M100 74H500" stroke="#01dc82" stroke-width="3"/><circle cx="100" cy="74" r="22" fill="#fff" stroke="#cbd5e1"/><circle cx="300" cy="74" r="22" fill="#fff" stroke="#01dc82" stroke-width="3"/><circle cx="500" cy="74" r="22" fill="#fff" stroke="#cbd5e1"/><text x="100" y="120" text-anchor="middle" class="label2">Novelty</text><text x="300" y="120" text-anchor="middle" class="label2">Bounded trial</text><text x="500" y="120" text-anchor="middle" class="label2">Operating leverage</text></svg></div></article>{lane_links}<article class="card top"><h2>All-lanes top three</h2><ol>{''.join(f'<li><strong>{esc(title)}</strong> — {esc(action)} <a href="{slug}.html">Open</a></li>' for lane,title,action,slug in top)}</ol></article></section><footer>Adaptive Daily Ingest • {DATE}</footer></main></body></html>'''
(pages/'index.html').write_text(overview)
(art/f'daily-ingest-overview-{DATEKEY}.html').write_text(overview)
ledger=json.dumps(data,indent=2,ensure_ascii=False)+'\n'
(pages/'ledger.json').write_text(ledger); (art/f'daily-ingest-{DATEKEY}.json').write_text(ledger)

coverage_path=Path('/root/Projects/daily-ingest-pages/topic-coverage.json')
coverage=json.loads(coverage_path.read_text())
summary=coverage.setdefault('rolling_theme_summary',{})
for g in data['topic_groups']:
 e=summary.setdefault(g['slug'],{'title':g['title'],'times_covered':0,'last_covered':None})
 e['title']=g['title']; e['times_covered']+=1; e['last_covered']=DATE
history=coverage.setdefault('item_history',[])
old=[x for x in history if x.get('date')!=DATE]
for g in data['topic_groups']:
 for s in g['sources']:
  old.append({'date':DATE,'lane':g['slug'],'title':s['title'],'url':s['url'],'source_type':s['source_type'],'selection_rationale':s['why_selected']})
cutoff='2026-06-23'
coverage['item_history']=[x for x in old if x.get('date','')>=cutoff]
coverage['updated_at']=data['generated_at']; coverage['last_run']={'date':DATE,'selected_lanes':[g['slug'] for g in data['topic_groups']],'editorial_thesis':data['editorial_thesis']}
coverage_path.write_text(json.dumps(coverage,indent=2,ensure_ascii=False)+'\n')
seen_path=Path('/root/Projects/daily-ingest-pages/seen-sources.json'); seen=json.loads(seen_path.read_text()); sources=seen.setdefault('sources',{})
for g in data['topic_groups']:
 for s in g['sources']:
  prior=sources.get(s['url'],{}); sources[s['url']]={'first_seen':prior.get('first_seen',DATE),'last_seen':DATE,'title':s['title']}
seen['updated_at']=data['generated_at']; seen_path.write_text(json.dumps(seen,indent=2,ensure_ascii=False)+'\n')
print('generated', pages)
